-- ============================================================================
-- Zephyriov — Opening catalog seed (generated by scripts/generate-seed.mjs)
-- Every line has been validated as a legal move sequence with chess.js.
-- Run once, after supabase/schema.sql, in the Supabase SQL editor.
-- ============================================================================
begin;

-- Ponziani Opening (C44)
insert into public.openings (slug, name, eco, playable_colors, detection_keys) values ('ponziani', 'Ponziani Opening', 'C44', '{white}', '{"ponziani"}');
insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'ponziani'), 'Main Line: 3...Nf6 4.d4', 1);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'Claim the center and open lines for the bishop and queen.'),
  (2, 'e5', 'Black stakes an equal claim in the center.'),
  (3, 'Nf3', 'Develop with tempo, attacking the e5 pawn.'),
  (4, 'Nc6', 'Defend e5 while developing a piece.'),
  (5, 'c3', 'The Ponziani: prepare d4 with full pawn support.'),
  (6, 'Nf6', 'Counterattack e4 instead of defending passively.'),
  (7, 'd4', 'Build the big center; c3 backs it up.'),
  (8, 'Nxe4', 'Grab the pawn — the critical test of the Ponziani.'),
  (9, 'd5', 'Push the knight question: c6 must move and e4 stays loose.'),
  (10, 'Ne7', 'Retreat toward g6 to hit the e5 fork ideas.'),
  (11, 'Nxe5', 'Win the pawn back with a strong central knight.'),
  (12, 'Ng6', 'Challenge the e5 knight immediately.'),
  (13, 'Qd4', 'Centralize: defend e5 and attack the e4 knight at once.'),
  (14, 'Qf6', 'Pile on e5 and offer to trade the attacked knight.'),
  (15, 'Qxe4', 'Collect the knight; material is even with a space edge.'),
  (16, 'Qxe5', 'Black regains the piece by taking the knight.'),
  (17, 'Qxe5+', 'Trade into a pleasant queenless middlegame with check.'),
  (18, 'Nxe5', 'Recapture; the knight is fine on e5 for now.'),
  (19, 'Bf4', 'Develop with tempo against the e5 knight.'),
  (20, 'd6', 'Solidify the knight and free the c8 bishop.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'ponziani' and ol.rank = 1;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'ponziani'), 'Jaenisch Counterattack: 3...d5', 2);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'Take the center.'),
  (2, 'e5', 'Symmetrical reply.'),
  (3, 'Nf3', 'Attack e5 and develop.'),
  (4, 'Nc6', 'Defend e5.'),
  (5, 'c3', 'Prepare the d4 break.'),
  (6, 'd5', 'The critical counter: strike e4 while c3 blocks the knight''s defense.'),
  (7, 'Qa4', 'The point: pin the c6 knight against the loose e5/d5 complex.'),
  (8, 'f6', 'Bolster e5 since the c6 knight is pinned.'),
  (9, 'Bb5', 'Add pressure on c6 and prepare to castle.'),
  (10, 'Ne7', 'Break the pin''s pressure by covering c6 again.'),
  (11, 'exd5', 'Win a central pawn while Black is tangled up.'),
  (12, 'Qxd5', 'Recapture; the queen is active but exposed.'),
  (13, 'O-O', 'Get the king safe before opening the center.'),
  (14, 'Bd7', 'Unpin the c6 knight and connect the queenside.'),
  (15, 'd4', 'Open the center against the centralized black queen.'),
  (16, 'e4', 'Black closes the center to blunt the initiative.'),
  (17, 'Nfd2', 'Reroute: the knight will hit e4 with f3 or Nc4.'),
  (18, 'f5', 'Support e4 and grab kingside space.'),
  (19, 'f3', 'Undermine the e4 pawn chain at its head.'),
  (20, 'exf3', 'Concede the center pawn to avoid losing it outright.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'ponziani' and ol.rank = 2;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'ponziani'), '3...Nf6 4.d4 exd4', 3);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'Take the center.'),
  (2, 'e5', 'Symmetrical reply.'),
  (3, 'Nf3', 'Attack e5 and develop.'),
  (4, 'Nc6', 'Defend e5.'),
  (5, 'c3', 'Prepare d4.'),
  (6, 'Nf6', 'Develop and hit e4.'),
  (7, 'd4', 'Seize the center.'),
  (8, 'exd4', 'Trade rather than let White keep the full pawn duo.'),
  (9, 'e5', 'Kick the f6 knight before recapturing on d4.'),
  (10, 'Nd5', 'The best square: centralized and hard to evict.'),
  (11, 'cxd4', 'Restore material with a strong pawn pair on d4/e5.'),
  (12, 'd6', 'Challenge the e5 spearhead immediately.'),
  (13, 'Bb5', 'Pin the c6 knight and prepare to castle.'),
  (14, 'Bd7', 'Break the pin calmly.'),
  (15, 'exd6', 'Resolve the tension and open lines while ahead in development.'),
  (16, 'Bxd6', 'Recapture with the bishop, finishing development.'),
  (17, 'O-O', 'King safety first.'),
  (18, 'O-O', 'Black castles too; the position is roughly level but easier for White.'),
  (19, 'Nc3', 'Develop with tempo, challenging the strong d5 knight.'),
  (20, 'Nxc3', 'Trade before the knight gets kicked by Ne4 ideas.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'ponziani' and ol.rank = 3;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'ponziani'), 'Passive Setup: 3...d6', 4);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'Take the center.'),
  (2, 'e5', 'Symmetrical reply.'),
  (3, 'Nf3', 'Attack e5 and develop.'),
  (4, 'Nc6', 'Defend e5.'),
  (5, 'c3', 'Prepare d4.'),
  (6, 'd6', 'A solid but passive way to hold e5.'),
  (7, 'd4', 'Take the center for free — this is why 3...d6 is harmless.'),
  (8, 'Nf6', 'Develop and eye e4.'),
  (9, 'Bd3', 'Modest but flexible: defend e4 and prepare O-O.'),
  (10, 'g6', 'Black opts for a fianchetto setup.'),
  (11, 'O-O', 'Castle while holding the strong center.'),
  (12, 'Bg7', 'Complete the fianchetto.'),
  (13, 'Re1', 'Support e4 and prepare central expansion.'),
  (14, 'O-O', 'Black castles.'),
  (15, 'h3', 'Deny g4 to the bishop and knight — a useful waiting move.'),
  (16, 'Re8', 'Put the rook opposite the white queen and e-pawns.'),
  (17, 'Nbd2', 'Develop the last minor piece, keeping c3 for the pawn.'),
  (18, 'exd4', 'Release the tension to free Black''s game.'),
  (19, 'cxd4', 'Recapture, keeping the ideal pawn duo on d4/e4.'),
  (20, 'd5', 'Strike back in the center at last.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'ponziani' and ol.rank = 4;

-- Caro-Kann: Fantasy Variation (B12)
insert into public.openings (slug, name, eco, playable_colors, detection_keys) values ('caro-kann-fantasy', 'Caro-Kann: Fantasy Variation', 'B12', '{white,black}', '{"fantasy variation"}');
insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'caro-kann-fantasy'), 'Main Line: 3...dxe4 4.fxe4 e5', 1);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'Take the center.'),
  (2, 'c6', 'The Caro-Kann: prepare ...d5 with pawn support.'),
  (3, 'd4', 'Build the full pawn center.'),
  (4, 'd5', 'Challenge e4 as planned.'),
  (5, 'f3', 'The Fantasy: hold e4 with a pawn and aim for a big center.'),
  (6, 'dxe4', 'The critical test: take and make White prove the setup.'),
  (7, 'fxe4', 'Recapture; White has a broad center and an open f-file.'),
  (8, 'e5', 'Strike immediately before White consolidates.'),
  (9, 'Nf3', 'Defend d4 by developing — never block the f-file with the king''s pawn.'),
  (10, 'Bg4', 'Pin the defender of d4 and e5.'),
  (11, 'Bc4', 'Target f7, the soft spot created by the open f-file.'),
  (12, 'Nd7', 'Reinforce e5 without blocking the c8 bishop''s pin.'),
  (13, 'O-O', 'Castle onto the half-open f-file — rook and bishop both eye f7.'),
  (14, 'Ngf6', 'Finish development and cover the e4-d5 squares.'),
  (15, 'c3', 'Solidify d4 and give the queen the b3 route.'),
  (16, 'Be7', 'Sensible development; ...O-O is next.'),
  (17, 'Qb3', 'Break the g4 pin and hit b7 and f7 simultaneously.'),
  (18, 'O-O', 'Castle into safety, returning material if needed.'),
  (19, 'Nbd2', 'Complete development, keeping the strong center intact.'),
  (20, 'Qc7', 'Connect the rooks and support e5.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'caro-kann-fantasy' and ol.rank = 1;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'caro-kann-fantasy'), 'French Setup: 3...e6', 2);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'Take the center.'),
  (2, 'c6', 'The Caro-Kann.'),
  (3, 'd4', 'Build the center.'),
  (4, 'd5', 'Challenge e4.'),
  (5, 'f3', 'The Fantasy setup, holding e4.'),
  (6, 'e6', 'A solid French-style reply, keeping the tension.'),
  (7, 'Be3', 'Support d4 and prepare Qd2 with quick development.'),
  (8, 'Nf6', 'Develop and pressure e4.'),
  (9, 'Nd2', 'Defend e4 flexibly, keeping c3 free for a pawn.'),
  (10, 'c5', 'The thematic break against White''s center.'),
  (11, 'c3', 'Keep the pawn chain intact — d4 is the anchor.'),
  (12, 'Nc6', 'Add pressure on d4.'),
  (13, 'Ne2', 'Develop while keeping f3-e4 solid; the knight may go to g3.'),
  (14, 'Be7', 'Prepare to castle.'),
  (15, 'e5', 'Gain space with tempo on the f6 knight.'),
  (16, 'Nd7', 'Retreat to hit e5 later with ...f6.'),
  (17, 'f4', 'Support e5 and clamp the kingside — a dream French structure.'),
  (18, 'O-O', 'King safety before the counterplay starts.'),
  (19, 'Nf3', 'Reinforce d4 and e5; White''s space advantage is stable.'),
  (20, 'cxd4', 'Open the c-file, Black''s main source of play.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'caro-kann-fantasy' and ol.rank = 2;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'caro-kann-fantasy'), 'Modern Setup: 3...g6', 3);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'Take the center.'),
  (2, 'c6', 'The Caro-Kann.'),
  (3, 'd4', 'Build the center.'),
  (4, 'd5', 'Challenge e4.'),
  (5, 'f3', 'The Fantasy setup.'),
  (6, 'g6', 'Black switches to a Modern-style fianchetto.'),
  (7, 'Nc3', 'Develop and support e4.'),
  (8, 'Bg7', 'Complete the fianchetto against d4.'),
  (9, 'Be3', 'Reinforce d4 and prepare queenside castling.'),
  (10, 'Nf6', 'Develop with pressure on e4.'),
  (11, 'Qd2', 'Connect Be3 and prepare O-O-O — opposite-side attacks.'),
  (12, 'O-O', 'Black commits the king to the kingside.'),
  (13, 'O-O-O', 'Castle long; the g/h pawns are free to storm.'),
  (14, 'b5', 'Black races on the queenside in return.'),
  (15, 'e5', 'Clamp the f6 knight out of the defense.'),
  (16, 'Ne8', 'Retreat, planning ...f6 or ...c5 breaks.'),
  (17, 'h4', 'Launch the pawn storm at the black king.'),
  (18, 'h5', 'Slow White down by fixing the h-pawn.'),
  (19, 'g4', 'Break through anyway — files must open for the attack.'),
  (20, 'hxg4', 'Capture; both sides sprint for the opposing king.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'caro-kann-fantasy' and ol.rank = 3;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'caro-kann-fantasy'), 'Provocative: 3...Nf6 4.e5', 4);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'Take the center.'),
  (2, 'c6', 'The Caro-Kann.'),
  (3, 'd4', 'Build the center.'),
  (4, 'd5', 'Challenge e4.'),
  (5, 'f3', 'The Fantasy setup.'),
  (6, 'Nf6', 'Develop, daring White to push.'),
  (7, 'e5', 'Accept the dare: gain space with tempo.'),
  (8, 'Nfd7', 'The knight steps back to hit e5 with ...c5 and ...f6.'),
  (9, 'f4', 'Reinforce e5 — the f3 pawn becomes an asset.'),
  (10, 'e6', 'Open the f8 bishop; the position is now a good French for White.'),
  (11, 'Nf3', 'Develop and cover d4.'),
  (12, 'c5', 'The standard strike at the pawn chain''s base.'),
  (13, 'c3', 'Hold d4 with the pawn chain.'),
  (14, 'Nc6', 'Pile on d4.'),
  (15, 'Bd3', 'The attacking diagonal toward h7.'),
  (16, 'cxd4', 'Trade to open the c-file.'),
  (17, 'cxd4', 'Recapture, keeping the chain d4-e5-f4 intact.'),
  (18, 'Qb6', 'Hit d4 and b2 — Black''s standard counterplay.'),
  (19, 'Nc3', 'Develop and simply ignore b2; d4 stays defended tactically.'),
  (20, 'Be7', 'Develop; a classic French-structure battle is ahead.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'caro-kann-fantasy' and ol.rank = 4;

-- French: Two Knights Variation (C00)
insert into public.openings (slug, name, eco, playable_colors, detection_keys) values ('french-two-knights', 'French: Two Knights Variation', 'C00', '{white,black}', '{"french defense two knights","french defense: two knights"}');
insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'french-two-knights'), 'Main Line: 3...Nf6 4.e5', 1);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'Take the center.'),
  (2, 'e6', 'The French Defense: prepare ...d5 behind a solid wall.'),
  (3, 'Nc3', 'Develop and defend e4 without committing the d-pawn yet.'),
  (4, 'd5', 'Challenge e4 as planned.'),
  (5, 'Nf3', 'The Two Knights: flexible development over early pawn commitments.'),
  (6, 'Nf6', 'Develop and add pressure on e4.'),
  (7, 'e5', 'Gain space with tempo on the knight.'),
  (8, 'Nfd7', 'The standard retreat, eyeing ...c5 and ...f6 breaks.'),
  (9, 'd4', 'Now build the classic French big center.'),
  (10, 'c5', 'Strike at the base of the chain immediately.'),
  (11, 'dxc5', 'Trade before ...Nc6 piles up on d4 — a key Two Knights idea.'),
  (12, 'Nc6', 'Develop and prepare to regain the c5 pawn.'),
  (13, 'Bf4', 'Develop actively; e5 gets rock-solid support.'),
  (14, 'Bxc5', 'Recover the pawn with a good diagonal.'),
  (15, 'Bd3', 'Point the bishop at h7 and prepare O-O.'),
  (16, 'f6', 'Challenge the e5 wedge — Black''s main plan.'),
  (17, 'exf6', 'Trade before ...fxe5 undermines everything.'),
  (18, 'Nxf6', 'Recapture toward the center; e6 stays backward.'),
  (19, 'O-O', 'Castle; White will target the weak e6 pawn.'),
  (20, 'O-O', 'Black castles into a playable but slightly worse middlegame.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'french-two-knights' and ol.rank = 1;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'french-two-knights'), 'Advance: 3...d4', 2);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'Take the center.'),
  (2, 'e6', 'The French Defense.'),
  (3, 'Nc3', 'Develop and cover e4.'),
  (4, 'd5', 'Challenge e4.'),
  (5, 'Nf3', 'The Two Knights setup.'),
  (6, 'd4', 'Push, gaining space and kicking the knight.'),
  (7, 'Ne2', 'Reroute — the knight heads for g3 or f4.'),
  (8, 'c5', 'Support d4 and grab queenside space.'),
  (9, 'c3', 'Undermine the advanced pawn immediately.'),
  (10, 'Nc6', 'Develop and hold d4.'),
  (11, 'cxd4', 'Open lines while Black''s development lags.'),
  (12, 'cxd4', 'Recapture, keeping the strong pawn.'),
  (13, 'Ng3', 'The knight finds a fine post, eyeing f5 and h5.'),
  (14, 'e5', 'Black builds an imposing pawn pair — but it can become a target.'),
  (15, 'Bc4', 'Develop with pressure on f7 before Black consolidates.'),
  (16, 'Nf6', 'Develop and cover d5/h5.'),
  (17, 'd3', 'Solidify the bishop and open the c1 diagonal.'),
  (18, 'Bd6', 'Develop, protecting e5.'),
  (19, 'O-O', 'Castle; White will attack the overextended center with f4.'),
  (20, 'O-O', 'Black castles; the center tension defines the game.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'french-two-knights' and ol.rank = 2;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'french-two-knights'), 'Pseudo-Winawer: 3...Bb4', 3);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'Take the center.'),
  (2, 'e6', 'The French Defense.'),
  (3, 'Nc3', 'Develop and cover e4.'),
  (4, 'd5', 'Challenge e4.'),
  (5, 'Nf3', 'The Two Knights setup.'),
  (6, 'Bb4', 'A Winawer-style pin on the c3 knight.'),
  (7, 'e5', 'Grab space — the pin no longer pressures e4.'),
  (8, 'c5', 'Hit the chain''s base, standard French play.'),
  (9, 'a3', 'Put the question to the bishop at once.'),
  (10, 'Bxc3', 'Concede the bishop pair to double White''s pawns.'),
  (11, 'dxc3', 'Recapture toward the center: open d-file, dark-square grip.'),
  (12, 'Ne7', 'Develop around the e5 wedge.'),
  (13, 'Bd3', 'Aim at h7 and prepare O-O.'),
  (14, 'Nbc6', 'Finish minor-piece development.'),
  (15, 'O-O', 'King to safety; dark squares belong to White.'),
  (16, 'Qc7', 'Pressure e5 and c-file squares.'),
  (17, 'Re1', 'Reinforce e5 — the space-giving wedge must stand.'),
  (18, 'Bd7', 'Connect the queenside, planning ...O-O-O or ...f6.'),
  (19, 'Bf4', 'Overprotect e5 and dominate the dark squares.'),
  (20, 'O-O-O', 'Black castles long; opposite-side plans emerge.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'french-two-knights' and ol.rank = 3;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'french-two-knights'), 'Exchange: 3...dxe4', 4);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'Take the center.'),
  (2, 'e6', 'The French Defense.'),
  (3, 'Nc3', 'Develop and cover e4.'),
  (4, 'd5', 'Challenge e4.'),
  (5, 'Nf3', 'The Two Knights setup.'),
  (6, 'dxe4', 'Release the tension — solid but slightly passive.'),
  (7, 'Nxe4', 'Recapture with a strong centralized knight.'),
  (8, 'Nd7', 'Prepare ...Ngf6 without allowing doubled pawns.'),
  (9, 'd4', 'Take the full center for free.'),
  (10, 'Ngf6', 'Challenge the e4 knight.'),
  (11, 'Nxf6+', 'Trade on your terms, pulling the knight forward.'),
  (12, 'Nxf6', 'Recapture; Black stays solid but cramped.'),
  (13, 'Bd3', 'Best diagonal, aiming at h7.'),
  (14, 'Be7', 'Modest development; ...c5 is the eventual break.'),
  (15, 'O-O', 'Castle first.'),
  (16, 'O-O', 'Black follows.'),
  (17, 'Bg5', 'Pin the last defender of h7''s key knight.'),
  (18, 'b6', 'Prepare ...Bb7 to fight for the long diagonal.'),
  (19, 'Qe2', 'Connect rooks and prepare Rad1 — a pleasant risk-free edge.'),
  (20, 'Bb7', 'Complete development; White holds more space.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'french-two-knights' and ol.rank = 4;

-- Italian Game (C50)
insert into public.openings (slug, name, eco, playable_colors, detection_keys) values ('italian-game', 'Italian Game', 'C50', '{white,black}', '{"italian game","giuoco piano","two knights defense"}');
insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'italian-game'), 'Giuoco Pianissimo: c3-d3 Main Line', 1);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'Take the center.'),
  (2, 'e5', 'Symmetrical reply.'),
  (3, 'Nf3', 'Attack e5 and develop.'),
  (4, 'Nc6', 'Defend e5.'),
  (5, 'Bc4', 'The Italian: eye f7 and prepare O-O.'),
  (6, 'Bc5', 'Mirror development on the strong diagonal.'),
  (7, 'c3', 'Prepare d4 and give the bishop the c2 retreat.'),
  (8, 'Nf6', 'Develop with pressure on e4.'),
  (9, 'd3', 'The modern slow treatment: keep the center flexible.'),
  (10, 'd6', 'Black matches the slow structure.'),
  (11, 'O-O', 'King safety.'),
  (12, 'O-O', 'Black castles too.'),
  (13, 'Re1', 'Support e4 and prepare d4 later.'),
  (14, 'a6', 'Give the c5 bishop a retreat and gain space.'),
  (15, 'Bb3', 'Sidestep in advance; the bishop stays on the key diagonal.'),
  (16, 'Ba7', 'Same idea — the bishop keeps eyeing f2 from safety.'),
  (17, 'h3', 'Stop ...Bg4 and ...Ng4 before regrouping.'),
  (18, 'h6', 'Black mirrors, stopping Bg5 and Ng5.'),
  (19, 'Nbd2', 'The famous maneuver begins: Nd2-f1-g3 toward f5.'),
  (20, 'Re8', 'Black centralizes a rook awaiting the middlegame.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'italian-game' and ol.rank = 1;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'italian-game'), 'Two Knights: 4.Ng5 Main Line', 2);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'Take the center.'),
  (2, 'e5', 'Symmetrical reply.'),
  (3, 'Nf3', 'Attack e5 and develop.'),
  (4, 'Nc6', 'Defend e5.'),
  (5, 'Bc4', 'The Italian bishop.'),
  (6, 'Nf6', 'The Two Knights: counterattack e4 instead of defending.'),
  (7, 'Ng5', 'The critical test: attack f7 twice at once.'),
  (8, 'd5', 'The only good defense: block the diagonal.'),
  (9, 'exd5', 'Take, keeping the threats alive.'),
  (10, 'Na5', 'The main line: hit the c4 bishop instead of recapturing.'),
  (11, 'Bb5+', 'Keep the extra pawn with tempo.'),
  (12, 'c6', 'Block and attack the bishop, offering a pawn for activity.'),
  (13, 'dxc6', 'Take again; White is up two pawns temporarily.'),
  (14, 'bxc6', 'Recapture and hit b5 — Black gets a huge initiative.'),
  (15, 'Be2', 'The safest retreat, covering the f3 square.'),
  (16, 'h6', 'Kick the knight back with tempo.'),
  (17, 'Nf3', 'Retreat; White holds a pawn but must weather the storm.'),
  (18, 'e4', 'The pawn kicks again — Black plays for full compensation.'),
  (19, 'Ne5', 'The best square: centralized and hitting c6.'),
  (20, 'Bd6', 'Develop with tempo against the e5 knight.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'italian-game' and ol.rank = 2;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'italian-game'), 'Evans Gambit', 3);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'Take the center.'),
  (2, 'e5', 'Symmetrical reply.'),
  (3, 'Nf3', 'Attack e5 and develop.'),
  (4, 'Nc6', 'Defend e5.'),
  (5, 'Bc4', 'The Italian bishop.'),
  (6, 'Bc5', 'The Giuoco Piano move.'),
  (7, 'b4', 'The Evans Gambit: a pawn for time and a monster center.'),
  (8, 'Bxb4', 'Accepting is critical — declining concedes space for free.'),
  (9, 'c3', 'Gain another tempo on the bishop while preparing d4.'),
  (10, 'Ba5', 'The main retreat, keeping the pin option on c3.'),
  (11, 'd4', 'The point: a full center arrives with threats.'),
  (12, 'exd4', 'Black must trade before being squeezed.'),
  (13, 'O-O', 'Sacrifice a second pawn for a huge lead in development.'),
  (14, 'Nge7', 'Modern defense: rush the king toward safety.'),
  (15, 'cxd4', 'Restore one pawn and own the center.'),
  (16, 'd5', 'Strike back before White''s center rolls.'),
  (17, 'exd5', 'Open lines — exactly what the gambiteer wants.'),
  (18, 'Nxd5', 'Recapture toward the center.'),
  (19, 'Ba3', 'The dark-square bishop denies Black castling rights.'),
  (20, 'Be6', 'Develop and shore up the d5 knight.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'italian-game' and ol.rank = 3;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'italian-game'), 'Two Knights: Fried Liver Attack', 4);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'Take the center.'),
  (2, 'e5', 'Symmetrical reply.'),
  (3, 'Nf3', 'Attack e5 and develop.'),
  (4, 'Nc6', 'Defend e5.'),
  (5, 'Bc4', 'The Italian bishop.'),
  (6, 'Nf6', 'The Two Knights Defense.'),
  (7, 'Ng5', 'Attack f7 twice.'),
  (8, 'd5', 'The necessary block.'),
  (9, 'exd5', 'Capture and keep the pressure.'),
  (10, 'Nxd5', 'The risky recapture that allows the famous sacrifice.'),
  (11, 'Nxf7', 'The Fried Liver: rip open the king''s cover.'),
  (12, 'Kxf7', 'Forced — declining just loses a pawn for nothing.'),
  (13, 'Qf3+', 'Fork the king and the loose d5 knight.'),
  (14, 'Ke6', 'The only way to hold the knight — the king marches out.'),
  (15, 'Nc3', 'Pile on d5 with every developing move.'),
  (16, 'Nb4', 'Reinforce d5 while threatening ...Nxc2 forks.'),
  (17, 'Qe4', 'Centralize: keep hitting d5 and cut the king''s escape.'),
  (18, 'c6', 'Finally shore up d5 with the pawn.'),
  (19, 'a3', 'Push the b4 knight away from its defense.'),
  (20, 'Na6', 'The knight retreats; White regains material with a raging attack.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'italian-game' and ol.rank = 4;

-- Ruy Lopez (C60)
insert into public.openings (slug, name, eco, playable_colors, detection_keys) values ('ruy-lopez', 'Ruy Lopez', 'C60', '{white,black}', '{"ruy lopez","spanish game"}');
insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'ruy-lopez'), 'Closed Main Line (Chigorin)', 1);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'Take the center.'),
  (2, 'e5', 'Symmetrical reply.'),
  (3, 'Nf3', 'Attack e5 and develop.'),
  (4, 'Nc6', 'Defend e5.'),
  (5, 'Bb5', 'The Ruy Lopez: pressure the defender of e5.'),
  (6, 'a6', 'The Morphy Defense: put the question to the bishop.'),
  (7, 'Ba4', 'Keep the pin option alive.'),
  (8, 'Nf6', 'Develop and counterattack e4.'),
  (9, 'O-O', 'Castle — e4 is tactically defended (Nxe4 runs into Re1 ideas).'),
  (10, 'Be7', 'The Closed Ruy: solid development first.'),
  (11, 'Re1', 'Now really defend e4 and take the e-file.'),
  (12, 'b5', 'Break the latent pin before ...d6.'),
  (13, 'Bb3', 'The bishop keeps its strong diagonal toward f7.'),
  (14, 'd6', 'Solidify e5 and open the c8 bishop.'),
  (15, 'c3', 'Prepare d4 and create the classic Spanish retreat c2.'),
  (16, 'O-O', 'Black completes king safety.'),
  (17, 'h3', 'Prevent the annoying pin ...Bg4 before playing d4.'),
  (18, 'Na5', 'The Chigorin plan: harass the b3 bishop and stake c4.'),
  (19, 'Bc2', 'Preserve the bishop on its ideal diagonal.'),
  (20, 'c5', 'Grab queenside space — the main tabiya of the Closed Ruy.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'ruy-lopez' and ol.rank = 1;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'ruy-lopez'), 'Berlin Defense', 2);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'Take the center.'),
  (2, 'e5', 'Symmetrical reply.'),
  (3, 'Nf3', 'Attack e5 and develop.'),
  (4, 'Nc6', 'Defend e5.'),
  (5, 'Bb5', 'The Ruy Lopez.'),
  (6, 'Nf6', 'The Berlin: immediate counterplay against e4.'),
  (7, 'O-O', 'The main line: let Black take and trust the initiative.'),
  (8, 'Nxe4', 'Take the pawn — the Berlin''s point.'),
  (9, 'd4', 'Open the center against the loose knight.'),
  (10, 'Nd6', 'Attack the b5 bishop while retreating.'),
  (11, 'Bxc6', 'Trade before recapturing on e5.'),
  (12, 'dxc6', 'Keep structure; ...bxc6 would leave weaker pawns.'),
  (13, 'dxe5', 'Win the pawn back with tempo on the d6 knight.'),
  (14, 'Nf5', 'The knight finds its best square.'),
  (15, 'Qxd8+', 'Enter the famous Berlin endgame.'),
  (16, 'Kxd8', 'Forced — Black loses castling but has the bishop pair.'),
  (17, 'Nc3', 'Develop with tempo toward d5.'),
  (18, 'Ke8', 'Tuck the king away; Black''s setup is resilient.'),
  (19, 'h3', 'Take g4 from the knight and bishop — a key endgame move.'),
  (20, 'h5', 'Fix White''s kingside and give the f5 knight a route via h4-g6.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'ruy-lopez' and ol.rank = 2;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'ruy-lopez'), 'Exchange Variation', 3);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'Take the center.'),
  (2, 'e5', 'Symmetrical reply.'),
  (3, 'Nf3', 'Attack e5 and develop.'),
  (4, 'Nc6', 'Defend e5.'),
  (5, 'Bb5', 'The Ruy Lopez.'),
  (6, 'a6', 'The Morphy Defense.'),
  (7, 'Bxc6', 'The Exchange: inflict doubled pawns for a superior endgame.'),
  (8, 'dxc6', 'Open the c8 bishop — the standard recapture.'),
  (9, 'O-O', 'Castle and prepare d4; 5.Nxe5 would lose to ...Qd4.'),
  (10, 'f6', 'Solidify e5 the sturdy way.'),
  (11, 'd4', 'Strike while ahead in structure.'),
  (12, 'exd4', 'Trade — holding e5 forever is impossible.'),
  (13, 'Nxd4', 'Recapture with a strong central knight.'),
  (14, 'c5', 'Kick the knight and free the doubled pawn.'),
  (15, 'Nb3', 'Retreat, keeping the queenside pawns fixed as targets.'),
  (16, 'Qxd1', 'Trade into the endgame White wants — but Black is solid too.'),
  (17, 'Rxd1', 'White''s 4-v-3 kingside majority is the long-term trump.'),
  (18, 'Bg4', 'Activate with tempo on the rook via the pin square.'),
  (19, 'f3', 'Blunt the bishop and take control of e4.'),
  (20, 'Be6', 'Reroute to the strong blockading square.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'ruy-lopez' and ol.rank = 3;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'ruy-lopez'), 'Steinitz Deferred: ...d6 Setup', 4);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'Take the center.'),
  (2, 'e5', 'Symmetrical reply.'),
  (3, 'Nf3', 'Attack e5 and develop.'),
  (4, 'Nc6', 'Defend e5.'),
  (5, 'Bb5', 'The Ruy Lopez.'),
  (6, 'a6', 'The Morphy Defense.'),
  (7, 'Ba4', 'Keep the tension.'),
  (8, 'd6', 'The Steinitz Deferred: a solid e5 fortress.'),
  (9, 'c3', 'Prepare d4 and preserve the bishop.'),
  (10, 'Nf6', 'Develop normally.'),
  (11, 'd4', 'Build the strong center.'),
  (12, 'Bd7', 'Unpin c6 and connect the pieces.'),
  (13, 'O-O', 'King safety.'),
  (14, 'Be7', 'Prepare to castle.'),
  (15, 'Re1', 'Overprotect e4 — the thematic Spanish rook.'),
  (16, 'O-O', 'Black castles.'),
  (17, 'Nbd2', 'Start the classic Spanish knight tour toward g3/f5.'),
  (18, 'Re8', 'Contest the e-file.'),
  (19, 'Nf1', 'Continue the maneuver — slow but venomous.'),
  (20, 'Bf8', 'Black regroups likewise; a rich maneuvering game begins.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'ruy-lopez' and ol.rank = 4;

-- Vienna Game (C25)
insert into public.openings (slug, name, eco, playable_colors, detection_keys) values ('vienna-game', 'Vienna Game', 'C25', '{white}', '{"vienna game","vienna gambit"}');
insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'vienna-game'), 'Vienna Gambit: 3...d5 Main Line', 1);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'Take the center.'),
  (2, 'e5', 'Symmetrical reply.'),
  (3, 'Nc3', 'The Vienna: defend e4 first, keep f4 available.'),
  (4, 'Nf6', 'Develop and hit e4.'),
  (5, 'f4', 'The Vienna Gambit: fight for the center like a King''s Gambit.'),
  (6, 'd5', 'The correct counter — striking back in the center.'),
  (7, 'fxe5', 'Take, gaining a tempo on the f6 knight.'),
  (8, 'Nxe4', 'The point of ...d5: the knight lands actively.'),
  (9, 'Nf3', 'Develop and cover the sensitive h4 checks.'),
  (10, 'Be7', 'Calm development, preparing ...O-O.'),
  (11, 'd4', 'Claim the center and open the c1 bishop.'),
  (12, 'O-O', 'Black castles first.'),
  (13, 'Bd3', 'Challenge the e4 knight directly.'),
  (14, 'Nxc3', 'Trade before the knight is pushed away.'),
  (15, 'bxc3', 'Recapture toward the center — big pawn presence.'),
  (16, 'c5', 'Chip at the pawn center immediately.'),
  (17, 'O-O', 'King safety; the half-open f-file is White''s prize.'),
  (18, 'Nc6', 'Develop and pressure d4.'),
  (19, 'Be3', 'Hold d4; White''s center and f-file promise attacking chances.'),
  (20, 'cxd4', 'Trade to relieve the pressure.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'vienna-game' and ol.rank = 1;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'vienna-game'), 'Max Lange Setup: 2...Nc6 3.Bc4', 2);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'Take the center.'),
  (2, 'e5', 'Symmetrical reply.'),
  (3, 'Nc3', 'The Vienna.'),
  (4, 'Nc6', 'Natural development.'),
  (5, 'Bc4', 'Target f7 while delaying the knight to f3.'),
  (6, 'Nf6', 'Develop and eye e4.'),
  (7, 'd3', 'Solidify e4; the f4 push is coming.'),
  (8, 'Bc5', 'Active development.'),
  (9, 'f4', 'The thematic Vienna advance — a delayed King''s Gambit.'),
  (10, 'd6', 'Hold e5 and open the c8 bishop.'),
  (11, 'Nf3', 'Develop and keep the f-file tension.'),
  (12, 'O-O', 'Black castles into the coming storm.'),
  (13, 'f5', 'Clamp the kingside — the attack plays itself: g4-g5 next.'),
  (14, 'Na5', 'Black seeks the strong c4 bishop.'),
  (15, 'Bb3', 'Preserve it — this bishop is the attack''s backbone.'),
  (16, 'Nxb3', 'Trade anyway to blunt the diagonal.'),
  (17, 'axb3', 'Recapture; the open a-file is a small bonus.'),
  (18, 'c6', 'Prepare ...b5 and give the queen c7.'),
  (19, 'g4', 'Launch the pawn storm against the castled king.'),
  (20, 'b5', 'Black races on the other wing — sharp opposite-flank play.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'vienna-game' and ol.rank = 2;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'vienna-game'), 'Positional Vienna: 3.g3', 3);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'Take the center.'),
  (2, 'e5', 'Symmetrical reply.'),
  (3, 'Nc3', 'The Vienna.'),
  (4, 'Nf6', 'Develop and hit e4.'),
  (5, 'g3', 'The positional treatment: fianchetto against d5.'),
  (6, 'd5', 'The principled break anyway.'),
  (7, 'exd5', 'Trade — the g2 bishop will bear on the long diagonal.'),
  (8, 'Nxd5', 'Recapture with a centralized knight.'),
  (9, 'Bg2', 'The fianchetto hits d5 and b7.'),
  (10, 'Nxc3', 'Trade before losing time to the pressure.'),
  (11, 'bxc3', 'Recapture toward the center; the pawn duo controls d4.'),
  (12, 'Nc6', 'Develop.'),
  (13, 'Nf3', 'Develop and restrain ...e4.'),
  (14, 'Bd6', 'Point at the kingside, holding e5.'),
  (15, 'O-O', 'Castle behind the fianchetto wall.'),
  (16, 'O-O', 'Black castles.'),
  (17, 'd3', 'Complete the structure; c1''s bishop gets options.'),
  (18, 'Re8', 'Support e5 down the half-open file.'),
  (19, 'Rb1', 'The other point of bxc3 — pressure on b7 forever.'),
  (20, 'Rb8', 'Black defends passively; White keeps a pleasant grind.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'vienna-game' and ol.rank = 3;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'vienna-game'), '2...Bc5 3.Nf3 d6', 4);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'Take the center.'),
  (2, 'e5', 'Symmetrical reply.'),
  (3, 'Nc3', 'The Vienna.'),
  (4, 'Bc5', 'Quick development, delaying ...Nf6.'),
  (5, 'Nf3', 'Attack e5 — Black must react.'),
  (6, 'd6', 'Hold e5 solidly.'),
  (7, 'd4', 'Open the center while better developed.'),
  (8, 'exd4', 'Forced trade to avoid losing e5.'),
  (9, 'Nxd4', 'Recapture with a dominant knight.'),
  (10, 'Nf6', 'Develop and pressure e4.'),
  (11, 'Bg5', 'Pin the knight — awkward for Black already.'),
  (12, 'h6', 'Put the question to the bishop.'),
  (13, 'Bh4', 'Maintain the pin; ...g5 would wreck Black''s king.'),
  (14, 'Nc6', 'Challenge the strong d4 knight.'),
  (15, 'Nxc6', 'Trade and damage Black''s queenside structure.'),
  (16, 'bxc6', 'Recapture, accepting the split pawns.'),
  (17, 'Bc4', 'Classic diagonal, hitting f7.'),
  (18, 'O-O', 'Black castles.'),
  (19, 'Qd3', 'Connect and aim pieces at the kingside.'),
  (20, 'Re8', 'Activate the rook; White retains the better structure.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'vienna-game' and ol.rank = 4;

-- London System (D02)
insert into public.openings (slug, name, eco, playable_colors, detection_keys) values ('london-system', 'London System', 'D02', '{white}', '{"london system"}');
insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'london-system'), 'Main Line vs ...c5/...e6', 1);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'd4', 'Take the center the queen''s-pawn way.'),
  (2, 'd5', 'Symmetrical reply.'),
  (3, 'Bf4', 'The modern London move order: bishop out before Nf3.'),
  (4, 'Nf6', 'Natural development.'),
  (5, 'e3', 'Build the pyramid; the bishop is already outside it.'),
  (6, 'c5', 'The main strike at d4.'),
  (7, 'c3', 'Reinforce d4 — the London wall takes shape.'),
  (8, 'Nc6', 'Develop and add pressure.'),
  (9, 'Nd2', 'Flexible: support e4 ideas and keep f3 for the other knight.'),
  (10, 'e6', 'Open the f8 bishop.'),
  (11, 'Ngf3', 'Complete the classic London setup.'),
  (12, 'Bd6', 'Challenge the strong f4 bishop.'),
  (13, 'Bg3', 'Keep the bishop — trades ease Black''s game.'),
  (14, 'O-O', 'Black castles.'),
  (15, 'Bd3', 'The attacking diagonal toward h7.'),
  (16, 'b6', 'Prepare ...Bb7 and queenside play.'),
  (17, 'Ne5', 'The thematic knight leap — the London''s main attacking idea.'),
  (18, 'Bb7', 'Complete development.'),
  (19, 'f4', 'Cement the knight; the f1 rook joins after O-O.'),
  (20, 'Ne7', 'Reroute to f5 to fight the coming attack.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'london-system' and ol.rank = 1;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'london-system'), 'Poisoned Pawn: ...Qb6', 2);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'd4', 'Take the center.'),
  (2, 'd5', 'Symmetrical reply.'),
  (3, 'Bf4', 'The London bishop.'),
  (4, 'Nf6', 'Natural development.'),
  (5, 'e3', 'Build the pyramid.'),
  (6, 'c5', 'Strike at d4.'),
  (7, 'c3', 'Reinforce d4.'),
  (8, 'Qb6', 'Target b2 — the bishop''s departure left it tender.'),
  (9, 'Qb3', 'The standard answer: offer the trade and hold b2.'),
  (10, 'Qxb3', 'Trade — grabbing b2 instead is famously risky.'),
  (11, 'axb3', 'Recapture opening the a-file; the doubled pawns control key squares.'),
  (12, 'cxd4', 'Release the tension.'),
  (13, 'exd4', 'Recapture, keeping the sturdy center.'),
  (14, 'Nc6', 'Develop with pressure on d4.'),
  (15, 'Nf3', 'Defend d4 and develop.'),
  (16, 'Bf5', 'Active development before ...e6.'),
  (17, 'Nbd2', 'Complete development, eyeing c4/e5.'),
  (18, 'e6', 'Solidify.'),
  (19, 'Bb5', 'Pin and pressure — White''s endgame edge is tiny but real.'),
  (20, 'Bd6', 'Offer the trade of dark-squared bishops.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'london-system' and ol.rank = 2;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'london-system'), 'vs Fianchetto: ...g6', 3);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'd4', 'Take the center.'),
  (2, 'd5', 'Symmetrical reply.'),
  (3, 'Bf4', 'The London bishop.'),
  (4, 'Nf6', 'Natural development.'),
  (5, 'e3', 'Build the pyramid.'),
  (6, 'g6', 'Black opts for a Grünfeld-like fianchetto.'),
  (7, 'Nf3', 'Develop; the setup barely changes.'),
  (8, 'Bg7', 'Complete the fianchetto.'),
  (9, 'Be2', 'Modest: against ...g6 the bishop bites on granite at d3.'),
  (10, 'O-O', 'Black castles.'),
  (11, 'h3', 'Give the f4 bishop an h2 retreat from ...Nh5.'),
  (12, 'c5', 'The standard break.'),
  (13, 'c3', 'Hold d4 as always.'),
  (14, 'Nc6', 'Develop.'),
  (15, 'O-O', 'King safety.'),
  (16, 'b6', 'Prepare ...Bb7 and a queenside squeeze.'),
  (17, 'Nbd2', 'Finish development, ready for Ne5 or a4.'),
  (18, 'Bb7', 'Complete the setup.'),
  (19, 'a4', 'Gain space and probe the queenside dark squares.'),
  (20, 'a6', 'Restrain a4-a5; a long maneuvering battle begins.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'london-system' and ol.rank = 3;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'london-system'), 'Mirror: ...Bf5', 4);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'd4', 'Take the center.'),
  (2, 'd5', 'Symmetrical reply.'),
  (3, 'Bf4', 'The London bishop.'),
  (4, 'Nf6', 'Natural development.'),
  (5, 'e3', 'Build the pyramid.'),
  (6, 'Bf5', 'Black copies the London setup.'),
  (7, 'Nf3', 'Develop normally.'),
  (8, 'e6', 'Solid structure.'),
  (9, 'Bd3', 'Offer the trade — White gains time either way.'),
  (10, 'Bxd3', 'Trade; declining loses a tempo to the offer.'),
  (11, 'Qxd3', 'Recapture with a well-placed queen.'),
  (12, 'c6', 'Solidify d5, Slav-style.'),
  (13, 'Nbd2', 'Develop toward e5/c4.'),
  (14, 'Nbd7', 'Black completes the mirror.'),
  (15, 'O-O', 'King safety.'),
  (16, 'Be7', 'Prepare to castle.'),
  (17, 'c4', 'Break first — the tempo advantage means White opens on his terms.'),
  (18, 'O-O', 'Black castles.'),
  (19, 'Rac1', 'Take the file that is about to open.'),
  (20, 'Re8', 'Black waits; White presses with a riskless initiative.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'london-system' and ol.rank = 4;

-- Queen's Gambit (D06)
insert into public.openings (slug, name, eco, playable_colors, detection_keys) values ('queens-gambit', 'Queen''s Gambit', 'D06', '{white,black}', '{"queens gambit","queen''s gambit","slav defense"}');
insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'queens-gambit'), 'QGD: Classical Bg5 Main Line', 1);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'd4', 'Take the center.'),
  (2, 'd5', 'Symmetrical reply.'),
  (3, 'c4', 'The Queen''s Gambit: bid to deflect the d5 pawn.'),
  (4, 'e6', 'The Declined: hold d5 at the cost of the c8 bishop.'),
  (5, 'Nc3', 'Develop and add pressure on d5.'),
  (6, 'Nf6', 'Defend d5 and develop.'),
  (7, 'Bg5', 'The classical pin, indirectly fighting for d5.'),
  (8, 'Be7', 'Break the pin calmly.'),
  (9, 'e3', 'Solidify d4 and open the f1 bishop.'),
  (10, 'O-O', 'King safety.'),
  (11, 'Nf3', 'Complete kingside development.'),
  (12, 'h6', 'Put the question to the bishop — a useful luft too.'),
  (13, 'Bh4', 'Keep the pin at a distance.'),
  (14, 'b6', 'The Tartakower: fianchetto to solve the c8 bishop.'),
  (15, 'cxd5', 'Clarify the center before ...Bb7 lands.'),
  (16, 'Nxd5', 'Recapture actively, offering simplification.'),
  (17, 'Bxe7', 'Trade into the structure battle.'),
  (18, 'Qxe7', 'Recapture; Black is solid but slightly passive.'),
  (19, 'Nxd5', 'Trade again, pulling a pawn to d5.'),
  (20, 'exd5', 'Recapture; the symmetric structure slightly favors White''s bishop.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'queens-gambit' and ol.rank = 1;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'queens-gambit'), 'Queen''s Gambit Accepted', 2);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'd4', 'Take the center.'),
  (2, 'd5', 'Symmetrical reply.'),
  (3, 'c4', 'The Queen''s Gambit.'),
  (4, 'dxc4', 'Accept — Black gives the center for quick development.'),
  (5, 'Nf3', 'Stop ...e5 and develop; the pawn will come back.'),
  (6, 'Nf6', 'Natural development.'),
  (7, 'e3', 'Open the bishop to regain c4.'),
  (8, 'e6', 'Black returns the pawn for smooth development.'),
  (9, 'Bxc4', 'Regain the pawn with a good bishop.'),
  (10, 'c5', 'The equalizing strike at d4.'),
  (11, 'O-O', 'Castle before resolving the center.'),
  (12, 'a6', 'Prepare ...b5 with tempo.'),
  (13, 'Qe2', 'The main plan: prepare Rd1 and dxc5 ideas.'),
  (14, 'b5', 'Gain space with tempo on the bishop.'),
  (15, 'Bb3', 'Retreat, still eyeing e6/f7.'),
  (16, 'Bb7', 'The bishop takes the long diagonal.'),
  (17, 'Rd1', 'The rook opposes the black queen — central pressure.'),
  (18, 'Nbd7', 'Develop, holding c5 and e5.'),
  (19, 'Nc3', 'Complete development; the d4-d5 break is in the air.'),
  (20, 'Be7', 'Prepare to castle; a rich middlegame awaits.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'queens-gambit' and ol.rank = 2;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'queens-gambit'), 'Slav: Main Line 4...dxc4', 3);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'd4', 'Take the center.'),
  (2, 'd5', 'Symmetrical reply.'),
  (3, 'c4', 'The Queen''s Gambit.'),
  (4, 'c6', 'The Slav: hold d5 while keeping the c8 bishop free.'),
  (5, 'Nf3', 'Develop flexibly.'),
  (6, 'Nf6', 'Natural development.'),
  (7, 'Nc3', 'Pressure d5 again.'),
  (8, 'dxc4', 'Take now that ...b5 can defend the pawn.'),
  (9, 'a4', 'Stop ...b5 at the cost of the b4 square.'),
  (10, 'Bf5', 'The Slav''s point: the bishop develops actively first.'),
  (11, 'e3', 'Prepare to regain c4.'),
  (12, 'e6', 'Solidify and open the f8 bishop.'),
  (13, 'Bxc4', 'Regain the pawn.'),
  (14, 'Bb4', 'Pin, using the b4 hole a4 created.'),
  (15, 'O-O', 'Castle and offer the central battle.'),
  (16, 'Nbd7', 'Develop, supporting ...c5 or ...e5 breaks.'),
  (17, 'Qe2', 'Prepare the central e4 break.'),
  (18, 'Bg6', 'Tuck the bishop from e4-e5 tempo gains.'),
  (19, 'e4', 'The point of Qe2: the big center arrives.'),
  (20, 'O-O', 'Black castles; White has space, Black has no weaknesses.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'queens-gambit' and ol.rank = 3;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'queens-gambit'), 'QGD: Exchange Variation', 4);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'd4', 'Take the center.'),
  (2, 'd5', 'Symmetrical reply.'),
  (3, 'c4', 'The Queen''s Gambit.'),
  (4, 'e6', 'The Declined.'),
  (5, 'Nc3', 'Develop with pressure on d5.'),
  (6, 'Nf6', 'Defend and develop.'),
  (7, 'cxd5', 'The Exchange: fix the structure for the minority attack.'),
  (8, 'exd5', 'Recapture; the c8 bishop is free but d5 is static.'),
  (9, 'Bg5', 'Pin, the standard pressure piece.'),
  (10, 'c6', 'Solidify d5 — and create the b7/c6 target White wants.'),
  (11, 'e3', 'Solid center; the plan is b4-b5 on the queenside.'),
  (12, 'Be7', 'Unpin.'),
  (13, 'Bd3', 'The kingside diagonal — White can also attack there.'),
  (14, 'Nbd7', 'Standard development.'),
  (15, 'Qc2', 'Control e4 and support the b-pawn''s advance.'),
  (16, 'O-O', 'King safety.'),
  (17, 'Nge2', 'The Botvinnik setup: knights on c3/e2, f3 stays free for f2-f3.'),
  (18, 'Re8', 'Contest the e-file.'),
  (19, 'O-O', 'Castle; now b4-b5 or f3-e4 — two plans, one setup.'),
  (20, 'Nf8', 'The standard regrouping toward e6/g6.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'queens-gambit' and ol.rank = 4;

-- Sicilian Dragon (B70)
insert into public.openings (slug, name, eco, playable_colors, detection_keys) values ('sicilian-dragon', 'Sicilian Dragon', 'B70', '{black,white}', '{"sicilian defense dragon","sicilian defense: dragon","dragon variation"}');
insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'sicilian-dragon'), 'Yugoslav Attack: 9.Bc4 Main Line', 1);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'White takes the center.'),
  (2, 'c5', 'The Sicilian: fight for d4 asymmetrically.'),
  (3, 'Nf3', 'Prepare d4.'),
  (4, 'd6', 'Support ...Nf6 against e5 and keep options open.'),
  (5, 'd4', 'The Open Sicilian.'),
  (6, 'cxd4', 'Trade the wing pawn for a central one — the Sicilian''s point.'),
  (7, 'Nxd4', 'Recapture with a centralized knight.'),
  (8, 'Nf6', 'Develop and attack e4.'),
  (9, 'Nc3', 'Defend e4.'),
  (10, 'g6', 'The Dragon: the g7 bishop will breathe fire down the long diagonal.'),
  (11, 'Be3', 'The Yugoslav setup begins: Qd2 and O-O-O are coming.'),
  (12, 'Bg7', 'Complete the fianchetto.'),
  (13, 'f3', 'Blunt ...Ng4 and prepare the g4 pawn storm.'),
  (14, 'O-O', 'Castle — the race is on.'),
  (15, 'Qd2', 'Connect for O-O-O and aim at h6.'),
  (16, 'Nc6', 'Develop with pressure on d4.'),
  (17, 'Bc4', 'Stop ...d5 and eye f7 — the 9.Bc4 main line.'),
  (18, 'Bd7', 'Prepare ...Rc8 and the c-file counterattack.'),
  (19, 'O-O-O', 'Opposite-side castling: both sides attack at full speed.'),
  (20, 'Rc8', 'The rook takes the file where White''s king lives.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'sicilian-dragon' and ol.rank = 1;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'sicilian-dragon'), 'Classical: 6.Be2', 2);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'White takes the center.'),
  (2, 'c5', 'The Sicilian.'),
  (3, 'Nf3', 'Prepare d4.'),
  (4, 'd6', 'Flexible support.'),
  (5, 'd4', 'The Open Sicilian.'),
  (6, 'cxd4', 'Standard trade.'),
  (7, 'Nxd4', 'Recapture.'),
  (8, 'Nf6', 'Develop with tempo on e4.'),
  (9, 'Nc3', 'Defend e4.'),
  (10, 'g6', 'The Dragon setup.'),
  (11, 'Be2', 'The Classical: White castles short and plays positionally.'),
  (12, 'Bg7', 'Complete the fianchetto.'),
  (13, 'O-O', 'White castles.'),
  (14, 'Nc6', 'Develop and hit d4.'),
  (15, 'Nb3', 'Sidestep — avoid tricks on the c6/d4 diagonal.'),
  (16, 'O-O', 'Castle; with same-side kings the game is calmer.'),
  (17, 'Bg5', 'Pressure e7 and probe the dark squares.'),
  (18, 'Be6', 'Develop toward the queenside light squares.'),
  (19, 'Kh1', 'Tuck the king and prepare f4.'),
  (20, 'Rc8', 'Take the half-open file — Black''s play flows there.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'sicilian-dragon' and ol.rank = 2;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'sicilian-dragon'), 'Levenfish: 6.f4 Nc6!', 3);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'White takes the center.'),
  (2, 'c5', 'The Sicilian.'),
  (3, 'Nf3', 'Prepare d4.'),
  (4, 'd6', 'Flexible support.'),
  (5, 'd4', 'The Open Sicilian.'),
  (6, 'cxd4', 'Standard trade.'),
  (7, 'Nxd4', 'Recapture.'),
  (8, 'Nf6', 'Develop with tempo.'),
  (9, 'Nc3', 'Defend e4.'),
  (10, 'g6', 'The Dragon setup.'),
  (11, 'f4', 'The Levenfish: threatening e5 with a quick attack.'),
  (12, 'Nc6', 'The precise answer — 6...Bg7? runs into 7.e5! tricks.'),
  (13, 'Nxc6', 'Trade before the pressure on d4 mounts.'),
  (14, 'bxc6', 'Recapture toward the center, opening the b-file.'),
  (15, 'e5', 'White insists on the space-gaining push.'),
  (16, 'Nd7', 'Retreat calmly; e5 will become weak, not strong.'),
  (17, 'exd6', 'Release the tension before ...dxe5 favors Black.'),
  (18, 'exd6', 'Recapture; Black''s center pawns are fine and the bishops breathe.'),
  (19, 'Be2', 'Develop and prepare O-O.'),
  (20, 'Bg7', 'The Dragon bishop arrives — Black already stands well.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'sicilian-dragon' and ol.rank = 3;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'sicilian-dragon'), 'Yugoslav 9.O-O-O: ...d5!', 4);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'White takes the center.'),
  (2, 'c5', 'The Sicilian.'),
  (3, 'Nf3', 'Prepare d4.'),
  (4, 'd6', 'Flexible support.'),
  (5, 'd4', 'The Open Sicilian.'),
  (6, 'cxd4', 'Standard trade.'),
  (7, 'Nxd4', 'Recapture.'),
  (8, 'Nf6', 'Develop with tempo.'),
  (9, 'Nc3', 'Defend e4.'),
  (10, 'g6', 'The Dragon setup.'),
  (11, 'Be3', 'Yugoslav development.'),
  (12, 'Bg7', 'Complete the fianchetto.'),
  (13, 'f3', 'Support e4, prepare g4.'),
  (14, 'O-O', 'Castle.'),
  (15, 'Qd2', 'Prepare O-O-O.'),
  (16, 'Nc6', 'Develop with pressure on d4.'),
  (17, 'O-O-O', 'The 9.O-O-O line — skipping Bc4 has a drawback...'),
  (18, 'd5', '...this freeing break, the whole point: strike the center now!'),
  (19, 'exd5', 'Take — declining leaves White worse in the center.'),
  (20, 'Nxd5', 'Recapture; Black has full equality and active pieces.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'sicilian-dragon' and ol.rank = 4;

-- Modern Defense (B06)
insert into public.openings (slug, name, eco, playable_colors, detection_keys) values ('modern-defense', 'Modern Defense', 'B06', '{black}', '{"modern defense","robatsch"}');
insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'modern-defense'), 'Tiger''s Modern: ...a6', 1);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'White takes the center.'),
  (2, 'g6', 'The Modern: concede the center now, attack it later.'),
  (3, 'd4', 'White grabs the full center.'),
  (4, 'Bg7', 'The fianchetto — this bishop defines the opening.'),
  (5, 'Nc3', 'Natural development.'),
  (6, 'd6', 'Restrain e5 and open the c8 bishop.'),
  (7, 'Be3', 'White builds a Qd2/O-O-O attacking setup.'),
  (8, 'a6', 'Tiger''s Modern: prepare ...b5 and deny b5 to White''s pieces.'),
  (9, 'Nf3', 'Develop.'),
  (10, 'b5', 'Queenside space — Black plays on the flank, not the center.'),
  (11, 'Bd3', 'Complete development.'),
  (12, 'Bb7', 'The second fianchetto pressures e4.'),
  (13, 'O-O', 'White castles short after all.'),
  (14, 'Nd7', 'Flexible: support ...c5 or ...e5 breaks.'),
  (15, 'a4', 'White strikes at the pawn chain.'),
  (16, 'b4', 'Advance — closing lines toward Black''s own queenside.'),
  (17, 'Ne2', 'Reroute toward the kingside or d4 support.'),
  (18, 'c5', 'The thematic break arrives at the right moment.'),
  (19, 'c3', 'White fights for the dark squares.'),
  (20, 'bxc3', 'Trade, opening the b-file for the rook.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'modern-defense' and ol.rank = 1;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'modern-defense'), 'Austrian Attack: 4.f4', 2);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'White takes the center.'),
  (2, 'g6', 'The Modern.'),
  (3, 'd4', 'Full center.'),
  (4, 'Bg7', 'The fianchetto.'),
  (5, 'Nc3', 'Development.'),
  (6, 'd6', 'Restrain e5.'),
  (7, 'f4', 'The Austrian Attack: maximum central ambition.'),
  (8, 'a6', 'Stay flexible; the counterattack comes with ...b5.'),
  (9, 'Nf3', 'Develop behind the pawn wall.'),
  (10, 'b5', 'Gain space and threaten ...b4.'),
  (11, 'Bd3', 'Develop and defend e4.'),
  (12, 'Nd7', 'Develop, holding the e5/c5 breaks in reserve.'),
  (13, 'e5', 'White pushes — the wall advances.'),
  (14, 'dxe5', 'Trade at the right moment to loosen the wall.'),
  (15, 'fxe5', 'White keeps the spearhead.'),
  (16, 'c5', 'Now undermine d4 while it lacks pawn support.'),
  (17, 'dxc5', 'White grabs, but the center dissolves.'),
  (18, 'Nxc5', 'Recapture with tempo on the d3 bishop.'),
  (19, 'O-O', 'White castles at last.'),
  (20, 'Nxd3', 'Win the bishop pair — Black''s strategy has paid off.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'modern-defense' and ol.rank = 2;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'modern-defense'), '3.c4: King''s Indian Style', 3);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'White takes the center.'),
  (2, 'g6', 'The Modern.'),
  (3, 'd4', 'Full center.'),
  (4, 'Bg7', 'The fianchetto.'),
  (5, 'c4', 'White grabs even more space — a KID structure beckons.'),
  (6, 'd6', 'Standard restraint.'),
  (7, 'Nc3', 'Development.'),
  (8, 'e5', 'Stake the central claim immediately.'),
  (9, 'd5', 'White closes the center — now it''s a pure KID battle.'),
  (10, 'Ne7', 'Develop toward f5 without blocking the f-pawn... via e7.'),
  (11, 'Bd3', 'Develop, watching the f5 square.'),
  (12, 'O-O', 'King safety before the pawn storms.'),
  (13, 'Nge2', 'White completes development flexibly.'),
  (14, 'f5', 'The thematic KID break — Black''s whole game is here.'),
  (15, 'exf5', 'White trades to keep e4 for the pieces.'),
  (16, 'gxf5', 'Recapture toward the center, opening the g-file too.'),
  (17, 'f4', 'White blocks the pawn mass.'),
  (18, 'e4', 'Push through with tempo on the d3 bishop.'),
  (19, 'Bc2', 'Retreat, keeping the b1-h7 diagonal.'),
  (20, 'Nd7', 'The knight heads for the dream c5/e5 squares.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'modern-defense' and ol.rank = 3;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'modern-defense'), 'Classical: 4.Nf3 c6', 4);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'White takes the center.'),
  (2, 'g6', 'The Modern.'),
  (3, 'd4', 'Full center.'),
  (4, 'Bg7', 'The fianchetto.'),
  (5, 'Nc3', 'Development.'),
  (6, 'd6', 'Standard restraint.'),
  (7, 'Nf3', 'The classical treatment: simple development.'),
  (8, 'c6', 'Flexible: support ...b5 and ...d5 ideas, give the queen c7.'),
  (9, 'Bd3', 'Develop, keeping e2 free for the knight reroute.'),
  (10, 'b5', 'Queenside expansion, the Modern''s trademark.'),
  (11, 'O-O', 'White castles.'),
  (12, 'Nd7', 'Develop, keeping the g8 knight flexible.'),
  (13, 'a4', 'White probes the advanced pawn.'),
  (14, 'b4', 'Advance rather than concede the file.'),
  (15, 'Ne2', 'Reroute toward g3/d4.'),
  (16, 'Ngf6', 'Finally develop, hitting e4.'),
  (17, 'Ng3', 'Cover e4 and prepare kingside play.'),
  (18, 'O-O', 'King safety.'),
  (19, 'a5', 'White fixes the queenside — space vs. flexibility.'),
  (20, 'Qc7', 'Connect and eye e5; a rich maneuvering game unfolds.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'modern-defense' and ol.rank = 4;

-- Caro-Kann Defense (B10)
insert into public.openings (slug, name, eco, playable_colors, detection_keys) values ('caro-kann', 'Caro-Kann Defense', 'B10', '{black,white}', '{"caro-kann","caro kann"}');
insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'caro-kann'), 'Advance: 3...Bf5 Main Line', 1);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'White takes the center.'),
  (2, 'c6', 'The Caro-Kann: prepare ...d5 with support.'),
  (3, 'd4', 'White builds the full center.'),
  (4, 'd5', 'The planned strike at e4.'),
  (5, 'e5', 'The Advance: White grabs space and locks the center.'),
  (6, 'Bf5', 'The whole point of the Caro-Kann: this bishop escapes BEFORE ...e6.'),
  (7, 'Nf3', 'Natural development.'),
  (8, 'e6', 'Now close the door — the bishop is already outside.'),
  (9, 'Be2', 'Modest development, avoiding early commitments.'),
  (10, 'Nd7', 'Develop, keeping ...c5 ready.'),
  (11, 'O-O', 'White castles.'),
  (12, 'Bg6', 'Prophylaxis: sidestep Nh4 and clear f5 for a knight.'),
  (13, 'Nbd2', 'White regroups toward b3/c4.'),
  (14, 'Ne7', 'The king''s knight takes the free route.'),
  (15, 'Nb3', 'Restrain ...c5 by covering the square.'),
  (16, 'Nf5', 'The knight lands on its dream blockading square.'),
  (17, 'a4', 'White grabs queenside space.'),
  (18, 'Be7', 'Complete development.'),
  (19, 'a5', 'White fixes the queenside.'),
  (20, 'O-O', 'Castle; Black is solid with a clear plan of ...c5 or ...f6.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'caro-kann' and ol.rank = 1;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'caro-kann'), 'Classical: 4...Bf5', 2);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'White takes the center.'),
  (2, 'c6', 'The Caro-Kann.'),
  (3, 'd4', 'Full center.'),
  (4, 'd5', 'Strike at e4.'),
  (5, 'Nc3', 'White defends e4 with development.'),
  (6, 'dxe4', 'Trade — Black gets a rock-solid structure.'),
  (7, 'Nxe4', 'White recaptures with a centralized knight.'),
  (8, 'Bf5', 'The Classical: develop the problem bishop with tempo.'),
  (9, 'Ng3', 'Attack the bishop.'),
  (10, 'Bg6', 'The standard retreat, still on the key diagonal.'),
  (11, 'h4', 'White probes: the bishop needs luft.'),
  (12, 'h6', 'Give the bishop h7 — never allow h5-h6 for free.'),
  (13, 'Nf3', 'Develop.'),
  (14, 'Nd7', 'Prepare ...Ngf6 without doubled pawns.'),
  (15, 'h5', 'White fixes the bishop on h7.'),
  (16, 'Bh7', 'Tuck it away; it still watches b1-h7.'),
  (17, 'Bd3', 'White offers the trade to exploit the tucked bishop.'),
  (18, 'Bxd3', 'Trade happily — the h5 pawn may become weak.'),
  (19, 'Qxd3', 'White recaptures.'),
  (20, 'e6', 'The famous Caro wall: ugly-looking, extremely hard to break.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'caro-kann' and ol.rank = 2;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'caro-kann'), 'Exchange Variation', 3);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'White takes the center.'),
  (2, 'c6', 'The Caro-Kann.'),
  (3, 'd4', 'Full center.'),
  (4, 'd5', 'Strike at e4.'),
  (5, 'exd5', 'The Exchange: White settles for a small structural game.'),
  (6, 'cxd5', 'Recapture toward the center — a fine Carlsbad structure.'),
  (7, 'Bd3', 'Claim the b1-h7 diagonal before ...Bf5.'),
  (8, 'Nc6', 'Develop with pressure on d4.'),
  (9, 'c3', 'Solidify d4.'),
  (10, 'Nf6', 'Natural development.'),
  (11, 'Bf4', 'White develops actively.'),
  (12, 'Bg4', 'Active development — provoke f3 or Qb3.'),
  (13, 'Qb3', 'Hit b7 and d5 while the c8 bishop is away.'),
  (14, 'Na5', 'The precise reply: hit the queen and cover b7 laterally.'),
  (15, 'Qa4+', 'Check, forcing a block.'),
  (16, 'Bd7', 'Return with tempo on the queen.'),
  (17, 'Qc2', 'Retreat; the dance gained Black time.'),
  (18, 'e6', 'Solidify and open the f8 bishop.'),
  (19, 'Nf3', 'White finishes development.'),
  (20, 'Qb6', 'Target b2 and d4 — Black has easy, active play.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'caro-kann' and ol.rank = 3;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'caro-kann'), 'Panov Attack', 4);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'White takes the center.'),
  (2, 'c6', 'The Caro-Kann.'),
  (3, 'd4', 'Full center.'),
  (4, 'd5', 'Strike at e4.'),
  (5, 'exd5', 'White trades first...'),
  (6, 'cxd5', 'Recapture.'),
  (7, 'c4', '...the Panov: an IQP position by force.'),
  (8, 'Nf6', 'Develop and pressure d5''s attacker indirectly.'),
  (9, 'Nc3', 'Develop with pressure on d5.'),
  (10, 'e6', 'Hold d5 and open the bishop.'),
  (11, 'Nf3', 'Develop.'),
  (12, 'Bb4', 'Pin — the endgame variation, Black''s most solid path.'),
  (13, 'cxd5', 'Clarify the center.'),
  (14, 'Nxd5', 'Recapture with the knight, eyeing c3.'),
  (15, 'Bd2', 'Break the pin''s sting.'),
  (16, 'Nc6', 'Develop with pressure on d4.'),
  (17, 'Bd3', 'Develop toward the kingside.'),
  (18, 'O-O', 'King safety.'),
  (19, 'O-O', 'White castles too.'),
  (20, 'Be7', 'Reposition; Black blockades the IQP and trades pieces.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'caro-kann' and ol.rank = 4;

-- French Defense (C02)
insert into public.openings (slug, name, eco, playable_colors, detection_keys) values ('french-defense', 'French Defense', 'C02', '{black,white}', '{"french defense"}');
insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'french-defense'), 'Advance: 3.e5 c5 Main Line', 1);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'White takes the center.'),
  (2, 'e6', 'The French: prepare ...d5 behind a wall.'),
  (3, 'd4', 'Full center.'),
  (4, 'd5', 'The planned break.'),
  (5, 'e5', 'The Advance: space grab, locking the center.'),
  (6, 'c5', 'Attack the chain at its base immediately.'),
  (7, 'c3', 'White defends the base.'),
  (8, 'Nc6', 'Pile on d4.'),
  (9, 'Nf3', 'Defend d4 again.'),
  (10, 'Qb6', 'More pressure on d4 — and b2 is watched too.'),
  (11, 'a3', 'Prepare b4 to gain space and shield b2.'),
  (12, 'Nh6', 'The clever route: this knight belongs on f5, hitting d4.'),
  (13, 'b4', 'White expands, gaining a tempo on c5.'),
  (14, 'cxd4', 'Trade at the right moment.'),
  (15, 'cxd4', 'White recaptures, keeping the chain.'),
  (16, 'Nf5', 'The knight arrives: d4 is attacked once more.'),
  (17, 'Bb2', 'Defend d4 laterally.'),
  (18, 'Bd7', 'Develop, preparing ...Rc8 on the open file.'),
  (19, 'Be2', 'White finishes development.'),
  (20, 'Be7', 'Prepare ...O-O; the fight for d4 defines the game.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'french-defense' and ol.rank = 1;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'french-defense'), 'Winawer: Poisoned Pawn', 2);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'White takes the center.'),
  (2, 'e6', 'The French.'),
  (3, 'd4', 'Full center.'),
  (4, 'd5', 'The planned break.'),
  (5, 'Nc3', 'White defends e4 with development.'),
  (6, 'Bb4', 'The Winawer: pin the defender of e4.'),
  (7, 'e5', 'White grabs space now that e4 is resolved.'),
  (8, 'c5', 'Strike the base at once.'),
  (9, 'a3', 'Put the question to the bishop.'),
  (10, 'Bxc3+', 'Take: doubled pawns forever vs. the bishop pair.'),
  (11, 'bxc3', 'White recaptures.'),
  (12, 'Ne7', 'Develop around the wedge.'),
  (13, 'Qg4', 'The critical try: g7 hangs because the bishop left.'),
  (14, 'Qc7', 'The Poisoned Pawn: let g7 go, take the center instead!'),
  (15, 'Qxg7', 'White grabs the pawn and the h8 rook is next.'),
  (16, 'Rg8', 'Kick the queen with the rook — the point.'),
  (17, 'Qxh7', 'White takes a second pawn but falls badly behind.'),
  (18, 'cxd4', 'Black wins the center; the c3 pawns collapse.'),
  (19, 'Ne2', 'Defend against ...dxc3 and develop at last.'),
  (20, 'Nbc6', 'Full mobilization — Black''s initiative compensates everything.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'french-defense' and ol.rank = 2;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'french-defense'), 'Tarrasch: 3...c5 Open System', 3);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'White takes the center.'),
  (2, 'e6', 'The French.'),
  (3, 'd4', 'Full center.'),
  (4, 'd5', 'The planned break.'),
  (5, 'Nd2', 'The Tarrasch: defend e4 without allowing the ...Bb4 pin.'),
  (6, 'c5', 'The most active reply: hit d4 immediately.'),
  (7, 'exd5', 'White trades in the center.'),
  (8, 'exd5', 'Recapture — accepting an IQP for free piece play.'),
  (9, 'Ngf3', 'Develop and blockade-in-waiting on d4.'),
  (10, 'Nc6', 'Develop.'),
  (11, 'Bb5', 'Pin and pressure the IQP-to-be.'),
  (12, 'Bd6', 'The active diagonal — Black plays for the initiative.'),
  (13, 'dxc5', 'Trade to fix the isolated pawn.'),
  (14, 'Bxc5', 'Recapture; the bishop remains active.'),
  (15, 'O-O', 'White castles.'),
  (16, 'Ne7', 'The flexible square: keep f6 for a knight later... or f5 hops.'),
  (17, 'Nb3', 'Hit the bishop and head for d4.'),
  (18, 'Bd6', 'Keep the attacking diagonal.'),
  (19, 'Re1', 'White takes the open file.'),
  (20, 'O-O', 'Castle; the IQP gives Black activity for the structure.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'french-defense' and ol.rank = 3;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'french-defense'), 'Classical Steinitz: 4.e5', 4);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'White takes the center.'),
  (2, 'e6', 'The French.'),
  (3, 'd4', 'Full center.'),
  (4, 'd5', 'The planned break.'),
  (5, 'Nc3', 'Defend e4.'),
  (6, 'Nf6', 'The Classical: develop and re-attack e4.'),
  (7, 'e5', 'The Steinitz: gain space with tempo.'),
  (8, 'Nfd7', 'The standard retreat — ...c5 and ...f6 are coming.'),
  (9, 'f4', 'White reinforces the wedge massively.'),
  (10, 'c5', 'Base strike, as always in the French.'),
  (11, 'Nf3', 'Develop and hold d4.'),
  (12, 'Nc6', 'Pile on d4.'),
  (13, 'Be3', 'Defend d4 once more.'),
  (14, 'cxd4', 'Trade before White consolidates.'),
  (15, 'Nxd4', 'Recapture with the piece, keeping the chain flexible.'),
  (16, 'Bc5', 'Pin the knight against the loose e3 bishop.'),
  (17, 'Qd2', 'Unpin and connect for O-O-O.'),
  (18, 'O-O', 'Castle — into the storm, but the center counterplay is real.'),
  (19, 'O-O-O', 'Kings on opposite wings: a razor-sharp race.'),
  (20, 'a6', 'Start the queenside pawn avalanche with ...b5 next.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'french-defense' and ol.rank = 4;

-- Scandinavian Defense (B01)
insert into public.openings (slug, name, eco, playable_colors, detection_keys) values ('scandinavian', 'Scandinavian Defense', 'B01', '{black,white}', '{"scandinavian defense"}');
insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'scandinavian'), 'Main Line: 3...Qa5', 1);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'White takes the center.'),
  (2, 'd5', 'The Scandinavian: challenge e4 on move one.'),
  (3, 'exd5', 'White accepts — declining gives Black easy play.'),
  (4, 'Qxd5', 'Recapture immediately; the queen comes out early by design.'),
  (5, 'Nc3', 'Develop with tempo on the queen.'),
  (6, 'Qa5', 'The classical square: safe, pinning ideas against d2.'),
  (7, 'd4', 'White takes the center that remains.'),
  (8, 'Nf6', 'Develop.'),
  (9, 'Nf3', 'Develop.'),
  (10, 'c6', 'The system move: a Caro-like wall and an escape square for the queen.'),
  (11, 'Bc4', 'Active development, eyeing f7.'),
  (12, 'Bf5', 'The good bishop develops outside the wall first.'),
  (13, 'Bd2', 'Discourage ...Bb4 and prepare Nd5/Ne4 tricks against the queen.'),
  (14, 'e6', 'Complete the wall.'),
  (15, 'Qe2', 'Prepare O-O-O with central pressure.'),
  (16, 'Bb4', 'Pin, fighting for the d5/e4 squares.'),
  (17, 'O-O-O', 'White castles long — sharp opposite-side play.'),
  (18, 'Nbd7', 'Finish development, ready to castle either way.'),
  (19, 'a3', 'Put the question to the bishop.'),
  (20, 'Bxc3', 'Trade and damage the queenside — Black''s structure is superb.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'scandinavian' and ol.rank = 1;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'scandinavian'), 'Modern: 3...Qd6', 2);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'White takes the center.'),
  (2, 'd5', 'The Scandinavian.'),
  (3, 'exd5', 'White accepts.'),
  (4, 'Qxd5', 'Recapture.'),
  (5, 'Nc3', 'Tempo on the queen.'),
  (6, 'Qd6', 'The modern square: flexible, watching e5 and the d-file.'),
  (7, 'd4', 'White builds.'),
  (8, 'Nf6', 'Develop.'),
  (9, 'Nf3', 'Develop.'),
  (10, 'a6', 'The key system move: deny b5 to knight and bishop forever.'),
  (11, 'g3', 'White fianchettoes against the coming ...b5/...Bb7.'),
  (12, 'b5', 'Expand — Black plays on the queenside light squares.'),
  (13, 'Bg2', 'Complete the fianchetto.'),
  (14, 'Bb7', 'Oppose it on the long diagonal.'),
  (15, 'O-O', 'White castles.'),
  (16, 'e6', 'Solidify and open the f8 bishop.'),
  (17, 'Bf4', 'Hit the queen with tempo.'),
  (18, 'Qb6', 'Sidestep, keeping an eye on d4 and b2.'),
  (19, 'a4', 'White strikes at the pawn chain.'),
  (20, 'b4', 'Advance — the knight must find a new home.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'scandinavian' and ol.rank = 2;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'scandinavian'), 'Modern Scandinavian: 2...Nf6', 3);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'White takes the center.'),
  (2, 'd5', 'The Scandinavian.'),
  (3, 'exd5', 'White accepts.'),
  (4, 'Nf6', 'The modern gambit approach: recapture with the knight.'),
  (5, 'd4', 'White keeps the pawn for now and builds.'),
  (6, 'Nxd5', 'Regain it; the knight sits well on d5.'),
  (7, 'Nf3', 'Develop.'),
  (8, 'g6', 'Fianchetto — pressure on d4 defines Black''s setup.'),
  (9, 'Be2', 'Solid development.'),
  (10, 'Bg7', 'The bishop bears down on d4.'),
  (11, 'O-O', 'White castles.'),
  (12, 'O-O', 'Black follows.'),
  (13, 'c4', 'Gain space with tempo on the knight.'),
  (14, 'Nb6', 'The standard retreat, pressuring c4.'),
  (15, 'Nc3', 'Develop; White has space, Black has targets.'),
  (16, 'Nc6', 'Pile on d4 — the whole point of the setup.'),
  (17, 'Be3', 'Defend d4.'),
  (18, 'Bg4', 'Add pressure: the f3 defender is pinned.'),
  (19, 'd5', 'White pushes, releasing the tension under pressure.'),
  (20, 'Bxf3', 'Remove the defender before retreating the knight.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'scandinavian' and ol.rank = 3;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'scandinavian'), '3...Qd8: The Banker', 4);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'White takes the center.'),
  (2, 'd5', 'The Scandinavian.'),
  (3, 'exd5', 'White accepts.'),
  (4, 'Qxd5', 'Recapture.'),
  (5, 'Nc3', 'Tempo on the queen.'),
  (6, 'Qd8', 'Full retreat: lose time, keep an unbreakable structure.'),
  (7, 'd4', 'White builds the center.'),
  (8, 'Nf6', 'Develop.'),
  (9, 'Nf3', 'Develop.'),
  (10, 'Bg4', 'Active development while the pin is annoying.'),
  (11, 'h3', 'Put the question.'),
  (12, 'Bxf3', 'Concede the pair to wreck White''s coordination... slightly.'),
  (13, 'Qxf3', 'Recapture; the queen eyes b7.'),
  (14, 'c6', 'Cover b7 and build the wall.'),
  (15, 'Bc4', 'Actively placed, staring at f7.'),
  (16, 'e6', 'Complete the solid shell.'),
  (17, 'O-O', 'White castles.'),
  (18, 'Nbd7', 'Develop, heading for ...Be7 and ...O-O.'),
  (19, 'Bf4', 'White enjoys free development.'),
  (20, 'Be7', 'Black completes the setup: passive but nearly refutation-proof.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'scandinavian' and ol.rank = 4;

-- King's Indian Defense (E60)
insert into public.openings (slug, name, eco, playable_colors, detection_keys) values ('kings-indian', 'King''s Indian Defense', 'E60', '{black,white}', '{"kings indian defense","king''s indian defense"}');
insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'kings-indian'), 'Classical: Mar del Plata', 1);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'd4', 'White takes the center.'),
  (2, 'Nf6', 'The Indian move: control e4 with a piece first.'),
  (3, 'c4', 'White grabs more space.'),
  (4, 'g6', 'The King''s Indian: fianchetto and strike later.'),
  (5, 'Nc3', 'Development.'),
  (6, 'Bg7', 'The KID bishop.'),
  (7, 'e4', 'White owns the full center — for now.'),
  (8, 'd6', 'Restrain e5 and prepare ...e5.'),
  (9, 'Nf3', 'The Classical System.'),
  (10, 'O-O', 'Castle first — the structure fight comes next.'),
  (11, 'Be2', 'Development.'),
  (12, 'e5', 'The central strike that defines the KID.'),
  (13, 'O-O', 'White castles, keeping the tension.'),
  (14, 'Nc6', 'Pressure d4, forcing the decision.'),
  (15, 'd5', 'White closes: the Mar del Plata race begins.'),
  (16, 'Ne7', 'Reroute — the knight supports ...f5.'),
  (17, 'Ne1', 'White reroutes too: f3 must be free for the f-pawn... and d3 beckons.'),
  (18, 'Nd7', 'Clear f6 so the f-pawn can advance; cover c5 too.'),
  (19, 'Be3', 'White prepares the c5 queenside break.'),
  (20, 'f5', 'The storm begins: Black attacks the king, White the queenside.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'kings-indian' and ol.rank = 1;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'kings-indian'), 'Sämisch Variation', 2);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'd4', 'White takes the center.'),
  (2, 'Nf6', 'Indian development.'),
  (3, 'c4', 'Space.'),
  (4, 'g6', 'The KID.'),
  (5, 'Nc3', 'Development.'),
  (6, 'Bg7', 'The KID bishop.'),
  (7, 'e4', 'Full center.'),
  (8, 'd6', 'Restraint.'),
  (9, 'f3', 'The Sämisch: a concrete wall behind which to attack.'),
  (10, 'O-O', 'Castle and let White commit.'),
  (11, 'Be3', 'Development toward Qd2/O-O-O.'),
  (12, 'e5', 'The classical strike works here too.'),
  (13, 'd5', 'White closes the center.'),
  (14, 'Nh5', 'The point: with f3 played, ...Nh5-f4 and ...f5 come fast.'),
  (15, 'Qd2', 'White connects for long castling.'),
  (16, 'f5', 'The thematic break, gaining kingside space.'),
  (17, 'O-O-O', 'Opposite wings: a pure attacking race.'),
  (18, 'Nd7', 'Bring the last knight toward c5 and f6 duties.'),
  (19, 'exf5', 'White trades to open lines for the g4 push.'),
  (20, 'gxf5', 'Recapture toward the center, keeping the pawn mass rolling.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'kings-indian' and ol.rank = 2;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'kings-indian'), 'Four Pawns Attack', 3);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'd4', 'White takes the center.'),
  (2, 'Nf6', 'Indian development.'),
  (3, 'c4', 'Space.'),
  (4, 'g6', 'The KID.'),
  (5, 'Nc3', 'Development.'),
  (6, 'Bg7', 'The KID bishop.'),
  (7, 'e4', 'Full center.'),
  (8, 'd6', 'Restraint.'),
  (9, 'f4', 'The Four Pawns: maximum ambition, maximum targets.'),
  (10, 'O-O', 'Castle and prepare to strike the overextended wall.'),
  (11, 'Nf3', 'Develop behind the pawns.'),
  (12, 'c5', 'The correct break — hit d4 before the wall rolls.'),
  (13, 'd5', 'White closes.'),
  (14, 'e6', 'Undermine the new spearhead immediately.'),
  (15, 'Be2', 'Development.'),
  (16, 'exd5', 'Open the e-file at the right moment.'),
  (17, 'cxd5', 'White keeps the center duo.'),
  (18, 'Re8', 'The rook hits e4 — White''s center is pinned down.'),
  (19, 'e5', 'White lashes out — the critical, double-edged try.'),
  (20, 'dxe5', 'Take; after fxe5 ...Ng4 the center falls under siege.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'kings-indian' and ol.rank = 3;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'kings-indian'), 'Fianchetto Variation', 4);
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'd4', 'White takes the center.'),
  (2, 'Nf6', 'Indian development.'),
  (3, 'c4', 'Space.'),
  (4, 'g6', 'The KID.'),
  (5, 'Nf3', 'White chooses the calm system.'),
  (6, 'Bg7', 'The KID bishop.'),
  (7, 'g3', 'The Fianchetto: White''s bishop will blunt the g7 monster.'),
  (8, 'O-O', 'Castle.'),
  (9, 'Bg2', 'Complete the fianchetto.'),
  (10, 'd6', 'The standard structure.'),
  (11, 'O-O', 'White castles.'),
  (12, 'Nbd7', 'Support ...e5 the flexible way.'),
  (13, 'Nc3', 'Development complete.'),
  (14, 'e5', 'The strike.'),
  (15, 'e4', 'White claims the center fully, avoiding simplifications.'),
  (16, 'c6', 'Give the queen b6 and prepare ...exd4 with ...d5 ideas.'),
  (17, 'h3', 'Stop ...Ng4 and prepare Be3.'),
  (18, 'Qb6', 'Hit d4 and b2 — awkward pressure against the fianchetto.'),
  (19, 'Re1', 'Defend e4 laterally and support d4 tactics.'),
  (20, 'exd4', 'Win the central skirmish — ...Nc5 and ...d5 follow.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'kings-indian' and ol.rank = 4;

commit;
