// Sources (see README "Metodología de curaduría"):
//   Theory: standard published theory for the named variations, cross-checked
//   against Wikibooks "Chess Opening Theory" (consulted 2026-07-17). ECO B10-B17.
//   Engine audit 2026-07-20 (Stockfish 17.1, scripts/audit-lines.mjs): all lines
//   clean; only the rank 6 final move was fixed (...cxd4 instead of ...Nc6,
//   which dropped ~1 pawn of eval to a d4-d5 tactic).
export default {
  slug: "caro-kann",
  name: "Caro-Kann Defense",
  eco: "B10",
  playableColors: ["black", "white"],
  detectionKeys: ["caro-kann", "caro kann"],
  lines: [
    {
      rank: 1,
      name: "Advance: 3...Bf5 Main Line",
      moves: [
        ["e4", "White takes the center."],
        ["c6", "The Caro-Kann: prepare ...d5 with support."],
        ["d4", "White builds the full center."],
        ["d5", "The planned strike at e4."],
        ["e5", "The Advance: White grabs space and locks the center."],
        ["Bf5", "The whole point of the Caro-Kann: this bishop escapes BEFORE ...e6."],
        ["Nf3", "Natural development."],
        ["e6", "Now close the door — the bishop is already outside."],
        ["Be2", "Modest development, avoiding early commitments."],
        ["Nd7", "Develop, keeping ...c5 ready."],
        ["O-O", "White castles."],
        ["Bg6", "Prophylaxis: sidestep Nh4 and clear f5 for a knight."],
        ["Nbd2", "White regroups toward b3/c4."],
        ["Ne7", "The king's knight takes the free route."],
        ["Nb3", "Restrain ...c5 by covering the square."],
        ["Nf5", "The knight lands on its dream blockading square."],
        ["a4", "White grabs queenside space."],
        ["Be7", "Complete development."],
        ["a5", "White fixes the queenside."],
        ["O-O", "Castle; Black is solid with a clear plan of ...c5 or ...f6."],
      ],
    },
    {
      rank: 2,
      name: "Classical: 4...Bf5",
      moves: [
        ["e4", "White takes the center."],
        ["c6", "The Caro-Kann."],
        ["d4", "Full center."],
        ["d5", "Strike at e4."],
        ["Nc3", "White defends e4 with development."],
        ["dxe4", "Trade — Black gets a rock-solid structure."],
        ["Nxe4", "White recaptures with a centralized knight."],
        ["Bf5", "The Classical: develop the problem bishop with tempo."],
        ["Ng3", "Attack the bishop."],
        ["Bg6", "The standard retreat, still on the key diagonal."],
        ["h4", "White probes: the bishop needs luft."],
        ["h6", "Give the bishop h7 — never allow h5-h6 for free."],
        ["Nf3", "Develop."],
        ["Nd7", "Prepare ...Ngf6 without doubled pawns."],
        ["h5", "White fixes the bishop on h7."],
        ["Bh7", "Tuck it away; it still watches b1-h7."],
        ["Bd3", "White offers the trade to exploit the tucked bishop."],
        ["Bxd3", "Trade happily — the h5 pawn may become weak."],
        ["Qxd3", "White recaptures."],
        ["e6", "The famous Caro wall: ugly-looking, extremely hard to break."],
      ],
    },
    {
      rank: 3,
      name: "Exchange Variation",
      moves: [
        ["e4", "White takes the center."],
        ["c6", "The Caro-Kann."],
        ["d4", "Full center."],
        ["d5", "Strike at e4."],
        ["exd5", "The Exchange: White settles for a small structural game."],
        ["cxd5", "Recapture toward the center — a fine Carlsbad structure."],
        ["Bd3", "Claim the b1-h7 diagonal before ...Bf5."],
        ["Nc6", "Develop with pressure on d4."],
        ["c3", "Solidify d4."],
        ["Nf6", "Natural development."],
        ["Bf4", "White develops actively."],
        ["Bg4", "Active development — provoke f3 or Qb3."],
        ["Qb3", "Hit b7 and d5 while the c8 bishop is away."],
        ["Na5", "The precise reply: hit the queen and cover b7 laterally."],
        ["Qa4+", "Check, forcing a block."],
        ["Bd7", "Return with tempo on the queen."],
        ["Qc2", "Retreat; the dance gained Black time."],
        ["e6", "Solidify and open the f8 bishop."],
        ["Nf3", "White finishes development."],
        ["Qb6", "Target b2 and d4 — Black has easy, active play."],
      ],
    },
    {
      rank: 4,
      name: "Panov Attack",
      moves: [
        ["e4", "White takes the center."],
        ["c6", "The Caro-Kann."],
        ["d4", "Full center."],
        ["d5", "Strike at e4."],
        ["exd5", "White trades first..."],
        ["cxd5", "Recapture."],
        ["c4", "...the Panov: an IQP position by force."],
        ["Nf6", "Develop and pressure d5's attacker indirectly."],
        ["Nc3", "Develop with pressure on d5."],
        ["e6", "Hold d5 and open the bishop."],
        ["Nf3", "Develop."],
        ["Bb4", "Pin — the endgame variation, Black's most solid path."],
        ["cxd5", "Clarify the center."],
        ["Nxd5", "Recapture with the knight, eyeing c3."],
        ["Bd2", "Break the pin's sting."],
        ["Nc6", "Develop with pressure on d4."],
        ["Bd3", "Develop toward the kingside."],
        ["O-O", "King safety."],
        ["O-O", "White castles too."],
        ["Be7", "Reposition; Black blockades the IQP and trades pieces."],
      ],
    },
    {
      rank: 5,
      name: "Karpov: 4...Nd7",
      moves: [
        ["e4", "White takes the center."],
        ["c6", "The Caro-Kann."],
        ["d4", "Full center."],
        ["d5", "Strike at e4."],
        ["Nc3", "Defend e4 with a piece."],
        ["dxe4", "Release the tension — the classical treatment."],
        ["Nxe4", "Recapture with a centralized knight."],
        ["Nd7", "The Karpov Variation: prepare ...Ngf6 without doubled pawns."],
        ["Ng5", "The modern main line: probe f7 before Black consolidates."],
        ["Ngf6", "Cover f7's h5-attacker routes and develop; ...h6 must wait."],
        ["Bd3", "Aim at h7 and prepare N1f3-e5 tricks."],
        ["e6", "Blunt the d3 bishop and open the f8 bishop."],
        ["N1f3", "The g1 knight joins; g5 and f3 coordinate against e6/f7."],
        ["Bd6", "Active development, controlling e5."],
        ["Qe2", "Pile on e6 and prepare O-O-O or Ne5."],
        ["h6", "Finally put the question to the g5 knight."],
        ["Ne4", "Retreat with tempo play on d6 — the point of Qe2."],
        ["Nxe4", "Trade the attacker."],
        ["Qxe4", "Recapture, keeping h7 under watch."],
        ["Qc7", "Cover e5/h2 tricks and prepare ...b6 or ...c5 — the tabiya."],
      ],
    },
    {
      rank: 6,
      name: "Tartakower: 5...exf6",
      moves: [
        ["e4", "White takes the center."],
        ["c6", "The Caro-Kann."],
        ["d4", "Full center."],
        ["d5", "Strike at e4."],
        ["Nc3", "Defend e4 with a piece."],
        ["dxe4", "Release the tension."],
        ["Nxe4", "Recapture."],
        ["Nf6", "Offer the trade — Black accepts a structural change for activity."],
        ["Nxf6+", "Take; declining loses time."],
        ["exf6", "The Tartakower: open the f8 bishop and keep a rock-solid king."],
        ["c3", "Support d4 against the coming piece pressure."],
        ["Bd6", "The bishop takes the strong kingside diagonal."],
        ["Bd3", "Symmetrical development toward the king."],
        ["O-O", "Castle early — Black's whole setup is built for it."],
        ["Ne2", "Flexible: keep f3 free for the f-pawn and avoid pins."],
        ["Re8", "The rook takes the open e-file at once."],
        ["O-O", "King safety."],
        ["c5", "Break at d4 — Black's active plan in this structure."],
        ["Be3", "Hold d4 and complete development."],
        ["cxd4", "Resolve the tension; after Nxd4 Black develops with full equality."],
      ],
    },
  ],
};
