// Sources (see README "Metodología de curaduría"):
//   Theory: standard published theory for the named variations, cross-checked
//   against Wikibooks "Chess Opening Theory" (consulted 2026-07-17). ECO C01-C19.
//   Engine audit 2026-07-20 (Stockfish 17.1, scripts/audit-lines.mjs): all six
//   lines passed clean — no changes needed.
export default {
  slug: "french-defense",
  name: "French Defense",
  eco: "C02",
  playableColors: ["black", "white"],
  detectionKeys: ["french defense"],
  lines: [
    {
      rank: 1,
      name: "Advance: 3.e5 c5 Main Line",
      moves: [
        ["e4", "White takes the center."],
        ["e6", "The French: prepare ...d5 behind a wall."],
        ["d4", "Full center."],
        ["d5", "The planned break."],
        ["e5", "The Advance: space grab, locking the center."],
        ["c5", "Attack the chain at its base immediately."],
        ["c3", "White defends the base."],
        ["Nc6", "Pile on d4."],
        ["Nf3", "Defend d4 again."],
        ["Qb6", "More pressure on d4 — and b2 is watched too."],
        ["a3", "Prepare b4 to gain space and shield b2."],
        ["Nh6", "The clever route: this knight belongs on f5, hitting d4."],
        ["b4", "White expands, gaining a tempo on c5."],
        ["cxd4", "Trade at the right moment."],
        ["cxd4", "White recaptures, keeping the chain."],
        ["Nf5", "The knight arrives: d4 is attacked once more."],
        ["Bb2", "Defend d4 laterally."],
        ["Bd7", "Develop, preparing ...Rc8 on the open file."],
        ["Be2", "White finishes development."],
        ["Be7", "Prepare ...O-O; the fight for d4 defines the game."],
      ],
    },
    {
      rank: 2,
      name: "Winawer: Poisoned Pawn",
      moves: [
        ["e4", "White takes the center."],
        ["e6", "The French."],
        ["d4", "Full center."],
        ["d5", "The planned break."],
        ["Nc3", "White defends e4 with development."],
        ["Bb4", "The Winawer: pin the defender of e4."],
        ["e5", "White grabs space now that e4 is resolved."],
        ["c5", "Strike the base at once."],
        ["a3", "Put the question to the bishop."],
        ["Bxc3+", "Take: doubled pawns forever vs. the bishop pair."],
        ["bxc3", "White recaptures."],
        ["Ne7", "Develop around the wedge."],
        ["Qg4", "The critical try: g7 hangs because the bishop left."],
        ["Qc7", "The Poisoned Pawn: let g7 go, take the center instead!"],
        ["Qxg7", "White grabs the pawn and the h8 rook is next."],
        ["Rg8", "Kick the queen with the rook — the point."],
        ["Qxh7", "White takes a second pawn but falls badly behind."],
        ["cxd4", "Black wins the center; the c3 pawns collapse."],
        ["Ne2", "Defend against ...dxc3 and develop at last."],
        ["Nbc6", "Full mobilization — Black's initiative compensates everything."],
      ],
    },
    {
      rank: 3,
      name: "Tarrasch: 3...c5 Open System",
      moves: [
        ["e4", "White takes the center."],
        ["e6", "The French."],
        ["d4", "Full center."],
        ["d5", "The planned break."],
        ["Nd2", "The Tarrasch: defend e4 without allowing the ...Bb4 pin."],
        ["c5", "The most active reply: hit d4 immediately."],
        ["exd5", "White trades in the center."],
        ["exd5", "Recapture — accepting an IQP for free piece play."],
        ["Ngf3", "Develop and blockade-in-waiting on d4."],
        ["Nc6", "Develop."],
        ["Bb5", "Pin and pressure the IQP-to-be."],
        ["Bd6", "The active diagonal — Black plays for the initiative."],
        ["dxc5", "Trade to fix the isolated pawn."],
        ["Bxc5", "Recapture; the bishop remains active."],
        ["O-O", "White castles."],
        ["Ne7", "The flexible square: keep f6 for a knight later... or f5 hops."],
        ["Nb3", "Hit the bishop and head for d4."],
        ["Bd6", "Keep the attacking diagonal."],
        ["Re1", "White takes the open file."],
        ["O-O", "Castle; the IQP gives Black activity for the structure."],
      ],
    },
    {
      rank: 4,
      name: "Classical Steinitz: 4.e5",
      moves: [
        ["e4", "White takes the center."],
        ["e6", "The French."],
        ["d4", "Full center."],
        ["d5", "The planned break."],
        ["Nc3", "Defend e4."],
        ["Nf6", "The Classical: develop and re-attack e4."],
        ["e5", "The Steinitz: gain space with tempo."],
        ["Nfd7", "The standard retreat — ...c5 and ...f6 are coming."],
        ["f4", "White reinforces the wedge massively."],
        ["c5", "Base strike, as always in the French."],
        ["Nf3", "Develop and hold d4."],
        ["Nc6", "Pile on d4."],
        ["Be3", "Defend d4 once more."],
        ["cxd4", "Trade before White consolidates."],
        ["Nxd4", "Recapture with the piece, keeping the chain flexible."],
        ["Bc5", "Pin the knight against the loose e3 bishop."],
        ["Qd2", "Unpin and connect for O-O-O."],
        ["O-O", "Castle — into the storm, but the center counterplay is real."],
        ["O-O-O", "Kings on opposite wings: a razor-sharp race."],
        ["a6", "Start the queenside pawn avalanche with ...b5 next."],
      ],
    },
    {
      rank: 5,
      name: "Rubinstein Variation",
      moves: [
        ["e4", "White takes the center."],
        ["e6", "The French."],
        ["d4", "Full center."],
        ["d5", "The planned break."],
        ["Nc3", "Defend e4."],
        ["dxe4", "The Rubinstein: trade the tension away for a compact game."],
        ["Nxe4", "Recapture with a centralized knight."],
        ["Nd7", "Prepare ...Ngf6 so a trade doesn't wreck the pawns."],
        ["Nf3", "Natural development."],
        ["Ngf6", "Offer the trade on White's terms no longer."],
        ["Nxf6+", "Take — retreating concedes the tempo battle."],
        ["Nxf6", "Recapture with the piece, keeping the structure clean."],
        ["Bd3", "The active diagonal, eyeing h7."],
        ["c5", "The essential break — without it Black suffocates."],
        ["dxc5", "Trade toward a small but lasting development lead."],
        ["Bxc5", "Recapture, completing a key developing move for free."],
        ["Qe2", "Connect for O-O-O ideas and control e5."],
        ["O-O", "King safety."],
        ["Bg5", "The last piece out, pinning — White's edge is activity."],
        ["b6", "Solve the eternal French problem: ...Bb7 comes next."],
      ],
    },
    {
      rank: 6,
      name: "Exchange Variation",
      moves: [
        ["e4", "White takes the center."],
        ["e6", "The French."],
        ["d4", "Full center."],
        ["d5", "The planned break."],
        ["exd5", "The Exchange: trade into a symmetric, open structure."],
        ["exd5", "Recapture — the c8 bishop is finally free."],
        ["Nf3", "Develop toward the kingside."],
        ["Nf6", "Mirror development."],
        ["Bd3", "The active diagonal."],
        ["Bd6", "Black mirrors — in symmetry, activity is everything."],
        ["O-O", "King safety."],
        ["O-O", "Black castles."],
        ["Bg5", "Create the first asymmetry: pressure on f6."],
        ["Bg4", "Answer in kind against f3."],
        ["Nbd2", "Flexible: support Nf3, keep c3 free for the pawn."],
        ["Nbd7", "Same mirror logic."],
        ["c3", "Solidify d4 and open the queen's path to b3/c2."],
        ["c6", "Match it; both sides fight for the e-file next."],
        ["Qc2", "Step off the pin's file and eye h7."],
        ["Qc7", "Symmetry holds — the middlegame is a pure activity contest."],
      ],
    },
  ],
};
