// Sources (see README "Metodología de curaduría"):
//   Theory: standard published theory for the named variations, cross-checked
//   against Wikibooks "Chess Opening Theory" (consulted 2026-07-17). ECO C50-C55.
//   Engine audit 2026-07-20 (Stockfish 17.1, scripts/audit-lines.mjs): rank 4
//   tail fixed (9.Bb3!, the theory move — the old 9.Qe4 lost the thread).
//   Documented exception: the Fried Liver (rank 4) ends ~+0.9 for White by
//   design — it punishes the dubious-but-common 5...Nxd5. Black's sound
//   treatment of 4.Ng5 is rank 2 (5...Na5), also in this catalog.
export default {
  slug: "italian-game",
  name: "Italian Game",
  eco: "C50",
  playableColors: ["white", "black"],
  detectionKeys: ["italian game", "giuoco piano", "two knights defense"],
  lines: [
    {
      rank: 1,
      name: "Giuoco Pianissimo: c3-d3 Main Line",
      moves: [
        ["e4", "Take the center."],
        ["e5", "Symmetrical reply."],
        ["Nf3", "Attack e5 and develop."],
        ["Nc6", "Defend e5."],
        ["Bc4", "The Italian: eye f7 and prepare O-O."],
        ["Bc5", "Mirror development on the strong diagonal."],
        ["c3", "Prepare d4 and give the bishop the c2 retreat."],
        ["Nf6", "Develop with pressure on e4."],
        ["d3", "The modern slow treatment: keep the center flexible."],
        ["d6", "Black matches the slow structure."],
        ["O-O", "King safety."],
        ["O-O", "Black castles too."],
        ["Re1", "Support e4 and prepare d4 later."],
        ["a6", "Give the c5 bishop a retreat and gain space."],
        ["Bb3", "Sidestep in advance; the bishop stays on the key diagonal."],
        ["Ba7", "Same idea — the bishop keeps eyeing f2 from safety."],
        ["h3", "Stop ...Bg4 and ...Ng4 before regrouping."],
        ["h6", "Black mirrors, stopping Bg5 and Ng5."],
        ["Nbd2", "The famous maneuver begins: Nd2-f1-g3 toward f5."],
        ["Re8", "Black centralizes a rook awaiting the middlegame."],
      ],
    },
    {
      rank: 2,
      name: "Two Knights: 4.Ng5 Main Line",
      moves: [
        ["e4", "Take the center."],
        ["e5", "Symmetrical reply."],
        ["Nf3", "Attack e5 and develop."],
        ["Nc6", "Defend e5."],
        ["Bc4", "The Italian bishop."],
        ["Nf6", "The Two Knights: counterattack e4 instead of defending."],
        ["Ng5", "The critical test: attack f7 twice at once."],
        ["d5", "The only good defense: block the diagonal."],
        ["exd5", "Take, keeping the threats alive."],
        ["Na5", "The main line: hit the c4 bishop instead of recapturing."],
        ["Bb5+", "Keep the extra pawn with tempo."],
        ["c6", "Block and attack the bishop, offering a pawn for activity."],
        ["dxc6", "Take again; White is up two pawns temporarily."],
        ["bxc6", "Recapture and hit b5 — Black gets a huge initiative."],
        ["Be2", "The safest retreat, covering the f3 square."],
        ["h6", "Kick the knight back with tempo."],
        ["Nf3", "Retreat; White holds a pawn but must weather the storm."],
        ["e4", "The pawn kicks again — Black plays for full compensation."],
        ["Ne5", "The best square: centralized and hitting c6."],
        ["Bd6", "Develop with tempo against the e5 knight."],
      ],
    },
    {
      rank: 3,
      name: "Evans Gambit",
      moves: [
        ["e4", "Take the center."],
        ["e5", "Symmetrical reply."],
        ["Nf3", "Attack e5 and develop."],
        ["Nc6", "Defend e5."],
        ["Bc4", "The Italian bishop."],
        ["Bc5", "The Giuoco Piano move."],
        ["b4", "The Evans Gambit: a pawn for time and a monster center."],
        ["Bxb4", "Accepting is critical — declining concedes space for free."],
        ["c3", "Gain another tempo on the bishop while preparing d4."],
        ["Ba5", "The main retreat, keeping the pin option on c3."],
        ["d4", "The point: a full center arrives with threats."],
        ["exd4", "Black must trade before being squeezed."],
        ["O-O", "Sacrifice a second pawn for a huge lead in development."],
        ["Nge7", "Modern defense: rush the king toward safety."],
        ["cxd4", "Restore one pawn and own the center."],
        ["d5", "Strike back before White's center rolls."],
        ["exd5", "Open lines — exactly what the gambiteer wants."],
        ["Nxd5", "Recapture toward the center."],
        ["Ba3", "The dark-square bishop denies Black castling rights."],
        ["Be6", "Develop and shore up the d5 knight."],
      ],
    },
    {
      rank: 4,
      name: "Two Knights: Fried Liver Attack",
      moves: [
        ["e4", "Take the center."],
        ["e5", "Symmetrical reply."],
        ["Nf3", "Attack e5 and develop."],
        ["Nc6", "Defend e5."],
        ["Bc4", "The Italian bishop."],
        ["Nf6", "The Two Knights Defense."],
        ["Ng5", "Attack f7 twice."],
        ["d5", "The necessary block."],
        ["exd5", "Capture and keep the pressure."],
        ["Nxd5", "The risky recapture that allows the famous sacrifice."],
        ["Nxf7", "The Fried Liver: rip open the king's cover."],
        ["Kxf7", "Forced — declining just loses a pawn for nothing."],
        ["Qf3+", "Fork the king and the loose d5 knight."],
        ["Ke6", "The only way to hold the knight — the king marches out."],
        ["Nc3", "Pile on d5 with every developing move."],
        ["Nb4", "Reinforce d5 while threatening ...Nxc2 forks."],
        ["Bb3", "Preserve the bishop and keep every threat on d5 alive."],
        ["c6", "Finally shore up d5 with the pawn."],
        ["a3", "Push the b4 knight away from its defense."],
        ["Na6", "The knight retreats; White regains material with a raging attack."],
      ],
    },
    {
      rank: 5,
      name: "Giuoco Piano: Center Attack 5.d4",
      moves: [
        ["e4", "Take the center."],
        ["e5", "Symmetrical reply."],
        ["Nf3", "Attack e5 and develop."],
        ["Nc6", "Defend e5."],
        ["Bc4", "The Italian bishop."],
        ["Bc5", "Mirror development."],
        ["c3", "Prepare d4 with pawn support."],
        ["Nf6", "Hit e4 rather than defend passively."],
        ["d4", "The classical center attack — the old main line of the Giuoco."],
        ["exd4", "Take; letting White keep d4-e4 for free is worse."],
        ["cxd4", "Recapture with the ideal pawn duo, hitting the c5 bishop."],
        ["Bb4+", "The saving check — without it Black is simply worse."],
        ["Bd2", "The solid main line; 7.Nc3 is the wild Greco gambit."],
        ["Bxd2+", "Trade — keeping the bishop loses time."],
        ["Nbxd2", "Recapture, developing at the same time."],
        ["d5", "The classical equalizer: strike e4 before the center rolls."],
        ["exd5", "Take — protecting e4 leaves d4 weak."],
        ["Nxd5", "Recapture with a fine blockading knight."],
        ["Qb3", "The critical try: double-attack d5 and b7."],
        ["Nce7", "The main defense: hold d5 with everything."],
      ],
    },
    {
      rank: 6,
      name: "Two Knights: Modern 4.d3",
      moves: [
        ["e4", "Take the center."],
        ["e5", "Symmetrical reply."],
        ["Nf3", "Attack e5 and develop."],
        ["Nc6", "Defend e5."],
        ["Bc4", "The Italian bishop."],
        ["Nf6", "The Two Knights Defense."],
        ["d3", "The modern choice at every level: keep the tension, skip 4.Ng5 theory."],
        ["Be7", "Solid — avoid c3-d4 tempo hits on a c5 bishop."],
        ["O-O", "King safety."],
        ["O-O", "Black castles."],
        ["Re1", "Standard e4 support before regrouping."],
        ["d6", "Hold e5 and open the c8 bishop."],
        ["a4", "Modern wing space — also readies Ba2 keeping the diagonal."],
        ["Na5", "Trade-seeking: the knight hunts the strong c4 bishop."],
        ["Ba2", "Preserve it — this bishop is White's best piece."],
        ["c5", "Grab queenside space and give the knight a home on c6 again."],
        ["c3", "Prepare d4 and keep the a5 knight shut out of b3/c4."],
        ["Nc6", "Return to the center — the a5 trip fixed the queenside terms."],
        ["Nbd2", "The familiar Italian tour toward f1-g3."],
        ["Be6", "Offer the trade to ease the position — the modern tabiya."],
      ],
    },
  ],
};
