// Sources (see README "Metodología de curaduría"):
//   ranks 1-4: initial catalog (2026-07-14), legality-validated only; theory audit pending.
//   ranks 5-6 (added 2026-07-17): standard published theory for the named variations,
//   cross-checked against Wikibooks "Chess Opening Theory" where coverage exists
//   (en.wikibooks.org/wiki/Chess_Opening_Theory, consulted 2026-07-17); natural-play
//   extensions past book depth. Masters-DB frequency check (scripts/verify-lines.mjs)
//   pending — the explorer API was auth-gated at the time of writing.
//   Rank 5: Averbakh Variation (ECO E73). Rank 6: Makagonov System 6.h3 (ECO E71/E90).
export default {
  slug: "kings-indian",
  name: "King's Indian Defense",
  eco: "E60",
  playableColors: ["black", "white"],
  detectionKeys: ["kings indian defense", "king's indian defense"],
  lines: [
    {
      rank: 1,
      name: "Classical: Mar del Plata",
      moves: [
        ["d4", "White takes the center."],
        ["Nf6", "The Indian move: control e4 with a piece first."],
        ["c4", "White grabs more space."],
        ["g6", "The King's Indian: fianchetto and strike later."],
        ["Nc3", "Development."],
        ["Bg7", "The KID bishop."],
        ["e4", "White owns the full center — for now."],
        ["d6", "Restrain e5 and prepare ...e5."],
        ["Nf3", "The Classical System."],
        ["O-O", "Castle first — the structure fight comes next."],
        ["Be2", "Development."],
        ["e5", "The central strike that defines the KID."],
        ["O-O", "White castles, keeping the tension."],
        ["Nc6", "Pressure d4, forcing the decision."],
        ["d5", "White closes: the Mar del Plata race begins."],
        ["Ne7", "Reroute — the knight supports ...f5."],
        ["Ne1", "White reroutes too: f3 must be free for the f-pawn... and d3 beckons."],
        ["Nd7", "Clear f6 so the f-pawn can advance; cover c5 too."],
        ["Be3", "White prepares the c5 queenside break."],
        ["f5", "The storm begins: Black attacks the king, White the queenside."],
      ],
    },
    {
      rank: 2,
      name: "Sämisch Variation",
      moves: [
        ["d4", "White takes the center."],
        ["Nf6", "Indian development."],
        ["c4", "Space."],
        ["g6", "The KID."],
        ["Nc3", "Development."],
        ["Bg7", "The KID bishop."],
        ["e4", "Full center."],
        ["d6", "Restraint."],
        ["f3", "The Sämisch: a concrete wall behind which to attack."],
        ["O-O", "Castle and let White commit."],
        ["Be3", "Development toward Qd2/O-O-O."],
        ["e5", "The classical strike works here too."],
        ["d5", "White closes the center."],
        ["Nh5", "The point: with f3 played, ...Nh5-f4 and ...f5 come fast."],
        ["Qd2", "White connects for long castling."],
        ["f5", "The thematic break, gaining kingside space."],
        ["O-O-O", "Opposite wings: a pure attacking race."],
        ["Nd7", "Bring the last knight toward c5 and f6 duties."],
        ["exf5", "White trades to open lines for the g4 push."],
        ["gxf5", "Recapture toward the center, keeping the pawn mass rolling."],
      ],
    },
    {
      rank: 3,
      name: "Four Pawns Attack",
      moves: [
        ["d4", "White takes the center."],
        ["Nf6", "Indian development."],
        ["c4", "Space."],
        ["g6", "The KID."],
        ["Nc3", "Development."],
        ["Bg7", "The KID bishop."],
        ["e4", "Full center."],
        ["d6", "Restraint."],
        ["f4", "The Four Pawns: maximum ambition, maximum targets."],
        ["O-O", "Castle and prepare to strike the overextended wall."],
        ["Nf3", "Develop behind the pawns."],
        ["c5", "The correct break — hit d4 before the wall rolls."],
        ["d5", "White closes."],
        ["e6", "Undermine the new spearhead immediately."],
        ["Be2", "Development."],
        ["exd5", "Open the e-file at the right moment."],
        ["cxd5", "White keeps the center duo."],
        ["Re8", "The rook hits e4 — White's center is pinned down."],
        ["e5", "White lashes out — the critical, double-edged try."],
        ["dxe5", "Take; after fxe5 ...Ng4 the center falls under siege."],
      ],
    },
    {
      rank: 4,
      name: "Fianchetto Variation",
      moves: [
        ["d4", "White takes the center."],
        ["Nf6", "Indian development."],
        ["c4", "Space."],
        ["g6", "The KID."],
        ["Nf3", "White chooses the calm system."],
        ["Bg7", "The KID bishop."],
        ["g3", "The Fianchetto: White's bishop will blunt the g7 monster."],
        ["O-O", "Castle."],
        ["Bg2", "Complete the fianchetto."],
        ["d6", "The standard structure."],
        ["O-O", "White castles."],
        ["Nbd7", "Support ...e5 the flexible way."],
        ["Nc3", "Development complete."],
        ["e5", "The strike."],
        ["e4", "White claims the center fully, avoiding simplifications."],
        ["c6", "Give the queen b6 and prepare ...exd4 with ...d5 ideas."],
        ["h3", "Stop ...Ng4 and prepare Be3."],
        ["Qb6", "Hit d4 and b2 — awkward pressure against the fianchetto."],
        ["Re1", "Defend e4 laterally and support d4 tactics."],
        ["exd4", "Win the central skirmish — ...Nc5 and ...d5 follow."],
      ],
    },
    {
      rank: 5,
      name: "Averbakh Variation",
      moves: [
        ["d4", "White takes the center."],
        ["Nf6", "Indian development."],
        ["c4", "Space."],
        ["g6", "The KID."],
        ["Nc3", "Central development."],
        ["Bg7", "The KID bishop."],
        ["e4", "The big center."],
        ["d6", "The standard structure."],
        ["Be2", "Develop before committing the g1 knight."],
        ["O-O", "Castle."],
        ["Bg5", "The Averbakh: clamp e7 so the standard ...e5 is met by tactics."],
        ["c5", "The main answer — since ...e5 is awkward, strike on the other wing."],
        ["d5", "Close the center into a Benoni structure on White's terms."],
        ["e6", "Challenge the head of the chain immediately."],
        ["Qd2", "Connect with Bg5-h6 ideas and keep e6/d5 tension."],
        ["exd5", "Resolve toward an open e-file."],
        ["exd5", "Keep the space-gaining Benoni bind rather than cxd5."],
        ["Re8", "The rook exploits the freshly opened file."],
        ["Nf3", "Complete development at last."],
        ["Bg4", "Pin and prepare trades to ease the cramped position."],
      ],
    },
    {
      rank: 6,
      name: "Makagonov: 6.h3",
      moves: [
        ["d4", "White takes the center."],
        ["Nf6", "Indian development."],
        ["c4", "Space."],
        ["g6", "The KID."],
        ["Nc3", "Central development."],
        ["Bg7", "The KID bishop."],
        ["e4", "The big center."],
        ["d6", "The standard structure."],
        ["Nf3", "Classical development."],
        ["O-O", "Castle."],
        ["h3", "The Makagonov: prepare Be3/g4 without allowing ...Ng4 or ...Bg4."],
        ["e5", "The thematic strike anyway."],
        ["d5", "Close the center — with h3 in, White's g4 clamp is coming."],
        ["Na6", "The modern route: the knight heads for c5 hitting e4."],
        ["Bg5", "Provoke a concession before completing the setup."],
        ["h6", "Ask the bishop."],
        ["Be3", "Retreat with the point that ...Ng4 never works with h3 played."],
        ["Nc5", "The knight arrives — pressure on e4 pins White's pieces down."],
        ["Nd2", "Overprotect e4 and unblock the f-pawn quietly."],
        ["a5", "Anchor the c5 knight against b4 — the standard tabiya."],
      ],
    },
  ],
};
