// Sources (see README "Metodología de curaduría"):
//   Theory: Wikibooks "Chess Opening Theory" 1.e4 e5 2.f4 pages (consulted
//   2026-07-17): 2...exf4 main (3.Nf3 / 3.Bc4), 2...d5 Falkbeer and 2...Bc5
//   classical declines (ECO C30-C39).
//   Engine audit 2026-07-20 (Stockfish 17.1, scripts/audit-lines.mjs): tails of
//   ranks 2, 3, 5, 6 rebuilt (7.Nc3 in the Modern, ...Bxc1 in the Fischer,
//   7.Na4! in the Classical Declined, ...Qxe2+ in the Falkbeer). Documented
//   exception: 2.f4 itself costs ~0.6 by engine count — that IS the King's
//   Gambit; every line now ends within the 0.7 bar for White.
export default {
  slug: "kings-gambit",
  name: "King's Gambit",
  eco: "C30",
  playableColors: ["white"],
  detectionKeys: ["kings gambit", "king's gambit"],
  lines: [
    {
      rank: 1,
      name: "Accepted: Kieseritzky 4...g4",
      moves: [
        ["e4", "Take the center."],
        ["e5", "Symmetrical reply."],
        ["f4", "The King's Gambit: give a pawn to rip open the f-file."],
        ["exf4", "Accepting is the main move — Black takes the challenge."],
        ["Nf3", "The King's Knight Gambit: stop ...Qh4+ and develop."],
        ["g5", "The classical defense: hold f4 at any cost."],
        ["h4", "Undermine the chain immediately."],
        ["g4", "Push — the point of no return."],
        ["Ne5", "The Kieseritzky: the knight sits mightily in the center."],
        ["Nf6", "The modern main line: counterattack e4 at once."],
        ["d4", "Claim the center and open the c1 bishop toward f4."],
        ["d6", "Put the question to the proud knight."],
        ["Nd3", "The strange-looking retreat is the theory move: it eyes f4."],
        ["Nxe4", "Take the pawn — material honesty check for both sides."],
        ["Bxf4", "Regain the gambit pawn; development counts now."],
        ["Bg7", "The long diagonal is Black's whole game."],
        ["Nc3", "Challenge the strong e4 knight."],
        ["Nxc3", "Trade — retreating leaves White a free hand."],
        ["bxc3", "Recapture toward the center; the b-file opens too."],
        ["c5", "Strike at d4 — the main tabiya of the modern Kieseritzky."],
      ],
    },
    {
      rank: 2,
      name: "Accepted: Modern 3...d5",
      moves: [
        ["e4", "Take the center."],
        ["e5", "Symmetrical reply."],
        ["f4", "The King's Gambit."],
        ["exf4", "Accept."],
        ["Nf3", "The King's Knight Gambit."],
        ["d5", "The Modern Defense: give the pawn right back for free play."],
        ["exd5", "Take — declining concedes the center."],
        ["Nf6", "Develop and regain d5 with a piece, not the queen."],
        ["Bb5+", "The main line: trade off the c6 defender in advance."],
        ["c6", "Block and hit the bishop — the critical reply."],
        ["dxc6", "Take en route; the structure clarifies."],
        ["Nxc6", "Recapture with easy development for the pawn's return."],
        ["Nc3", "Develop — the initiative matters more than the f4 pawn."],
        ["Be6", "Develop and blunt any c4-diagonal ideas."],
        ["d4", "Claim the center; f4 will be rounded up in time."],
        ["Bd6", "Overprotect f4 and aim at h2 — Black's active setup."],
        ["Ne5", "Centralize, offering a trade White welcomes."],
        ["Bxe5", "Trade — letting the knight sit on e5 is worse."],
        ["dxe5", "Recapture with a cramping pawn; f4 finally falls next."],
        ["Qxd1+", "Trade queens — a level, honest endgame for both sides."],
      ],
    },
    {
      rank: 3,
      name: "Accepted: Fischer Defense 3...d6",
      moves: [
        ["e4", "Take the center."],
        ["e5", "Symmetrical reply."],
        ["f4", "The King's Gambit."],
        ["exf4", "Accept."],
        ["Nf3", "The King's Knight Gambit."],
        ["d6", "Fischer's 'bust': prepare ...g5 without allowing Ne5 ideas."],
        ["d4", "Take the center — the principled answer."],
        ["g5", "Hold f4 now that h4 lacks the Ne5 follow-up."],
        ["h4", "Challenge the chain anyway."],
        ["g4", "Push, as consistent as in the Kieseritzky..."],
        ["Ng1", "...but here the knight must go home — Fischer's whole point."],
        ["Bh6", "Guard the f4-g5 chain — Black keeps the material."],
        ["Ne2", "Redevelop against f4; the g1 detour cost real time."],
        ["Qf6", "Reinforce f4 again and eye d4."],
        ["Nbc3", "Develop with d5-jump ideas against the queen."],
        ["c6", "Deny d5 and keep the wall standing."],
        ["g3", "The thematic break: the f4 chain must be dissolved."],
        ["fxg3", "Take — holding everything is impossible now."],
        ["Nxg3", "Recapture with the knight, opening lines at last."],
        ["Bxc1", "Cash the dark-square bishops; material returns to balance."],
      ],
    },
    {
      rank: 4,
      name: "Bishop's Gambit: 3.Bc4",
      moves: [
        ["e4", "Take the center."],
        ["e5", "Symmetrical reply."],
        ["f4", "The King's Gambit."],
        ["exf4", "Accept."],
        ["Bc4", "The Bishop's Gambit: dare ...Qh4+ — the king walk is playable."],
        ["Nf6", "The modern refutation attempt: develop and hit e4 instead."],
        ["Nc3", "Defend e4 and develop."],
        ["c6", "Prepare ...d5 with full support — Black's main plan."],
        ["Bb3", "Step aside in advance; d5 is coming regardless."],
        ["d5", "The freeing break — Black returns the pawn for activity."],
        ["exd5", "Take — the structure battle begins."],
        ["cxd5", "Recapture, claiming central space."],
        ["d4", "Counter in the center immediately."],
        ["Bd6", "Guard f4 and develop actively."],
        ["Nge2", "Develop against f4 without blocking the f1 rook's future."],
        ["O-O", "Castle."],
        ["O-O", "White castles; the f4 pawn is surrounded."],
        ["Nc6", "Complete development, holding d4 tension."],
        ["Bxf4", "Regain the pawn at last."],
        ["Bxf4", "Trade; an open, balanced middlegame — Bishop's Gambit theory."],
      ],
    },
    {
      rank: 5,
      name: "Declined: Classical 2...Bc5",
      moves: [
        ["e4", "Take the center."],
        ["e5", "Symmetrical reply."],
        ["f4", "The King's Gambit."],
        ["Bc5", "The classical decline: the bishop forbids O-O forever."],
        ["Nf3", "Develop and defend against ...Qh4+ ideas."],
        ["d6", "Solidify e5 — the point of declining."],
        ["Nc3", "Develop; taking on e5 too early runs into ...Qd4 tricks."],
        ["Nf6", "Develop and pressure e4."],
        ["Bc4", "Natural development, mirroring the bishop."],
        ["Nc6", "Complete the knights; the position stays tense."],
        ["d3", "Support e4 and open the c1 bishop."],
        ["Bg4", "Pin the f3 knight — pressure against f4's support."],
        ["Na4", "The thematic hunt: remove the bishop that forbids O-O."],
        ["exf4", "Take while the knight is distracted."],
        ["Nxc5", "Complete the mission: the dark-square bishop falls."],
        ["dxc5", "Recapture; the d-file half-opens for Black's queen."],
        ["Bxf4", "Regain the pawn with the better structure."],
        ["O-O", "Black castles."],
        ["O-O", "Castle at last — the whole point of trading that bishop."],
        ["Nd4", "Centralize with tempo; a balanced middlegame follows."],
      ],
    },
    {
      rank: 6,
      name: "Falkbeer: 2...d5 3.exd5 e4",
      moves: [
        ["e4", "Take the center."],
        ["e5", "Symmetrical reply."],
        ["f4", "The King's Gambit."],
        ["d5", "The Falkbeer: counter-gambit in the center immediately."],
        ["exd5", "Accept — everything else concedes the center."],
        ["e4", "The classical point: the cramping pawn wedge on e4."],
        ["d3", "Undermine the wedge at once — the main line."],
        ["Nf6", "Develop and support e4."],
        ["dxe4", "Take; holding the wedge costs Black material."],
        ["Nxe4", "Recapture with an active knight."],
        ["Nf3", "Develop and cover the sensitive d4/e5 squares."],
        ["Bc5", "The active diagonal — f2 is the target."],
        ["Qe2", "Pin the e4 knight and prepare to castle long."],
        ["Bf5", "Support the knight and develop with threats."],
        ["Nc3", "Challenge the pinned knight — the critical moment."],
        ["Qe7", "Counter-pin: now everything on the e-file hangs together."],
        ["Be3", "Break the tension by offering the dark-square trade."],
        ["Nxc3", "The forcing sequence begins: take toward the queen trade."],
        ["Bxc5", "In-between: take the bishop with tempo on the queen."],
        ["Qxe2+", "Trade queens; after Bxe2 ...Nd7 regains the piece — dead level."],
      ],
    },
  ],
};
