export default {
  slug: "kings-indian",
  name: "King's Indian Defense",
  eco: "E60",
  playableColors: ["black", "white"],
  detectionKeys: ["kings indian defense", "king's indian defense"],
  lines: [
    {
      rank: 1,
      name: "Classical: Mar del Plata",
      moves: [
        ["d4", "White takes the center."],
        ["Nf6", "The Indian move: control e4 with a piece first."],
        ["c4", "White grabs more space."],
        ["g6", "The King's Indian: fianchetto and strike later."],
        ["Nc3", "Development."],
        ["Bg7", "The KID bishop."],
        ["e4", "White owns the full center — for now."],
        ["d6", "Restrain e5 and prepare ...e5."],
        ["Nf3", "The Classical System."],
        ["O-O", "Castle first — the structure fight comes next."],
        ["Be2", "Development."],
        ["e5", "The central strike that defines the KID."],
        ["O-O", "White castles, keeping the tension."],
        ["Nc6", "Pressure d4, forcing the decision."],
        ["d5", "White closes: the Mar del Plata race begins."],
        ["Ne7", "Reroute — the knight supports ...f5."],
        ["Ne1", "White reroutes too: f3 must be free for the f-pawn... and d3 beckons."],
        ["Nd7", "Clear f6 so the f-pawn can advance; cover c5 too."],
        ["Be3", "White prepares the c5 queenside break."],
        ["f5", "The storm begins: Black attacks the king, White the queenside."],
      ],
    },
    {
      rank: 2,
      name: "Sämisch Variation",
      moves: [
        ["d4", "White takes the center."],
        ["Nf6", "Indian development."],
        ["c4", "Space."],
        ["g6", "The KID."],
        ["Nc3", "Development."],
        ["Bg7", "The KID bishop."],
        ["e4", "Full center."],
        ["d6", "Restraint."],
        ["f3", "The Sämisch: a concrete wall behind which to attack."],
        ["O-O", "Castle and let White commit."],
        ["Be3", "Development toward Qd2/O-O-O."],
        ["e5", "The classical strike works here too."],
        ["d5", "White closes the center."],
        ["Nh5", "The point: with f3 played, ...Nh5-f4 and ...f5 come fast."],
        ["Qd2", "White connects for long castling."],
        ["f5", "The thematic break, gaining kingside space."],
        ["O-O-O", "Opposite wings: a pure attacking race."],
        ["Nd7", "Bring the last knight toward c5 and f6 duties."],
        ["exf5", "White trades to open lines for the g4 push."],
        ["gxf5", "Recapture toward the center, keeping the pawn mass rolling."],
      ],
    },
    {
      rank: 3,
      name: "Four Pawns Attack",
      moves: [
        ["d4", "White takes the center."],
        ["Nf6", "Indian development."],
        ["c4", "Space."],
        ["g6", "The KID."],
        ["Nc3", "Development."],
        ["Bg7", "The KID bishop."],
        ["e4", "Full center."],
        ["d6", "Restraint."],
        ["f4", "The Four Pawns: maximum ambition, maximum targets."],
        ["O-O", "Castle and prepare to strike the overextended wall."],
        ["Nf3", "Develop behind the pawns."],
        ["c5", "The correct break — hit d4 before the wall rolls."],
        ["d5", "White closes."],
        ["e6", "Undermine the new spearhead immediately."],
        ["Be2", "Development."],
        ["exd5", "Open the e-file at the right moment."],
        ["cxd5", "White keeps the center duo."],
        ["Re8", "The rook hits e4 — White's center is pinned down."],
        ["e5", "White lashes out — the critical, double-edged try."],
        ["dxe5", "Take; after fxe5 ...Ng4 the center falls under siege."],
      ],
    },
    {
      rank: 4,
      name: "Fianchetto Variation",
      moves: [
        ["d4", "White takes the center."],
        ["Nf6", "Indian development."],
        ["c4", "Space."],
        ["g6", "The KID."],
        ["Nf3", "White chooses the calm system."],
        ["Bg7", "The KID bishop."],
        ["g3", "The Fianchetto: White's bishop will blunt the g7 monster."],
        ["O-O", "Castle."],
        ["Bg2", "Complete the fianchetto."],
        ["d6", "The standard structure."],
        ["O-O", "White castles."],
        ["Nbd7", "Support ...e5 the flexible way."],
        ["Nc3", "Development complete."],
        ["e5", "The strike."],
        ["e4", "White claims the center fully, avoiding simplifications."],
        ["c6", "Give the queen b6 and prepare ...exd4 with ...d5 ideas."],
        ["h3", "Stop ...Ng4 and prepare Be3."],
        ["Qb6", "Hit d4 and b2 — awkward pressure against the fianchetto."],
        ["Re1", "Defend e4 laterally and support d4 tactics."],
        ["exd4", "Win the central skirmish — ...Nc5 and ...d5 follow."],
      ],
    },
  ],
};
