export default {
  slug: "london-system",
  name: "London System",
  eco: "D02",
  playableColors: ["white"],
  detectionKeys: ["london system"],
  lines: [
    {
      rank: 1,
      name: "Main Line vs ...c5/...e6",
      moves: [
        ["d4", "Take the center the queen's-pawn way."],
        ["d5", "Symmetrical reply."],
        ["Bf4", "The modern London move order: bishop out before Nf3."],
        ["Nf6", "Natural development."],
        ["e3", "Build the pyramid; the bishop is already outside it."],
        ["c5", "The main strike at d4."],
        ["c3", "Reinforce d4 — the London wall takes shape."],
        ["Nc6", "Develop and add pressure."],
        ["Nd2", "Flexible: support e4 ideas and keep f3 for the other knight."],
        ["e6", "Open the f8 bishop."],
        ["Ngf3", "Complete the classic London setup."],
        ["Bd6", "Challenge the strong f4 bishop."],
        ["Bg3", "Keep the bishop — trades ease Black's game."],
        ["O-O", "Black castles."],
        ["Bd3", "The attacking diagonal toward h7."],
        ["b6", "Prepare ...Bb7 and queenside play."],
        ["Ne5", "The thematic knight leap — the London's main attacking idea."],
        ["Bb7", "Complete development."],
        ["f4", "Cement the knight; the f1 rook joins after O-O."],
        ["Ne7", "Reroute to f5 to fight the coming attack."],
      ],
    },
    {
      rank: 2,
      name: "Poisoned Pawn: ...Qb6",
      moves: [
        ["d4", "Take the center."],
        ["d5", "Symmetrical reply."],
        ["Bf4", "The London bishop."],
        ["Nf6", "Natural development."],
        ["e3", "Build the pyramid."],
        ["c5", "Strike at d4."],
        ["c3", "Reinforce d4."],
        ["Qb6", "Target b2 — the bishop's departure left it tender."],
        ["Qb3", "The standard answer: offer the trade and hold b2."],
        ["Qxb3", "Trade — grabbing b2 instead is famously risky."],
        ["axb3", "Recapture opening the a-file; the doubled pawns control key squares."],
        ["cxd4", "Release the tension."],
        ["exd4", "Recapture, keeping the sturdy center."],
        ["Nc6", "Develop with pressure on d4."],
        ["Nf3", "Defend d4 and develop."],
        ["Bf5", "Active development before ...e6."],
        ["Nbd2", "Complete development, eyeing c4/e5."],
        ["e6", "Solidify."],
        ["Bb5", "Pin and pressure — White's endgame edge is tiny but real."],
        ["Bd6", "Offer the trade of dark-squared bishops."],
      ],
    },
    {
      rank: 3,
      name: "vs Fianchetto: ...g6",
      moves: [
        ["d4", "Take the center."],
        ["d5", "Symmetrical reply."],
        ["Bf4", "The London bishop."],
        ["Nf6", "Natural development."],
        ["e3", "Build the pyramid."],
        ["g6", "Black opts for a Grünfeld-like fianchetto."],
        ["Nf3", "Develop; the setup barely changes."],
        ["Bg7", "Complete the fianchetto."],
        ["Be2", "Modest: against ...g6 the bishop bites on granite at d3."],
        ["O-O", "Black castles."],
        ["h3", "Give the f4 bishop an h2 retreat from ...Nh5."],
        ["c5", "The standard break."],
        ["c3", "Hold d4 as always."],
        ["Nc6", "Develop."],
        ["O-O", "King safety."],
        ["b6", "Prepare ...Bb7 and a queenside squeeze."],
        ["Nbd2", "Finish development, ready for Ne5 or a4."],
        ["Bb7", "Complete the setup."],
        ["a4", "Gain space and probe the queenside dark squares."],
        ["a6", "Restrain a4-a5; a long maneuvering battle begins."],
      ],
    },
    {
      rank: 4,
      name: "Mirror: ...Bf5",
      moves: [
        ["d4", "Take the center."],
        ["d5", "Symmetrical reply."],
        ["Bf4", "The London bishop."],
        ["Nf6", "Natural development."],
        ["e3", "Build the pyramid."],
        ["Bf5", "Black copies the London setup."],
        ["Nf3", "Develop normally."],
        ["e6", "Solid structure."],
        ["Bd3", "Offer the trade — White gains time either way."],
        ["Bxd3", "Trade; declining loses a tempo to the offer."],
        ["Qxd3", "Recapture with a well-placed queen."],
        ["c6", "Solidify d5, Slav-style."],
        ["Nbd2", "Develop toward e5/c4."],
        ["Nbd7", "Black completes the mirror."],
        ["O-O", "King safety."],
        ["Be7", "Prepare to castle."],
        ["c4", "Break first — the tempo advantage means White opens on his terms."],
        ["O-O", "Black castles."],
        ["Rac1", "Take the file that is about to open."],
        ["Re8", "Black waits; White presses with a riskless initiative."],
      ],
    },
  ],
};
