// Sources (see README "Metodología de curaduría"):
//   Theory: Wikibooks "Chess Opening Theory" 1.d4 d5 2.Bf4 pages (consulted
//   2026-07-17) for the named systems (ECO D00-D02, A48).
//   Engine audit 2026-07-20 (Stockfish 17.1, scripts/audit-lines.mjs): rank 2
//   endgame tail fixed (the old 10.Bb5 Bd6?? hung a piece). Documented
//   exception: rank 2 keeps 6...Qxb3, the standard book reply (engine slightly
//   prefers 6...c4); the resulting endgame runs ~+0.9 for White, which is the
//   teaching point of the line in a White-only opening.
export default {
  slug: "london-system",
  name: "London System",
  eco: "D02",
  playableColors: ["white"],
  detectionKeys: ["london system"],
  lines: [
    {
      rank: 1,
      name: "Main Line vs ...c5/...e6",
      moves: [
        ["d4", "Take the center the queen's-pawn way."],
        ["d5", "Symmetrical reply."],
        ["Bf4", "The modern London move order: bishop out before Nf3."],
        ["Nf6", "Natural development."],
        ["e3", "Build the pyramid; the bishop is already outside it."],
        ["c5", "The main strike at d4."],
        ["c3", "Reinforce d4 — the London wall takes shape."],
        ["Nc6", "Develop and add pressure."],
        ["Nd2", "Flexible: support e4 ideas and keep f3 for the other knight."],
        ["e6", "Open the f8 bishop."],
        ["Ngf3", "Complete the classic London setup."],
        ["Bd6", "Challenge the strong f4 bishop."],
        ["Bg3", "Keep the bishop — trades ease Black's game."],
        ["O-O", "Black castles."],
        ["Bd3", "The attacking diagonal toward h7."],
        ["b6", "Prepare ...Bb7 and queenside play."],
        ["Ne5", "The thematic knight leap — the London's main attacking idea."],
        ["Bb7", "Complete development."],
        ["f4", "Cement the knight; the f1 rook joins after O-O."],
        ["Ne7", "Reroute to f5 to fight the coming attack."],
      ],
    },
    {
      rank: 2,
      name: "Poisoned Pawn: ...Qb6",
      moves: [
        ["d4", "Take the center."],
        ["d5", "Symmetrical reply."],
        ["Bf4", "The London bishop."],
        ["Nf6", "Natural development."],
        ["e3", "Build the pyramid."],
        ["c5", "Strike at d4."],
        ["c3", "Reinforce d4."],
        ["Qb6", "Target b2 — the bishop's departure left it tender."],
        ["Qb3", "The standard answer: offer the trade and hold b2."],
        ["Qxb3", "Trade — grabbing b2 instead is famously risky."],
        ["axb3", "Recapture opening the a-file; the doubled pawns control key squares."],
        ["cxd4", "Release the tension."],
        ["exd4", "Recapture, keeping the sturdy center."],
        ["Nc6", "Develop with pressure on d4."],
        ["Nf3", "Defend d4 and develop."],
        ["Bf5", "Active development before ...e6."],
        ["Nbd2", "Complete development, eyeing c4/e5."],
        ["e6", "Solidify."],
        ["Bb5", "Pin and press — every trade highlights the b6/c6 squares."],
        ["Nd7", "Cover the e5 hop; White keeps a pleasant riskless pull."],
      ],
    },
    {
      rank: 3,
      name: "vs Fianchetto: ...g6",
      moves: [
        ["d4", "Take the center."],
        ["d5", "Symmetrical reply."],
        ["Bf4", "The London bishop."],
        ["Nf6", "Natural development."],
        ["e3", "Build the pyramid."],
        ["g6", "Black opts for a Grünfeld-like fianchetto."],
        ["Nf3", "Develop; the setup barely changes."],
        ["Bg7", "Complete the fianchetto."],
        ["Be2", "Modest: against ...g6 the bishop bites on granite at d3."],
        ["O-O", "Black castles."],
        ["h3", "Give the f4 bishop an h2 retreat from ...Nh5."],
        ["c5", "The standard break."],
        ["c3", "Hold d4 as always."],
        ["Nc6", "Develop."],
        ["O-O", "King safety."],
        ["b6", "Prepare ...Bb7 and a queenside squeeze."],
        ["Nbd2", "Finish development, ready for Ne5 or a4."],
        ["Bb7", "Complete the setup."],
        ["a4", "Gain space and probe the queenside dark squares."],
        ["a6", "Restrain a4-a5; a long maneuvering battle begins."],
      ],
    },
    {
      rank: 4,
      name: "Mirror: ...Bf5",
      moves: [
        ["d4", "Take the center."],
        ["d5", "Symmetrical reply."],
        ["Bf4", "The London bishop."],
        ["Nf6", "Natural development."],
        ["e3", "Build the pyramid."],
        ["Bf5", "Black copies the London setup."],
        ["Nf3", "Develop normally."],
        ["e6", "Solid structure."],
        ["Bd3", "Offer the trade — White gains time either way."],
        ["Bxd3", "Trade; declining loses a tempo to the offer."],
        ["Qxd3", "Recapture with a well-placed queen."],
        ["c6", "Solidify d5, Slav-style."],
        ["Nbd2", "Develop toward e5/c4."],
        ["Nbd7", "Black completes the mirror."],
        ["O-O", "King safety."],
        ["Be7", "Prepare to castle."],
        ["c4", "Break first — the tempo advantage means White opens on his terms."],
        ["O-O", "Black castles."],
        ["Rac1", "Take the file that is about to open."],
        ["Re8", "Black waits; White presses with a riskless initiative."],
      ],
    },
    {
      rank: 5,
      name: "Steinitz Countergambit: 2...c5",
      moves: [
        ["d4", "Take the center."],
        ["d5", "Symmetrical reply."],
        ["Bf4", "The London bishop."],
        ["c5", "The immediate countergambit: hit d4 before White sets the wall."],
        ["e3", "Decline calmly and keep the structure — taking helps Black."],
        ["Nc6", "Develop with pressure on d4."],
        ["c3", "The wall, as always."],
        ["Nf6", "Natural development."],
        ["Nd2", "Flexible London development, holding e4 and c4 ideas."],
        ["Bf5", "Grab the good diagonal before ...e6 closes it."],
        ["Ngf3", "Complete the setup."],
        ["Qb6", "The point of Black's order: b2 is attacked and Qb3 is harder now."],
        ["Qb3", "Offer the trade anyway — the endgame slightly favors White."],
        ["c4", "Black declines with tempo: hit the queen and clamp the queenside."],
        ["Qxb6", "Trade on White's terms before ...Qxb3 doubles White's pawns."],
        ["axb6", "Recapture; the open a-file and b6 targets are the trade-off."],
        ["Be2", "Develop and prepare O-O; the c4 pawn cramps White slightly."],
        ["e6", "Solidify and open the f8 bishop."],
        ["O-O", "King safety."],
        ["Be7", "Complete development — a subtle, balanced endgame battle."],
      ],
    },
    {
      rank: 6,
      name: "vs King's Indian: ...g6 & ...d6",
      moves: [
        ["d4", "Take the center."],
        ["Nf6", "The Indian move order — no early ...d5."],
        ["Bf4", "The London works against nearly everything — play it anyway."],
        ["g6", "Black sets up a King's Indian structure."],
        ["e3", "The usual pyramid."],
        ["Bg7", "The KID bishop."],
        ["Nf3", "Develop."],
        ["d6", "The KID point: prepare ...e5 against the London wall."],
        ["h3", "Secure h2 for the bishop before ...Nh5 or ...e5 tricks."],
        ["O-O", "Black castles."],
        ["Be2", "Modest and correct: d3 would bite on granite against ...g6."],
        ["c5", "Strike at d4 — the alternative plan to ...e5."],
        ["c3", "Hold the wall."],
        ["Nc6", "Develop and keep asking about d4."],
        ["O-O", "King safety."],
        ["b6", "Prepare ...Bb7 for the long-diagonal battle."],
        ["Nbd2", "Complete the setup; a4 and Ne5 are the active tries."],
        ["Bb7", "Complete development."],
        ["a4", "Gain space and threaten a5 against the b6 chain."],
        ["a6", "Restrain it — a long maneuvering game, London-style."],
      ],
    },
  ],
};
