// Sources (see README "Metodología de curaduría"):
//   Theory: standard published theory for the named systems, cross-checked
//   against Wikibooks "Chess Opening Theory" (consulted 2026-07-17). ECO B06/B09.
//   Engine audit 2026-07-20 (Stockfish 17.1, scripts/audit-lines.mjs): rank 2
//   rebuilt on the Austrian main line 4...Nf6 5.Nf3 c5 6.Bb5+ (the old ...a6/b5
//   setup left Black at -0.8 or worse); ranks 3-6 tails rebuilt along
//   engine-approved play. The Modern concedes ~+0.4/+0.6 to White in every
//   line — that is its nature; all finals now sit inside the 0.7 bar at depth 20.
export default {
  slug: "modern-defense",
  name: "Modern Defense",
  eco: "B06",
  playableColors: ["black"],
  detectionKeys: ["modern defense", "robatsch"],
  lines: [
    {
      rank: 1,
      name: "Tiger's Modern: ...a6",
      moves: [
        ["e4", "White takes the center."],
        ["g6", "The Modern: concede the center now, attack it later."],
        ["d4", "White grabs the full center."],
        ["Bg7", "The fianchetto — this bishop defines the opening."],
        ["Nc3", "Natural development."],
        ["d6", "Restrain e5 and open the c8 bishop."],
        ["Be3", "White builds a Qd2/O-O-O attacking setup."],
        ["a6", "Tiger's Modern: prepare ...b5 and deny b5 to White's pieces."],
        ["Nf3", "Develop."],
        ["b5", "Queenside space — Black plays on the flank, not the center."],
        ["Bd3", "Complete development."],
        ["Bb7", "The second fianchetto pressures e4."],
        ["O-O", "White castles short after all."],
        ["Nd7", "Flexible: support ...c5 or ...e5 breaks."],
        ["a4", "White strikes at the pawn chain."],
        ["b4", "Advance — closing lines toward Black's own queenside."],
        ["Ne2", "Reroute toward the kingside or d4 support."],
        ["c5", "The thematic break arrives at the right moment."],
        ["c3", "White fights for the dark squares."],
        ["bxc3", "Trade, opening the b-file for the rook."],
      ],
    },
    {
      rank: 2,
      name: "Austrian Attack: 4.f4",
      moves: [
        ["e4", "White takes the center."],
        ["g6", "The Modern."],
        ["d4", "Full center."],
        ["Bg7", "The fianchetto."],
        ["Nc3", "Development."],
        ["d6", "Restrain e5."],
        ["f4", "The Austrian Attack: maximum central ambition."],
        ["Nf6", "Develop and hit e4 — the most reliable answer."],
        ["Nf3", "Develop behind the pawn wall."],
        ["c5", "The classical counter: strike d4 before the wall rolls."],
        ["Bb5+", "The main line: trade the defender of the queenside squares."],
        ["Bd7", "The natural block."],
        ["e5", "Push with tempo — the critical try."],
        ["Ng4", "Sidestep, keeping the knight active toward e3/f2."],
        ["Bxd7+", "Resolve the check trade first."],
        ["Qxd7", "Recapture; ...cxd4 and ...dxe5 both loom."],
        ["d5", "Keep lines closed and space intact."],
        ["dxe5", "Undermine the spearhead at once."],
        ["h3", "Put the question to the g4 knight."],
        ["e4", "The tactical point: push with tempo — hxg4 fails to ...exf3."],
      ],
    },
    {
      rank: 3,
      name: "3.c4: King's Indian Style",
      moves: [
        ["e4", "White takes the center."],
        ["g6", "The Modern."],
        ["d4", "Full center."],
        ["Bg7", "The fianchetto."],
        ["c4", "White grabs even more space — a KID structure beckons."],
        ["d6", "Standard restraint."],
        ["Nc3", "Development."],
        ["e5", "Stake the central claim immediately."],
        ["d5", "White closes the center — now it's a pure KID battle."],
        ["Nd7", "Flexible: the knight heads for c5, the dream blockade square."],
        ["Bd3", "Develop, watching the f5 square."],
        ["Ngf6", "Complete the kingside development."],
        ["Be3", "Solid development behind the pawn chain."],
        ["a5", "Anchor the coming ...Nc5 against b4 forever."],
        ["f3", "Cover e4 and prepare queenside expansion."],
        ["Nc5", "The knight arrives — e4 is pinned down for good."],
        ["Nge2", "Develop around the committed f3 pawn."],
        ["Nfd7", "Double on the blockade: ...Nb6 and ...f5 are both coming."],
        ["Bc2", "Keep the bishop pair pointed at the queenside."],
        ["Nb6", "Hit c4 and clamp a4 — full-fledged Modern counterplay."],
      ],
    },
    {
      rank: 4,
      name: "Classical: 4.Nf3 c6",
      moves: [
        ["e4", "White takes the center."],
        ["g6", "The Modern."],
        ["d4", "Full center."],
        ["Bg7", "The fianchetto."],
        ["Nc3", "Development."],
        ["d6", "Standard restraint."],
        ["Nf3", "The classical treatment: simple development."],
        ["c6", "Flexible: support ...b5 and ...d5 ideas, give the queen c7."],
        ["Bd3", "Develop, keeping e2 free for the knight reroute."],
        ["Bg4", "Solve the problem bishop actively, pinning f3."],
        ["Be3", "Support d4 against the coming ...e5."],
        ["Nd7", "Prepare ...e5 in earnest."],
        ["Qd2", "Connect the queens' wing and keep O-O-O options."],
        ["Ngf6", "Full development; e4 feels the pressure."],
        ["h4", "The typical spearhead against the fianchetto."],
        ["e5", "The central break, right on time."],
        ["dxe5", "Trade — keeping the tension now favors Black."],
        ["dxe5", "Recapture toward the center; the d-file opens evenly."],
        ["Bc4", "Reroute against f7 — on d3 the bishop bit on granite."],
        ["Bxf3", "Trade the pinned knight; after gxf3 the structure cracks — balanced."],
      ],
    },
    {
      rank: 5,
      name: "Fianchetto: 4.g3",
      moves: [
        ["e4", "White takes the center."],
        ["g6", "The Modern."],
        ["d4", "Full center."],
        ["Bg7", "The fianchetto."],
        ["Nc3", "Development."],
        ["d6", "Standard restraint."],
        ["g3", "The positional treatment: mirror the fianchetto, deny targets."],
        ["Nc6", "Provoke d5 or win the d4/e5 tension battle."],
        ["Be3", "Hold d4 and keep the structure flexible."],
        ["e5", "Stake the central claim before White finishes."],
        ["d5", "Close, gaining space and shutting the g7 bishop's file."],
        ["Nce7", "Standard KID-style regrouping toward f5/g6."],
        ["h4", "Strike at the fianchetto immediately — the critical try."],
        ["h5", "The standard brake, fixing h4 before it rolls."],
        ["Qd2", "Connect for O-O-O; the dark squares are the battleground."],
        ["Nf6", "Develop, covering g4 and eyeing e4."],
        ["Bg5", "Pin and probe — provoke a concession around the king."],
        ["a6", "Start the counter-race: ...b5 comes with tempo."],
        ["O-O-O", "Commit to opposite wings at full speed."],
        ["b5", "The avalanche arrives; both plans are fully loaded."],
      ],
    },
    {
      rank: 6,
      name: "Pseudo-Yugoslav: ...c6 & ...b5",
      moves: [
        ["e4", "White takes the center."],
        ["g6", "The Modern."],
        ["d4", "Full center."],
        ["Bg7", "The fianchetto."],
        ["Nc3", "Development."],
        ["c6", "The flexible move order: ...b5 comes before ...Nf6 exists to be hit."],
        ["Be3", "The Yugoslav-style setup: Qd2, f3 and O-O-O are the plan."],
        ["d6", "Standard restraint, transposing structures."],
        ["Qd2", "Connect for O-O-O and eye h6."],
        ["b5", "The point of ...c6: expansion with tempo-free support."],
        ["f3", "Cover e4 and prepare the g4/h4 storm."],
        ["Nd7", "Develop, keeping the g8 knight for f6 or h6 duty."],
        ["h4", "Start the storm before Black's arrives."],
        ["h5", "The standard brake: fix h4 and deny g4 its full force."],
        ["Nh3", "Reroute — the g5 outpost is the new target."],
        ["Ngf6", "Complete development, covering g4 and e4-jumps."],
        ["O-O-O", "Commit: opposite wings, full-speed attacks."],
        ["Qa5", "The counterattack arrives with tempo threats on a2/c3."],
        ["Kb1", "The standard prophylactic sidestep."],
        ["b4", "Throw the pawn forward with tempo — the race is fully on."],
      ],
    },
  ],
};
