export default {
  slug: "modern-defense",
  name: "Modern Defense",
  eco: "B06",
  playableColors: ["black"],
  detectionKeys: ["modern defense", "robatsch"],
  lines: [
    {
      rank: 1,
      name: "Tiger's Modern: ...a6",
      moves: [
        ["e4", "White takes the center."],
        ["g6", "The Modern: concede the center now, attack it later."],
        ["d4", "White grabs the full center."],
        ["Bg7", "The fianchetto — this bishop defines the opening."],
        ["Nc3", "Natural development."],
        ["d6", "Restrain e5 and open the c8 bishop."],
        ["Be3", "White builds a Qd2/O-O-O attacking setup."],
        ["a6", "Tiger's Modern: prepare ...b5 and deny b5 to White's pieces."],
        ["Nf3", "Develop."],
        ["b5", "Queenside space — Black plays on the flank, not the center."],
        ["Bd3", "Complete development."],
        ["Bb7", "The second fianchetto pressures e4."],
        ["O-O", "White castles short after all."],
        ["Nd7", "Flexible: support ...c5 or ...e5 breaks."],
        ["a4", "White strikes at the pawn chain."],
        ["b4", "Advance — closing lines toward Black's own queenside."],
        ["Ne2", "Reroute toward the kingside or d4 support."],
        ["c5", "The thematic break arrives at the right moment."],
        ["c3", "White fights for the dark squares."],
        ["bxc3", "Trade, opening the b-file for the rook."],
      ],
    },
    {
      rank: 2,
      name: "Austrian Attack: 4.f4",
      moves: [
        ["e4", "White takes the center."],
        ["g6", "The Modern."],
        ["d4", "Full center."],
        ["Bg7", "The fianchetto."],
        ["Nc3", "Development."],
        ["d6", "Restrain e5."],
        ["f4", "The Austrian Attack: maximum central ambition."],
        ["a6", "Stay flexible; the counterattack comes with ...b5."],
        ["Nf3", "Develop behind the pawn wall."],
        ["b5", "Gain space and threaten ...b4."],
        ["Bd3", "Develop and defend e4."],
        ["Nd7", "Develop, holding the e5/c5 breaks in reserve."],
        ["e5", "White pushes — the wall advances."],
        ["dxe5", "Trade at the right moment to loosen the wall."],
        ["fxe5", "White keeps the spearhead."],
        ["c5", "Now undermine d4 while it lacks pawn support."],
        ["dxc5", "White grabs, but the center dissolves."],
        ["Nxc5", "Recapture with tempo on the d3 bishop."],
        ["O-O", "White castles at last."],
        ["Nxd3", "Win the bishop pair — Black's strategy has paid off."],
      ],
    },
    {
      rank: 3,
      name: "3.c4: King's Indian Style",
      moves: [
        ["e4", "White takes the center."],
        ["g6", "The Modern."],
        ["d4", "Full center."],
        ["Bg7", "The fianchetto."],
        ["c4", "White grabs even more space — a KID structure beckons."],
        ["d6", "Standard restraint."],
        ["Nc3", "Development."],
        ["e5", "Stake the central claim immediately."],
        ["d5", "White closes the center — now it's a pure KID battle."],
        ["Ne7", "Develop toward f5 without blocking the f-pawn... via e7."],
        ["Bd3", "Develop, watching the f5 square."],
        ["O-O", "King safety before the pawn storms."],
        ["Nge2", "White completes development flexibly."],
        ["f5", "The thematic KID break — Black's whole game is here."],
        ["exf5", "White trades to keep e4 for the pieces."],
        ["gxf5", "Recapture toward the center, opening the g-file too."],
        ["f4", "White blocks the pawn mass."],
        ["e4", "Push through with tempo on the d3 bishop."],
        ["Bc2", "Retreat, keeping the b1-h7 diagonal."],
        ["Nd7", "The knight heads for the dream c5/e5 squares."],
      ],
    },
    {
      rank: 4,
      name: "Classical: 4.Nf3 c6",
      moves: [
        ["e4", "White takes the center."],
        ["g6", "The Modern."],
        ["d4", "Full center."],
        ["Bg7", "The fianchetto."],
        ["Nc3", "Development."],
        ["d6", "Standard restraint."],
        ["Nf3", "The classical treatment: simple development."],
        ["c6", "Flexible: support ...b5 and ...d5 ideas, give the queen c7."],
        ["Bd3", "Develop, keeping e2 free for the knight reroute."],
        ["b5", "Queenside expansion, the Modern's trademark."],
        ["O-O", "White castles."],
        ["Nd7", "Develop, keeping the g8 knight flexible."],
        ["a4", "White probes the advanced pawn."],
        ["b4", "Advance rather than concede the file."],
        ["Ne2", "Reroute toward g3/d4."],
        ["Ngf6", "Finally develop, hitting e4."],
        ["Ng3", "Cover e4 and prepare kingside play."],
        ["O-O", "King safety."],
        ["a5", "White fixes the queenside — space vs. flexibility."],
        ["Qc7", "Connect and eye e5; a rich maneuvering game unfolds."],
      ],
    },
  ],
};
