// Each move is [san, explanation]. Plies alternate White/Black starting with White.
// Sources (see README "Metodología de curaduría"):
//   Theory: Wikibooks "Chess Opening Theory" 1.e4 e5 2.Nf3 Nc6 3.c3 pages
//   (consulted 2026-07-17) for the named variations (ECO C44).
//   Engine audit 2026-07-20 (Stockfish 17.1, scripts/audit-lines.mjs): line
//   tails rebuilt where the old "natural-play" extensions dropped material or
//   misplayed the resulting middlegames (ranks 2, 4, 5, 6). Known engine
//   quibbles kept on purpose: 3.c3 itself (~-0.6, the opening's defining move)
//   and 4...Ne7 in rank 1 (the documented book move). The Jaenisch (rank 2)
//   honestly ends ~-0.5 for White — it is Black's best answer to the Ponziani.
export default {
  slug: "ponziani",
  name: "Ponziani Opening",
  eco: "C44",
  playableColors: ["white"],
  detectionKeys: ["ponziani"],
  lines: [
    {
      rank: 1,
      name: "Main Line: 3...Nf6 4.d4",
      moves: [
        ["e4", "Claim the center and open lines for the bishop and queen."],
        ["e5", "Black stakes an equal claim in the center."],
        ["Nf3", "Develop with tempo, attacking the e5 pawn."],
        ["Nc6", "Defend e5 while developing a piece."],
        ["c3", "The Ponziani: prepare d4 with full pawn support."],
        ["Nf6", "Counterattack e4 instead of defending passively."],
        ["d4", "Build the big center; c3 backs it up."],
        ["Nxe4", "Grab the pawn — the critical test of the Ponziani."],
        ["d5", "Push the knight question: c6 must move and e4 stays loose."],
        ["Ne7", "Retreat toward g6 to hit the e5 fork ideas."],
        ["Nxe5", "Win the pawn back with a strong central knight."],
        ["Ng6", "Challenge the e5 knight immediately."],
        ["Qd4", "Centralize: defend e5 and attack the e4 knight at once."],
        ["Qf6", "Pile on e5 and offer to trade the attacked knight."],
        ["Qxe4", "Collect the knight; material is even with a space edge."],
        ["Qxe5", "Black regains the piece by taking the knight."],
        ["Qxe5+", "Trade into a pleasant queenless middlegame with check."],
        ["Nxe5", "Recapture; the knight is fine on e5 for now."],
        ["Bf4", "Develop with tempo against the e5 knight."],
        ["d6", "Solidify the knight and free the c8 bishop."],
      ],
    },
    {
      rank: 2,
      name: "Jaenisch Counterattack: 3...d5",
      moves: [
        ["e4", "Take the center."],
        ["e5", "Symmetrical reply."],
        ["Nf3", "Attack e5 and develop."],
        ["Nc6", "Defend e5."],
        ["c3", "Prepare the d4 break."],
        ["d5", "The critical counter: strike e4 while c3 blocks the knight's defense."],
        ["Qa4", "The point: pin the c6 knight against the loose e5/d5 complex."],
        ["f6", "Bolster e5 since the c6 knight is pinned."],
        ["Bb5", "Add pressure on c6 and prepare to castle."],
        ["Ne7", "Break the pin's pressure by covering c6 again."],
        ["exd5", "Win a central pawn while Black is tangled up."],
        ["Qxd5", "Recapture; the queen is active but exposed."],
        ["O-O", "Get the king safe before opening the center."],
        ["e4", "Push with tempo on the knight — Black's most testing try."],
        ["Nd4", "Jump to the strong central square rather than retreat."],
        ["Bd7", "Break the pin so ...Nxd4 becomes a real threat."],
        ["d3", "Challenge the advanced pawn before Black consolidates."],
        ["exd3", "Trade — holding e4 outright costs material."],
        ["Bxd3", "Recapture; both white bishops now eye the kingside."],
        ["O-O-O", "Black castles long with active pieces — the critical battleground."],
      ],
    },
    {
      rank: 3,
      name: "3...Nf6 4.d4 exd4",
      moves: [
        ["e4", "Take the center."],
        ["e5", "Symmetrical reply."],
        ["Nf3", "Attack e5 and develop."],
        ["Nc6", "Defend e5."],
        ["c3", "Prepare d4."],
        ["Nf6", "Develop and hit e4."],
        ["d4", "Seize the center."],
        ["exd4", "Trade rather than let White keep the full pawn duo."],
        ["e5", "Kick the f6 knight before recapturing on d4."],
        ["Nd5", "The best square: centralized and hard to evict."],
        ["cxd4", "Restore material with a strong pawn pair on d4/e5."],
        ["d6", "Challenge the e5 spearhead immediately."],
        ["Bb5", "Pin the c6 knight and prepare to castle."],
        ["Bd7", "Break the pin calmly."],
        ["exd6", "Resolve the tension and open lines while ahead in development."],
        ["Bxd6", "Recapture with the bishop, finishing development."],
        ["O-O", "King safety first."],
        ["O-O", "Black castles too; the position is roughly level but easier for White."],
        ["Nc3", "Develop with tempo, challenging the strong d5 knight."],
        ["Nxc3", "Trade before the knight gets kicked by Ne4 ideas."],
      ],
    },
    {
      rank: 4,
      name: "Passive Setup: 3...d6",
      moves: [
        ["e4", "Take the center."],
        ["e5", "Symmetrical reply."],
        ["Nf3", "Attack e5 and develop."],
        ["Nc6", "Defend e5."],
        ["c3", "Prepare d4."],
        ["d6", "A solid but passive way to hold e5."],
        ["d4", "Take the center for free — this is why 3...d6 is harmless."],
        ["Nf6", "Develop and eye e4."],
        ["Bd3", "Modest but flexible: defend e4 and prepare O-O."],
        ["g6", "Black opts for a fianchetto setup."],
        ["O-O", "Castle while holding the strong center."],
        ["Bg7", "Complete the fianchetto."],
        ["Re1", "Support e4 and prepare central expansion."],
        ["O-O", "Black castles."],
        ["h3", "Deny g4 to the bishop and knight — a useful waiting move."],
        ["Re8", "Put the rook opposite the white queen and e-pawns."],
        ["Nbd2", "Develop the last minor piece, keeping c3 for the pawn."],
        ["exd4", "Release the tension to free Black's game."],
        ["cxd4", "Recapture, keeping the ideal pawn duo on d4/e4."],
        ["a5", "Grab queenside space and restrain b4; White keeps the freer game."],
      ],
    },
    {
      rank: 5,
      name: "Caro Gambit: 3...d5 4.Qa4 Bd7",
      moves: [
        ["e4", "Take the center."],
        ["e5", "Symmetrical reply."],
        ["Nf3", "Attack e5 and develop."],
        ["Nc6", "Defend e5."],
        ["c3", "Prepare the d4 break."],
        ["d5", "The critical counter, striking e4."],
        ["Qa4", "The point of the Ponziani: pin the c6 knight."],
        ["Bd7", "The Caro Gambit: calmly break the pin and offer e5."],
        ["exd5", "Take the center pawn while the offer stands."],
        ["Nd4", "The trick: the 'pinned' knight jumps — ...Nc2+ forking is the threat."],
        ["Qd1", "Retreat and cover c2; Qxd7+ loses the queen to ...Qxd7."],
        ["Nxf3+", "Trade off the defender of e5 and d4."],
        ["Qxf3", "Recapture; White is a pawn up but behind in development."],
        ["Nf6", "Develop with pressure on d5."],
        ["Bc4", "Hold the extra d5 pawn the natural way."],
        ["Bd6", "Aim at h2 and prepare ...O-O — full compensation play."],
        ["d3", "Open the c1 bishop and solidify."],
        ["O-O", "King safety; Black's activity balances the pawn."],
        ["Bg5", "Pin the f6 knight — the extra d5 pawn stays protected."],
        ["b5", "Expand with tempo on the bishop; activity is the compensation."],
      ],
    },
    {
      rank: 6,
      name: "Leonhardt: 3...d5 4.Qa4 Nf6",
      moves: [
        ["e4", "Take the center."],
        ["e5", "Symmetrical reply."],
        ["Nf3", "Attack e5 and develop."],
        ["Nc6", "Defend e5."],
        ["c3", "Prepare the d4 break."],
        ["d5", "The critical counter."],
        ["Qa4", "Pin the c6 knight against e5/d5."],
        ["Nf6", "The Leonhardt: develop and ignore the threat — a true gambit."],
        ["Nxe5", "Call the bluff: take, exploiting the pinned defender."],
        ["Nxe4", "Grab the pawn back in kind, keeping maximum activity."],
        ["Nxc6", "Win the tangled knight before Black consolidates."],
        ["bxc6", "Recapture, opening the b-file for counterplay."],
        ["Qxc6+", "Collect a second pawn with check — the punishing continuation."],
        ["Bd7", "Block and develop with tempo on the queen."],
        ["Qxd5", "Take a third pawn — greedy but theory approves."],
        ["Nf6", "Hit the queen again; Black plays for raw initiative."],
        ["Qd3", "Step back to safety, ready to return material for development."],
        ["Bd6", "Point everything at the kingside."],
        ["Qe3+", "Force the king to move — two pawns up, White gladly trades time for structure."],
        ["Kf8", "Forced sidestep; Black banks everything on the development lead."],
      ],
    },
  ],
};
