// Each move is [san, explanation]. Plies alternate White/Black starting with White.
export default {
  slug: "ponziani",
  name: "Ponziani Opening",
  eco: "C44",
  playableColors: ["white"],
  detectionKeys: ["ponziani"],
  lines: [
    {
      rank: 1,
      name: "Main Line: 3...Nf6 4.d4",
      moves: [
        ["e4", "Claim the center and open lines for the bishop and queen."],
        ["e5", "Black stakes an equal claim in the center."],
        ["Nf3", "Develop with tempo, attacking the e5 pawn."],
        ["Nc6", "Defend e5 while developing a piece."],
        ["c3", "The Ponziani: prepare d4 with full pawn support."],
        ["Nf6", "Counterattack e4 instead of defending passively."],
        ["d4", "Build the big center; c3 backs it up."],
        ["Nxe4", "Grab the pawn — the critical test of the Ponziani."],
        ["d5", "Push the knight question: c6 must move and e4 stays loose."],
        ["Ne7", "Retreat toward g6 to hit the e5 fork ideas."],
        ["Nxe5", "Win the pawn back with a strong central knight."],
        ["Ng6", "Challenge the e5 knight immediately."],
        ["Qd4", "Centralize: defend e5 and attack the e4 knight at once."],
        ["Qf6", "Pile on e5 and offer to trade the attacked knight."],
        ["Qxe4", "Collect the knight; material is even with a space edge."],
        ["Qxe5", "Black regains the piece by taking the knight."],
        ["Qxe5+", "Trade into a pleasant queenless middlegame with check."],
        ["Nxe5", "Recapture; the knight is fine on e5 for now."],
        ["Bf4", "Develop with tempo against the e5 knight."],
        ["d6", "Solidify the knight and free the c8 bishop."],
      ],
    },
    {
      rank: 2,
      name: "Jaenisch Counterattack: 3...d5",
      moves: [
        ["e4", "Take the center."],
        ["e5", "Symmetrical reply."],
        ["Nf3", "Attack e5 and develop."],
        ["Nc6", "Defend e5."],
        ["c3", "Prepare the d4 break."],
        ["d5", "The critical counter: strike e4 while c3 blocks the knight's defense."],
        ["Qa4", "The point: pin the c6 knight against the loose e5/d5 complex."],
        ["f6", "Bolster e5 since the c6 knight is pinned."],
        ["Bb5", "Add pressure on c6 and prepare to castle."],
        ["Ne7", "Break the pin's pressure by covering c6 again."],
        ["exd5", "Win a central pawn while Black is tangled up."],
        ["Qxd5", "Recapture; the queen is active but exposed."],
        ["O-O", "Get the king safe before opening the center."],
        ["Bd7", "Unpin the c6 knight and connect the queenside."],
        ["d4", "Open the center against the centralized black queen."],
        ["e4", "Black closes the center to blunt the initiative."],
        ["Nfd2", "Reroute: the knight will hit e4 with f3 or Nc4."],
        ["f5", "Support e4 and grab kingside space."],
        ["f3", "Undermine the e4 pawn chain at its head."],
        ["exf3", "Concede the center pawn to avoid losing it outright."],
      ],
    },
    {
      rank: 3,
      name: "3...Nf6 4.d4 exd4",
      moves: [
        ["e4", "Take the center."],
        ["e5", "Symmetrical reply."],
        ["Nf3", "Attack e5 and develop."],
        ["Nc6", "Defend e5."],
        ["c3", "Prepare d4."],
        ["Nf6", "Develop and hit e4."],
        ["d4", "Seize the center."],
        ["exd4", "Trade rather than let White keep the full pawn duo."],
        ["e5", "Kick the f6 knight before recapturing on d4."],
        ["Nd5", "The best square: centralized and hard to evict."],
        ["cxd4", "Restore material with a strong pawn pair on d4/e5."],
        ["d6", "Challenge the e5 spearhead immediately."],
        ["Bb5", "Pin the c6 knight and prepare to castle."],
        ["Bd7", "Break the pin calmly."],
        ["exd6", "Resolve the tension and open lines while ahead in development."],
        ["Bxd6", "Recapture with the bishop, finishing development."],
        ["O-O", "King safety first."],
        ["O-O", "Black castles too; the position is roughly level but easier for White."],
        ["Nc3", "Develop with tempo, challenging the strong d5 knight."],
        ["Nxc3", "Trade before the knight gets kicked by Ne4 ideas."],
      ],
    },
    {
      rank: 4,
      name: "Passive Setup: 3...d6",
      moves: [
        ["e4", "Take the center."],
        ["e5", "Symmetrical reply."],
        ["Nf3", "Attack e5 and develop."],
        ["Nc6", "Defend e5."],
        ["c3", "Prepare d4."],
        ["d6", "A solid but passive way to hold e5."],
        ["d4", "Take the center for free — this is why 3...d6 is harmless."],
        ["Nf6", "Develop and eye e4."],
        ["Bd3", "Modest but flexible: defend e4 and prepare O-O."],
        ["g6", "Black opts for a fianchetto setup."],
        ["O-O", "Castle while holding the strong center."],
        ["Bg7", "Complete the fianchetto."],
        ["Re1", "Support e4 and prepare central expansion."],
        ["O-O", "Black castles."],
        ["h3", "Deny g4 to the bishop and knight — a useful waiting move."],
        ["Re8", "Put the rook opposite the white queen and e-pawns."],
        ["Nbd2", "Develop the last minor piece, keeping c3 for the pawn."],
        ["exd4", "Release the tension to free Black's game."],
        ["cxd4", "Recapture, keeping the ideal pawn duo on d4/e4."],
        ["d5", "Strike back in the center at last."],
      ],
    },
  ],
};
