export default {
  slug: "queens-gambit",
  name: "Queen's Gambit",
  eco: "D06",
  playableColors: ["white", "black"],
  detectionKeys: ["queens gambit", "queen's gambit", "slav defense"],
  lines: [
    {
      rank: 1,
      name: "QGD: Classical Bg5 Main Line",
      moves: [
        ["d4", "Take the center."],
        ["d5", "Symmetrical reply."],
        ["c4", "The Queen's Gambit: bid to deflect the d5 pawn."],
        ["e6", "The Declined: hold d5 at the cost of the c8 bishop."],
        ["Nc3", "Develop and add pressure on d5."],
        ["Nf6", "Defend d5 and develop."],
        ["Bg5", "The classical pin, indirectly fighting for d5."],
        ["Be7", "Break the pin calmly."],
        ["e3", "Solidify d4 and open the f1 bishop."],
        ["O-O", "King safety."],
        ["Nf3", "Complete kingside development."],
        ["h6", "Put the question to the bishop — a useful luft too."],
        ["Bh4", "Keep the pin at a distance."],
        ["b6", "The Tartakower: fianchetto to solve the c8 bishop."],
        ["cxd5", "Clarify the center before ...Bb7 lands."],
        ["Nxd5", "Recapture actively, offering simplification."],
        ["Bxe7", "Trade into the structure battle."],
        ["Qxe7", "Recapture; Black is solid but slightly passive."],
        ["Nxd5", "Trade again, pulling a pawn to d5."],
        ["exd5", "Recapture; the symmetric structure slightly favors White's bishop."],
      ],
    },
    {
      rank: 2,
      name: "Queen's Gambit Accepted",
      moves: [
        ["d4", "Take the center."],
        ["d5", "Symmetrical reply."],
        ["c4", "The Queen's Gambit."],
        ["dxc4", "Accept — Black gives the center for quick development."],
        ["Nf3", "Stop ...e5 and develop; the pawn will come back."],
        ["Nf6", "Natural development."],
        ["e3", "Open the bishop to regain c4."],
        ["e6", "Black returns the pawn for smooth development."],
        ["Bxc4", "Regain the pawn with a good bishop."],
        ["c5", "The equalizing strike at d4."],
        ["O-O", "Castle before resolving the center."],
        ["a6", "Prepare ...b5 with tempo."],
        ["Qe2", "The main plan: prepare Rd1 and dxc5 ideas."],
        ["b5", "Gain space with tempo on the bishop."],
        ["Bb3", "Retreat, still eyeing e6/f7."],
        ["Bb7", "The bishop takes the long diagonal."],
        ["Rd1", "The rook opposes the black queen — central pressure."],
        ["Nbd7", "Develop, holding c5 and e5."],
        ["Nc3", "Complete development; the d4-d5 break is in the air."],
        ["Be7", "Prepare to castle; a rich middlegame awaits."],
      ],
    },
    {
      rank: 3,
      name: "Slav: Main Line 4...dxc4",
      moves: [
        ["d4", "Take the center."],
        ["d5", "Symmetrical reply."],
        ["c4", "The Queen's Gambit."],
        ["c6", "The Slav: hold d5 while keeping the c8 bishop free."],
        ["Nf3", "Develop flexibly."],
        ["Nf6", "Natural development."],
        ["Nc3", "Pressure d5 again."],
        ["dxc4", "Take now that ...b5 can defend the pawn."],
        ["a4", "Stop ...b5 at the cost of the b4 square."],
        ["Bf5", "The Slav's point: the bishop develops actively first."],
        ["e3", "Prepare to regain c4."],
        ["e6", "Solidify and open the f8 bishop."],
        ["Bxc4", "Regain the pawn."],
        ["Bb4", "Pin, using the b4 hole a4 created."],
        ["O-O", "Castle and offer the central battle."],
        ["Nbd7", "Develop, supporting ...c5 or ...e5 breaks."],
        ["Qe2", "Prepare the central e4 break."],
        ["Bg6", "Tuck the bishop from e4-e5 tempo gains."],
        ["e4", "The point of Qe2: the big center arrives."],
        ["O-O", "Black castles; White has space, Black has no weaknesses."],
      ],
    },
    {
      rank: 4,
      name: "QGD: Exchange Variation",
      moves: [
        ["d4", "Take the center."],
        ["d5", "Symmetrical reply."],
        ["c4", "The Queen's Gambit."],
        ["e6", "The Declined."],
        ["Nc3", "Develop with pressure on d5."],
        ["Nf6", "Defend and develop."],
        ["cxd5", "The Exchange: fix the structure for the minority attack."],
        ["exd5", "Recapture; the c8 bishop is free but d5 is static."],
        ["Bg5", "Pin, the standard pressure piece."],
        ["c6", "Solidify d5 — and create the b7/c6 target White wants."],
        ["e3", "Solid center; the plan is b4-b5 on the queenside."],
        ["Be7", "Unpin."],
        ["Bd3", "The kingside diagonal — White can also attack there."],
        ["Nbd7", "Standard development."],
        ["Qc2", "Control e4 and support the b-pawn's advance."],
        ["O-O", "King safety."],
        ["Nge2", "The Botvinnik setup: knights on c3/e2, f3 stays free for f2-f3."],
        ["Re8", "Contest the e-file."],
        ["O-O", "Castle; now b4-b5 or f3-e4 — two plans, one setup."],
        ["Nf8", "The standard regrouping toward e6/g6."],
      ],
    },
  ],
};
