// Sources (see README "Metodología de curaduría"):
//   Theory: standard published theory for the named variations, cross-checked
//   against Wikibooks "Chess Opening Theory" (consulted 2026-07-17). ECO D06-D47.
//   Engine audit 2026-07-20 (Stockfish 17.1, scripts/audit-lines.mjs): all lines
//   clean; only the rank 2 (QGA) final move was tuned (...Qc7 instead of
//   ...Be7, matching the main tabiya).
export default {
  slug: "queens-gambit",
  name: "Queen's Gambit",
  eco: "D06",
  playableColors: ["white", "black"],
  detectionKeys: ["queens gambit", "queen's gambit", "slav defense"],
  lines: [
    {
      rank: 1,
      name: "QGD: Classical Bg5 Main Line",
      moves: [
        ["d4", "Take the center."],
        ["d5", "Symmetrical reply."],
        ["c4", "The Queen's Gambit: bid to deflect the d5 pawn."],
        ["e6", "The Declined: hold d5 at the cost of the c8 bishop."],
        ["Nc3", "Develop and add pressure on d5."],
        ["Nf6", "Defend d5 and develop."],
        ["Bg5", "The classical pin, indirectly fighting for d5."],
        ["Be7", "Break the pin calmly."],
        ["e3", "Solidify d4 and open the f1 bishop."],
        ["O-O", "King safety."],
        ["Nf3", "Complete kingside development."],
        ["h6", "Put the question to the bishop — a useful luft too."],
        ["Bh4", "Keep the pin at a distance."],
        ["b6", "The Tartakower: fianchetto to solve the c8 bishop."],
        ["cxd5", "Clarify the center before ...Bb7 lands."],
        ["Nxd5", "Recapture actively, offering simplification."],
        ["Bxe7", "Trade into the structure battle."],
        ["Qxe7", "Recapture; Black is solid but slightly passive."],
        ["Nxd5", "Trade again, pulling a pawn to d5."],
        ["exd5", "Recapture; the symmetric structure slightly favors White's bishop."],
      ],
    },
    {
      rank: 2,
      name: "Queen's Gambit Accepted",
      moves: [
        ["d4", "Take the center."],
        ["d5", "Symmetrical reply."],
        ["c4", "The Queen's Gambit."],
        ["dxc4", "Accept — Black gives the center for quick development."],
        ["Nf3", "Stop ...e5 and develop; the pawn will come back."],
        ["Nf6", "Natural development."],
        ["e3", "Open the bishop to regain c4."],
        ["e6", "Black returns the pawn for smooth development."],
        ["Bxc4", "Regain the pawn with a good bishop."],
        ["c5", "The equalizing strike at d4."],
        ["O-O", "Castle before resolving the center."],
        ["a6", "Prepare ...b5 with tempo."],
        ["Qe2", "The main plan: prepare Rd1 and dxc5 ideas."],
        ["b5", "Gain space with tempo on the bishop."],
        ["Bb3", "Retreat, still eyeing e6/f7."],
        ["Bb7", "The bishop takes the long diagonal."],
        ["Rd1", "The rook opposes the black queen — central pressure."],
        ["Nbd7", "Develop, holding c5 and e5."],
        ["Nc3", "Complete development; the d4-d5 break is in the air."],
        ["Qc7", "Connect the rooks and watch e5/c5 — full equality in hand."],
      ],
    },
    {
      rank: 3,
      name: "Slav: Main Line 4...dxc4",
      moves: [
        ["d4", "Take the center."],
        ["d5", "Symmetrical reply."],
        ["c4", "The Queen's Gambit."],
        ["c6", "The Slav: hold d5 while keeping the c8 bishop free."],
        ["Nf3", "Develop flexibly."],
        ["Nf6", "Natural development."],
        ["Nc3", "Pressure d5 again."],
        ["dxc4", "Take now that ...b5 can defend the pawn."],
        ["a4", "Stop ...b5 at the cost of the b4 square."],
        ["Bf5", "The Slav's point: the bishop develops actively first."],
        ["e3", "Prepare to regain c4."],
        ["e6", "Solidify and open the f8 bishop."],
        ["Bxc4", "Regain the pawn."],
        ["Bb4", "Pin, using the b4 hole a4 created."],
        ["O-O", "Castle and offer the central battle."],
        ["Nbd7", "Develop, supporting ...c5 or ...e5 breaks."],
        ["Qe2", "Prepare the central e4 break."],
        ["Bg6", "Tuck the bishop from e4-e5 tempo gains."],
        ["e4", "The point of Qe2: the big center arrives."],
        ["O-O", "Black castles; White has space, Black has no weaknesses."],
      ],
    },
    {
      rank: 4,
      name: "QGD: Exchange Variation",
      moves: [
        ["d4", "Take the center."],
        ["d5", "Symmetrical reply."],
        ["c4", "The Queen's Gambit."],
        ["e6", "The Declined."],
        ["Nc3", "Develop with pressure on d5."],
        ["Nf6", "Defend and develop."],
        ["cxd5", "The Exchange: fix the structure for the minority attack."],
        ["exd5", "Recapture; the c8 bishop is free but d5 is static."],
        ["Bg5", "Pin, the standard pressure piece."],
        ["c6", "Solidify d5 — and create the b7/c6 target White wants."],
        ["e3", "Solid center; the plan is b4-b5 on the queenside."],
        ["Be7", "Unpin."],
        ["Bd3", "The kingside diagonal — White can also attack there."],
        ["Nbd7", "Standard development."],
        ["Qc2", "Control e4 and support the b-pawn's advance."],
        ["O-O", "King safety."],
        ["Nge2", "The Botvinnik setup: knights on c3/e2, f3 stays free for f2-f3."],
        ["Re8", "Contest the e-file."],
        ["O-O", "Castle; now b4-b5 or f3-e4 — two plans, one setup."],
        ["Nf8", "The standard regrouping toward e6/g6."],
      ],
    },
    {
      rank: 5,
      name: "Semi-Slav: Meran",
      moves: [
        ["d4", "Take the center."],
        ["d5", "Symmetrical reply."],
        ["c4", "The Queen's Gambit."],
        ["c6", "Start with the Slav move order."],
        ["Nf3", "Develop flexibly."],
        ["Nf6", "Natural development."],
        ["Nc3", "Pressure d5."],
        ["e6", "The Semi-Slav: both center pawns defended, ...dxc4 plus ...b5 loaded."],
        ["e3", "The solid main line, avoiding the razor-sharp Botvinnik 5.Bg5."],
        ["Nbd7", "Flexible development, supporting both ...c5 and ...e5."],
        ["Bd3", "Natural — and now the Meran machinery starts."],
        ["dxc4", "The Meran: take exactly when the bishop must lose a tempo."],
        ["Bxc4", "Recapture."],
        ["b5", "Gain the tempo and start queenside expansion."],
        ["Bd3", "Best retreat, back on the kingside diagonal."],
        ["a6", "Support ...b4 and prepare the freeing ...c5."],
        ["e4", "Claim the center while Black is still unraveling."],
        ["c5", "The thematic counter — strike d4 before e5 lands."],
        ["e5", "Push on, hitting the f6 knight — the critical Meran fight."],
        ["cxd4", "Take; the wild lines after Nxb5 are the Meran's main battlefield."],
      ],
    },
    {
      rank: 6,
      name: "Tarrasch Defense",
      moves: [
        ["d4", "Take the center."],
        ["d5", "Symmetrical reply."],
        ["c4", "The Queen's Gambit."],
        ["e6", "Hold d5."],
        ["Nc3", "Develop with pressure on d5."],
        ["c5", "The Tarrasch: free piece play at the price of an isolated pawn."],
        ["cxd5", "Take toward the isolani structure White wants."],
        ["exd5", "Recapture, keeping the strong pawn presence on d5."],
        ["Nf3", "Develop and eye the d4/e5 squares."],
        ["Nc6", "Support c5/d4-breaks and develop."],
        ["g3", "The Rubinstein plan: fianchetto against the d5 pawn."],
        ["Nf6", "Natural development."],
        ["Bg2", "The bishop takes aim at d5 — Black's long-term burden."],
        ["Be7", "Prepare to castle."],
        ["O-O", "King safety."],
        ["O-O", "Black castles; activity must compensate the structure."],
        ["Bg5", "Pressure f6, indirectly d5 — the classic anti-Tarrasch piece."],
        ["cxd4", "Resolve the tension before d4xc5 comes."],
        ["Nxd4", "Recapture; the isolated d5 pawn is fixed as the target."],
        ["h6", "Put the question to the bishop — the main tabiya of the Tarrasch."],
      ],
    },
  ],
};
