// Sources (see README "Metodología de curaduría"):
//   ranks 1-4: initial catalog (2026-07-14), legality-validated only; theory audit pending.
//   ranks 5-6 (added 2026-07-17): standard published theory for the named variations,
//   cross-checked against Wikibooks "Chess Opening Theory" where coverage exists
//   (en.wikibooks.org/wiki/Chess_Opening_Theory, consulted 2026-07-17); natural-play
//   extensions past book depth. Masters-DB frequency check (scripts/verify-lines.mjs)
//   pending — the explorer API was auth-gated at the time of writing.
//   Rank 5: Open Variation (ECO C80-C83). Rank 6: Marshall Attack (ECO C89).
export default {
  slug: "ruy-lopez",
  name: "Ruy Lopez",
  eco: "C60",
  playableColors: ["white", "black"],
  detectionKeys: ["ruy lopez", "spanish game"],
  lines: [
    {
      rank: 1,
      name: "Closed Main Line (Chigorin)",
      moves: [
        ["e4", "Take the center."],
        ["e5", "Symmetrical reply."],
        ["Nf3", "Attack e5 and develop."],
        ["Nc6", "Defend e5."],
        ["Bb5", "The Ruy Lopez: pressure the defender of e5."],
        ["a6", "The Morphy Defense: put the question to the bishop."],
        ["Ba4", "Keep the pin option alive."],
        ["Nf6", "Develop and counterattack e4."],
        ["O-O", "Castle — e4 is tactically defended (Nxe4 runs into Re1 ideas)."],
        ["Be7", "The Closed Ruy: solid development first."],
        ["Re1", "Now really defend e4 and take the e-file."],
        ["b5", "Break the latent pin before ...d6."],
        ["Bb3", "The bishop keeps its strong diagonal toward f7."],
        ["d6", "Solidify e5 and open the c8 bishop."],
        ["c3", "Prepare d4 and create the classic Spanish retreat c2."],
        ["O-O", "Black completes king safety."],
        ["h3", "Prevent the annoying pin ...Bg4 before playing d4."],
        ["Na5", "The Chigorin plan: harass the b3 bishop and stake c4."],
        ["Bc2", "Preserve the bishop on its ideal diagonal."],
        ["c5", "Grab queenside space — the main tabiya of the Closed Ruy."],
      ],
    },
    {
      rank: 2,
      name: "Berlin Defense",
      moves: [
        ["e4", "Take the center."],
        ["e5", "Symmetrical reply."],
        ["Nf3", "Attack e5 and develop."],
        ["Nc6", "Defend e5."],
        ["Bb5", "The Ruy Lopez."],
        ["Nf6", "The Berlin: immediate counterplay against e4."],
        ["O-O", "The main line: let Black take and trust the initiative."],
        ["Nxe4", "Take the pawn — the Berlin's point."],
        ["d4", "Open the center against the loose knight."],
        ["Nd6", "Attack the b5 bishop while retreating."],
        ["Bxc6", "Trade before recapturing on e5."],
        ["dxc6", "Keep structure; ...bxc6 would leave weaker pawns."],
        ["dxe5", "Win the pawn back with tempo on the d6 knight."],
        ["Nf5", "The knight finds its best square."],
        ["Qxd8+", "Enter the famous Berlin endgame."],
        ["Kxd8", "Forced — Black loses castling but has the bishop pair."],
        ["Nc3", "Develop with tempo toward d5."],
        ["Ke8", "Tuck the king away; Black's setup is resilient."],
        ["h3", "Take g4 from the knight and bishop — a key endgame move."],
        ["h5", "Fix White's kingside and give the f5 knight a route via h4-g6."],
      ],
    },
    {
      rank: 3,
      name: "Exchange Variation",
      moves: [
        ["e4", "Take the center."],
        ["e5", "Symmetrical reply."],
        ["Nf3", "Attack e5 and develop."],
        ["Nc6", "Defend e5."],
        ["Bb5", "The Ruy Lopez."],
        ["a6", "The Morphy Defense."],
        ["Bxc6", "The Exchange: inflict doubled pawns for a superior endgame."],
        ["dxc6", "Open the c8 bishop — the standard recapture."],
        ["O-O", "Castle and prepare d4; 5.Nxe5 would lose to ...Qd4."],
        ["f6", "Solidify e5 the sturdy way."],
        ["d4", "Strike while ahead in structure."],
        ["exd4", "Trade — holding e5 forever is impossible."],
        ["Nxd4", "Recapture with a strong central knight."],
        ["c5", "Kick the knight and free the doubled pawn."],
        ["Nb3", "Retreat, keeping the queenside pawns fixed as targets."],
        ["Qxd1", "Trade into the endgame White wants — but Black is solid too."],
        ["Rxd1", "White's 4-v-3 kingside majority is the long-term trump."],
        ["Bg4", "Activate with tempo on the rook via the pin square."],
        ["f3", "Blunt the bishop and take control of e4."],
        ["Be6", "Reroute to the strong blockading square."],
      ],
    },
    {
      rank: 4,
      name: "Steinitz Deferred: ...d6 Setup",
      moves: [
        ["e4", "Take the center."],
        ["e5", "Symmetrical reply."],
        ["Nf3", "Attack e5 and develop."],
        ["Nc6", "Defend e5."],
        ["Bb5", "The Ruy Lopez."],
        ["a6", "The Morphy Defense."],
        ["Ba4", "Keep the tension."],
        ["d6", "The Steinitz Deferred: a solid e5 fortress."],
        ["c3", "Prepare d4 and preserve the bishop."],
        ["Nf6", "Develop normally."],
        ["d4", "Build the strong center."],
        ["Bd7", "Unpin c6 and connect the pieces."],
        ["O-O", "King safety."],
        ["Be7", "Prepare to castle."],
        ["Re1", "Overprotect e4 — the thematic Spanish rook."],
        ["O-O", "Black castles."],
        ["Nbd2", "Start the classic Spanish knight tour toward g3/f5."],
        ["Re8", "Contest the e-file."],
        ["Nf1", "Continue the maneuver — slow but venomous."],
        ["Bf8", "Black regroups likewise; a rich maneuvering game begins."],
      ],
    },
    {
      rank: 5,
      name: "Open Variation: 5...Nxe4",
      moves: [
        ["e4", "Take the center."],
        ["e5", "Symmetrical reply."],
        ["Nf3", "Attack e5 and develop."],
        ["Nc6", "Defend e5."],
        ["Bb5", "The Ruy Lopez."],
        ["a6", "The Morphy Defense."],
        ["Ba4", "Keep the pin option alive."],
        ["Nf6", "Develop and counterattack e4."],
        ["O-O", "Castle — e4 is only tactically defended."],
        ["Nxe4", "The Open Variation: take the pawn and fight for the initiative."],
        ["d4", "Open the center at once — White's compensation is activity."],
        ["b5", "Push the bishop back before it recaptures on c6."],
        ["Bb3", "The bishop keeps eyeing f7 from its classic diagonal."],
        ["d5", "Secure the e4 knight and free the c8 bishop — the Open's backbone."],
        ["dxe5", "Grab the e5 pawn; the advanced pawn cramps Black later."],
        ["Be6", "Develop and overprotect d5 against the b3 bishop."],
        ["c3", "Blunt ...Nc5-ideas hitting b3 and prepare Nbd2 to evict e4."],
        ["Be7", "Sensible development; ...Bc5 is the sharper alternative."],
        ["Nbd2", "Challenge the strong e4 knight — Black's whole game hangs on it."],
        ["O-O", "King safety; the fight revolves around the e4 outpost."],
      ],
    },
    {
      rank: 6,
      name: "Marshall Attack",
      moves: [
        ["e4", "Take the center."],
        ["e5", "Symmetrical reply."],
        ["Nf3", "Attack e5 and develop."],
        ["Nc6", "Defend e5."],
        ["Bb5", "The Ruy Lopez."],
        ["a6", "The Morphy Defense."],
        ["Ba4", "Keep the pin option alive."],
        ["Nf6", "Develop and counterattack e4."],
        ["O-O", "Castle."],
        ["Be7", "Solid development, keeping ...b5 and ...d5 ideas in reserve."],
        ["Re1", "Defend e4 and take the e-file."],
        ["b5", "Push the bishop off the a4-e8 diagonal."],
        ["Bb3", "Standard retreat toward f7."],
        ["O-O", "Castle FIRST — delaying ...d6 keeps the d-pawn free for ...d5."],
        ["c3", "Prepare d4; this is what the Marshall exploits."],
        ["d5", "The Marshall Attack: sacrifice a pawn for a lasting kingside attack."],
        ["exd5", "Accept — declining concedes easy equality."],
        ["Nxd5", "Recapture and clear the way for ...Nxe5xe5 tricks."],
        ["Nxe5", "Take the pawn; White banks the material."],
        ["Nxe5", "Recapture — after Rxe5 c6 Black gets ...Bd6, ...Qh4 with a raging attack."],
      ],
    },
  ],
};
