// Sources (see README "Metodología de curaduría"):
//   Theory: Wikibooks "Chess Opening Theory" 1.e4 d5 pages (consulted
//   2026-07-17) for the named variations (ECO B01).
//   Engine audit 2026-07-20 (Stockfish 17.1, scripts/audit-lines.mjs): tails of
//   ranks 2-4 rebuilt along engine-approved play (rank 4 now uses the modern
//   ...g6 Banker setup). The old rank 5 (Portuguese Gambit) and rank 6
//   (Icelandic Gambit) were removed: with correct White play both leave Black
//   at ~+0.9 or worse, beyond the catalog quality bar — and the old Icelandic
//   line even taught White to blunder a queen for a rook. 4 quality lines kept.
//   The Scandinavian itself runs at ~+0.5/+0.7 for White in every main line;
//   that is the honest engine verdict on the opening, right at the bar.
export default {
  slug: "scandinavian",
  name: "Scandinavian Defense",
  eco: "B01",
  playableColors: ["black", "white"],
  detectionKeys: ["scandinavian defense"],
  lines: [
    {
      rank: 1,
      name: "Main Line: 3...Qa5",
      moves: [
        ["e4", "White takes the center."],
        ["d5", "The Scandinavian: challenge e4 on move one."],
        ["exd5", "White accepts — declining gives Black easy play."],
        ["Qxd5", "Recapture immediately; the queen comes out early by design."],
        ["Nc3", "Develop with tempo on the queen."],
        ["Qa5", "The classical square: safe, pinning ideas against d2."],
        ["d4", "White takes the center that remains."],
        ["Nf6", "Develop."],
        ["Nf3", "Develop."],
        ["c6", "The system move: a Caro-like wall and an escape square for the queen."],
        ["Bc4", "Active development, eyeing f7."],
        ["Bf5", "The good bishop develops outside the wall first."],
        ["Bd2", "Discourage ...Bb4 and prepare Nd5/Ne4 tricks against the queen."],
        ["e6", "Complete the wall."],
        ["Qe2", "Prepare O-O-O with central pressure."],
        ["Bb4", "Pin, fighting for the d5/e4 squares."],
        ["O-O-O", "White castles long — sharp opposite-side play."],
        ["Nbd7", "Finish development, ready to castle either way."],
        ["a3", "Put the question to the bishop."],
        ["Bxc3", "Trade and damage the queenside — Black's structure is superb."],
      ],
    },
    {
      rank: 2,
      name: "Modern: 3...Qd6",
      moves: [
        ["e4", "White takes the center."],
        ["d5", "The Scandinavian."],
        ["exd5", "White accepts."],
        ["Qxd5", "Recapture."],
        ["Nc3", "Tempo on the queen."],
        ["Qd6", "The modern square: flexible, watching e5 and the d-file."],
        ["d4", "White builds."],
        ["Nf6", "Develop."],
        ["Nf3", "Develop."],
        ["a6", "The key system move: deny b5 to knight and bishop forever."],
        ["g3", "White fianchettoes against the coming ...b5/...Bb7."],
        ["b5", "Expand — Black plays on the queenside light squares."],
        ["Bg2", "Complete the fianchetto."],
        ["Bb7", "Oppose it on the long diagonal."],
        ["O-O", "White castles."],
        ["e6", "Solidify and open the f8 bishop."],
        ["Bf4", "Hit the queen with tempo."],
        ["Qb6", "Sidestep, keeping an eye on d4 and b2."],
        ["Be3", "Hit the queen again while overprotecting d4."],
        ["Nbd7", "Develop calmly; the queen stays active on b6."],
      ],
    },
    {
      rank: 3,
      name: "Modern Scandinavian: 2...Nf6",
      moves: [
        ["e4", "White takes the center."],
        ["d5", "The Scandinavian."],
        ["exd5", "White accepts."],
        ["Nf6", "The modern gambit approach: recapture with the knight."],
        ["d4", "White keeps the pawn for now and builds."],
        ["Nxd5", "Regain it; the knight sits well on d5."],
        ["Nf3", "Develop."],
        ["g6", "Fianchetto — pressure on d4 defines Black's setup."],
        ["Be2", "Solid development."],
        ["Bg7", "The bishop bears down on d4."],
        ["O-O", "White castles."],
        ["O-O", "Black follows."],
        ["c4", "Gain space with tempo on the knight."],
        ["Nb6", "The standard retreat, pressuring c4."],
        ["Nc3", "Develop; White has space, Black has targets."],
        ["Bg4", "Pin the defender of d4 before committing the b8 knight."],
        ["c5", "Gain space with tempo on the b6 knight."],
        ["Nd5", "Centralize — trades ease Black's cramped game."],
        ["Qb3", "Hit b7 and d5 while unpinning by force."],
        ["Nxc3", "Trade; after bxc3 ...b6 dissolves White's space edge."],
      ],
    },
    {
      rank: 4,
      name: "3...Qd8: The Banker",
      moves: [
        ["e4", "White takes the center."],
        ["d5", "The Scandinavian."],
        ["exd5", "White accepts."],
        ["Qxd5", "Recapture."],
        ["Nc3", "Tempo on the queen."],
        ["Qd8", "Full retreat: lose time, keep an unbreakable structure."],
        ["d4", "White builds the center."],
        ["Nf6", "Develop."],
        ["Nf3", "Develop."],
        ["g6", "The modern Banker treatment: fianchetto and castle fast."],
        ["Bf4", "Active development, eyeing c7 and e5."],
        ["Bg7", "The bishop counterbalances d4 from afar."],
        ["Qd2", "Connect toward Bh6 — trade off Black's best piece."],
        ["O-O", "King safety first; the structure has no holes."],
        ["Bh6", "Execute the plan: remove the fianchetto defender."],
        ["Qd6", "Activate before the trade lands; e5/f4 squares matter."],
        ["Be2", "Complete development calmly."],
        ["Bf5", "The problem bishop finds its best diagonal."],
        ["Bxg7", "Complete the dark-square trade."],
        ["Kxg7", "Recapture; solid, slightly passive, hard to crack."],
      ],
    },
  ],
};
