// Sources (see README "Metodología de curaduría"):
//   ranks 1-4: initial catalog (2026-07-14), legality-validated only; theory audit pending.
//   ranks 5-6 (added 2026-07-17): selected per Wikibooks "Chess Opening Theory"
//   (en.wikibooks.org/wiki/Chess_Opening_Theory/1._e4/1...d5, consulted 2026-07-17);
//   book moves follow the cited pages, with natural-play extensions past book depth.
//   Masters-DB frequency check (scripts/verify-lines.mjs) pending — explorer API
//   was auth-gated at the time of writing.
//   Rank 5: Portuguese 3.d4 Bg4, incl. the 5.g4 "correspondence refutation" (ECO B01).
//   Rank 6: Icelandic Gambit 3.c4 e6 (ECO B01).
export default {
  slug: "scandinavian",
  name: "Scandinavian Defense",
  eco: "B01",
  playableColors: ["black", "white"],
  detectionKeys: ["scandinavian defense"],
  lines: [
    {
      rank: 1,
      name: "Main Line: 3...Qa5",
      moves: [
        ["e4", "White takes the center."],
        ["d5", "The Scandinavian: challenge e4 on move one."],
        ["exd5", "White accepts — declining gives Black easy play."],
        ["Qxd5", "Recapture immediately; the queen comes out early by design."],
        ["Nc3", "Develop with tempo on the queen."],
        ["Qa5", "The classical square: safe, pinning ideas against d2."],
        ["d4", "White takes the center that remains."],
        ["Nf6", "Develop."],
        ["Nf3", "Develop."],
        ["c6", "The system move: a Caro-like wall and an escape square for the queen."],
        ["Bc4", "Active development, eyeing f7."],
        ["Bf5", "The good bishop develops outside the wall first."],
        ["Bd2", "Discourage ...Bb4 and prepare Nd5/Ne4 tricks against the queen."],
        ["e6", "Complete the wall."],
        ["Qe2", "Prepare O-O-O with central pressure."],
        ["Bb4", "Pin, fighting for the d5/e4 squares."],
        ["O-O-O", "White castles long — sharp opposite-side play."],
        ["Nbd7", "Finish development, ready to castle either way."],
        ["a3", "Put the question to the bishop."],
        ["Bxc3", "Trade and damage the queenside — Black's structure is superb."],
      ],
    },
    {
      rank: 2,
      name: "Modern: 3...Qd6",
      moves: [
        ["e4", "White takes the center."],
        ["d5", "The Scandinavian."],
        ["exd5", "White accepts."],
        ["Qxd5", "Recapture."],
        ["Nc3", "Tempo on the queen."],
        ["Qd6", "The modern square: flexible, watching e5 and the d-file."],
        ["d4", "White builds."],
        ["Nf6", "Develop."],
        ["Nf3", "Develop."],
        ["a6", "The key system move: deny b5 to knight and bishop forever."],
        ["g3", "White fianchettoes against the coming ...b5/...Bb7."],
        ["b5", "Expand — Black plays on the queenside light squares."],
        ["Bg2", "Complete the fianchetto."],
        ["Bb7", "Oppose it on the long diagonal."],
        ["O-O", "White castles."],
        ["e6", "Solidify and open the f8 bishop."],
        ["Bf4", "Hit the queen with tempo."],
        ["Qb6", "Sidestep, keeping an eye on d4 and b2."],
        ["a4", "White strikes at the pawn chain."],
        ["b4", "Advance — the knight must find a new home."],
      ],
    },
    {
      rank: 3,
      name: "Modern Scandinavian: 2...Nf6",
      moves: [
        ["e4", "White takes the center."],
        ["d5", "The Scandinavian."],
        ["exd5", "White accepts."],
        ["Nf6", "The modern gambit approach: recapture with the knight."],
        ["d4", "White keeps the pawn for now and builds."],
        ["Nxd5", "Regain it; the knight sits well on d5."],
        ["Nf3", "Develop."],
        ["g6", "Fianchetto — pressure on d4 defines Black's setup."],
        ["Be2", "Solid development."],
        ["Bg7", "The bishop bears down on d4."],
        ["O-O", "White castles."],
        ["O-O", "Black follows."],
        ["c4", "Gain space with tempo on the knight."],
        ["Nb6", "The standard retreat, pressuring c4."],
        ["Nc3", "Develop; White has space, Black has targets."],
        ["Nc6", "Pile on d4 — the whole point of the setup."],
        ["Be3", "Defend d4."],
        ["Bg4", "Add pressure: the f3 defender is pinned."],
        ["d5", "White pushes, releasing the tension under pressure."],
        ["Bxf3", "Remove the defender before retreating the knight."],
      ],
    },
    {
      rank: 4,
      name: "3...Qd8: The Banker",
      moves: [
        ["e4", "White takes the center."],
        ["d5", "The Scandinavian."],
        ["exd5", "White accepts."],
        ["Qxd5", "Recapture."],
        ["Nc3", "Tempo on the queen."],
        ["Qd8", "Full retreat: lose time, keep an unbreakable structure."],
        ["d4", "White builds the center."],
        ["Nf6", "Develop."],
        ["Nf3", "Develop."],
        ["Bg4", "Active development while the pin is annoying."],
        ["h3", "Put the question."],
        ["Bxf3", "Concede the pair to wreck White's coordination... slightly."],
        ["Qxf3", "Recapture; the queen eyes b7."],
        ["c6", "Cover b7 and build the wall."],
        ["Bc4", "Actively placed, staring at f7."],
        ["e6", "Complete the solid shell."],
        ["O-O", "White castles."],
        ["Nbd7", "Develop, heading for ...Be7 and ...O-O."],
        ["Bf4", "White enjoys free development."],
        ["Be7", "Black completes the setup: passive but nearly refutation-proof."],
      ],
    },
    {
      rank: 5,
      name: "Portuguese: 3.d4 Bg4",
      moves: [
        ["e4", "White takes the center."],
        ["d5", "The Scandinavian."],
        ["exd5", "White accepts."],
        ["Nf6", "The gambit move order."],
        ["d4", "White holds the extra pawn and builds."],
        ["Bg4", "The Portuguese: develop with maximum piece pressure, pawn be damned."],
        ["f3", "The critical test: kick the bishop and keep everything."],
        ["Bf5", "Retreat but stay active — d3/c2 are the targets."],
        ["g4", "The 'correspondence refutation': kick again and grab space."],
        ["Bg6", "Keep the diagonal; the bishop waits for e4/d3 to reappear."],
        ["c4", "Cement d5 — White plays for the full point of material."],
        ["e6", "Strike the pawn chain before White consolidates."],
        ["dxe6", "Take — holding everything is impossible."],
        ["fxe6", "Recapture toward the center; the f-file opens for the attack."],
        ["Nc3", "Develop and cover the loose light squares."],
        ["Bb4", "Pin — every Black piece points at White's king."],
        ["Bg2", "The kingside pawns advanced, so the bishop guards from g2."],
        ["Nc6", "Full mobilization; d4 is the pressure point."],
        ["Ne2", "Careful development; d4 and f4 both get cover (the c3 knight is pinned)."],
        ["Qe7", "Connect for ...O-O-O — Black's activity vs White's extra pawn."],
      ],
    },
    {
      rank: 6,
      name: "Icelandic Gambit: 3.c4 e6",
      moves: [
        ["e4", "White takes the center."],
        ["d5", "The Scandinavian."],
        ["exd5", "White accepts."],
        ["Nf6", "The gambit move order."],
        ["c4", "White holds the pawn the greedy way — inviting the Icelandic."],
        ["e6", "The gambit: give a whole pawn for development and open lines."],
        ["dxe6", "Accept — declining hands Black easy equality."],
        ["Bxe6", "Recapture with the bishop, hitting c4 already."],
        ["d4", "Take the center White is entitled to — but development lags."],
        ["Bb4+", "Check, forcing a concession on the dark squares."],
        ["Bd2", "The main block."],
        ["Qe7", "Load the e-file against White's uncastled king."],
        ["Bxb4", "Trade off the pinning bishop — but it costs more time."],
        ["Qxb4+", "Recapture with tempo — the queen forks b2 threats too."],
        ["Qd2", "Block; b2 must be watched and the endgame beckons."],
        ["Nc6", "Keep the queens on and hit d4 — trading helps White."],
        ["d5", "Push, forking the c6 knight and e6 bishop..."],
        ["O-O-O", "...answered by the point: the rook lands on d8 with a pin."],
        ["dxe6", "Take the piece anyway."],
        ["Rxd2", "The pin cashes in: queen for rook — dynamic balance."],
      ],
    },
  ],
};
