// Sources (see README "Metodología de curaduría"):
//   Theory: standard published theory for the named variations, cross-checked
//   against Wikibooks "Chess Opening Theory" (consulted 2026-07-17). ECO B70-B76.
//   Engine audit 2026-07-20 (Stockfish 17.1, scripts/audit-lines.mjs): all lines
//   clean; only the rank 3 (Levenfish) final move was fixed — with the e-file
//   open after exd6/exd6, ...Be7 is correct where the old ...Bg7 ran into
//   tactics against c6/d6.
export default {
  slug: "sicilian-dragon",
  name: "Sicilian Dragon",
  eco: "B70",
  playableColors: ["black", "white"],
  detectionKeys: ["sicilian defense dragon", "sicilian defense: dragon", "dragon variation"],
  lines: [
    {
      rank: 1,
      name: "Yugoslav Attack: 9.Bc4 Main Line",
      moves: [
        ["e4", "White takes the center."],
        ["c5", "The Sicilian: fight for d4 asymmetrically."],
        ["Nf3", "Prepare d4."],
        ["d6", "Support ...Nf6 against e5 and keep options open."],
        ["d4", "The Open Sicilian."],
        ["cxd4", "Trade the wing pawn for a central one — the Sicilian's point."],
        ["Nxd4", "Recapture with a centralized knight."],
        ["Nf6", "Develop and attack e4."],
        ["Nc3", "Defend e4."],
        ["g6", "The Dragon: the g7 bishop will breathe fire down the long diagonal."],
        ["Be3", "The Yugoslav setup begins: Qd2 and O-O-O are coming."],
        ["Bg7", "Complete the fianchetto."],
        ["f3", "Blunt ...Ng4 and prepare the g4 pawn storm."],
        ["O-O", "Castle — the race is on."],
        ["Qd2", "Connect for O-O-O and aim at h6."],
        ["Nc6", "Develop with pressure on d4."],
        ["Bc4", "Stop ...d5 and eye f7 — the 9.Bc4 main line."],
        ["Bd7", "Prepare ...Rc8 and the c-file counterattack."],
        ["O-O-O", "Opposite-side castling: both sides attack at full speed."],
        ["Rc8", "The rook takes the file where White's king lives."],
      ],
    },
    {
      rank: 2,
      name: "Classical: 6.Be2",
      moves: [
        ["e4", "White takes the center."],
        ["c5", "The Sicilian."],
        ["Nf3", "Prepare d4."],
        ["d6", "Flexible support."],
        ["d4", "The Open Sicilian."],
        ["cxd4", "Standard trade."],
        ["Nxd4", "Recapture."],
        ["Nf6", "Develop with tempo on e4."],
        ["Nc3", "Defend e4."],
        ["g6", "The Dragon setup."],
        ["Be2", "The Classical: White castles short and plays positionally."],
        ["Bg7", "Complete the fianchetto."],
        ["O-O", "White castles."],
        ["Nc6", "Develop and hit d4."],
        ["Nb3", "Sidestep — avoid tricks on the c6/d4 diagonal."],
        ["O-O", "Castle; with same-side kings the game is calmer."],
        ["Bg5", "Pressure e7 and probe the dark squares."],
        ["Be6", "Develop toward the queenside light squares."],
        ["Kh1", "Tuck the king and prepare f4."],
        ["Rc8", "Take the half-open file — Black's play flows there."],
      ],
    },
    {
      rank: 3,
      name: "Levenfish: 6.f4 Nc6!",
      moves: [
        ["e4", "White takes the center."],
        ["c5", "The Sicilian."],
        ["Nf3", "Prepare d4."],
        ["d6", "Flexible support."],
        ["d4", "The Open Sicilian."],
        ["cxd4", "Standard trade."],
        ["Nxd4", "Recapture."],
        ["Nf6", "Develop with tempo."],
        ["Nc3", "Defend e4."],
        ["g6", "The Dragon setup."],
        ["f4", "The Levenfish: threatening e5 with a quick attack."],
        ["Nc6", "The precise answer — 6...Bg7? runs into 7.e5! tricks."],
        ["Nxc6", "Trade before the pressure on d4 mounts."],
        ["bxc6", "Recapture toward the center, opening the b-file."],
        ["e5", "White insists on the space-gaining push."],
        ["Nd7", "Retreat calmly; e5 will become weak, not strong."],
        ["exd6", "Release the tension before ...dxe5 favors Black."],
        ["exd6", "Recapture; Black's center pawns are fine and the bishops breathe."],
        ["Be2", "Develop and prepare O-O."],
        ["Be7", "With the e-file open, e7 beats g7 here — Black is comfortably equal."],
      ],
    },
    {
      rank: 4,
      name: "Yugoslav 9.O-O-O: ...d5!",
      moves: [
        ["e4", "White takes the center."],
        ["c5", "The Sicilian."],
        ["Nf3", "Prepare d4."],
        ["d6", "Flexible support."],
        ["d4", "The Open Sicilian."],
        ["cxd4", "Standard trade."],
        ["Nxd4", "Recapture."],
        ["Nf6", "Develop with tempo."],
        ["Nc3", "Defend e4."],
        ["g6", "The Dragon setup."],
        ["Be3", "Yugoslav development."],
        ["Bg7", "Complete the fianchetto."],
        ["f3", "Support e4, prepare g4."],
        ["O-O", "Castle."],
        ["Qd2", "Prepare O-O-O."],
        ["Nc6", "Develop with pressure on d4."],
        ["O-O-O", "The 9.O-O-O line — skipping Bc4 has a drawback..."],
        ["d5", "...this freeing break, the whole point: strike the center now!"],
        ["exd5", "Take — declining leaves White worse in the center."],
        ["Nxd5", "Recapture; Black has full equality and active pieces."],
      ],
    },
    {
      rank: 5,
      name: "Yugoslav: 9.g4",
      moves: [
        ["e4", "White takes the center."],
        ["c5", "The Sicilian."],
        ["Nf3", "Prepare d4."],
        ["d6", "Support the coming ...Nf6."],
        ["d4", "The Open Sicilian."],
        ["cxd4", "The thematic trade."],
        ["Nxd4", "Recapture."],
        ["Nf6", "Develop and hit e4."],
        ["Nc3", "Defend e4."],
        ["g6", "The Dragon."],
        ["Be3", "Yugoslav development."],
        ["Bg7", "Complete the fianchetto."],
        ["f3", "Support e4, prepare the storm."],
        ["O-O", "Castle."],
        ["Qd2", "Prepare O-O-O."],
        ["Nc6", "Develop with pressure on d4."],
        ["g4", "The immediate bayonet: gain space before deciding on the king."],
        ["Be6", "The main answer: develop and prepare ...d5 or ...Qa5 anyway."],
        ["Nxe6", "Trade before ...Nxd4 — doubling Black's pawns..."],
        ["fxe6", "...but the f-file opens and e6/d5 gets a firm grip — double-edged."],
      ],
    },
    {
      rank: 6,
      name: "Fianchetto: 6.g3",
      moves: [
        ["e4", "White takes the center."],
        ["c5", "The Sicilian."],
        ["Nf3", "Prepare d4."],
        ["d6", "Support the coming ...Nf6."],
        ["d4", "The Open Sicilian."],
        ["cxd4", "The thematic trade."],
        ["Nxd4", "Recapture."],
        ["Nf6", "Develop and hit e4."],
        ["Nc3", "Defend e4."],
        ["g6", "The Dragon."],
        ["g3", "The Fianchetto: meet the dragon bishop with its mirror image."],
        ["Nc6", "Develop with pressure on d4."],
        ["Nde2", "Sidestep — keep the knight rather than allow ...Nxd4."],
        ["Bg7", "Complete the fianchetto."],
        ["Bg2", "The g2 bishop guards e4, freeing the pieces from defense."],
        ["O-O", "Castle."],
        ["O-O", "Both kings safe: a positional Dragon, not a race."],
        ["Rb8", "Prepare the ...b5-b4 minority plan — Black's standard counterplay."],
        ["a4", "Restrain ...b5 immediately."],
        ["a6", "Insist: ...b5 will come with support."],
      ],
    },
  ],
};
