// Sources (see README "Metodología de curaduría"):
//   ranks 1-4: initial catalog (2026-07-14), legality-validated only; theory audit pending.
//   ranks 5-6 (added 2026-07-17): standard published theory for the named variations,
//   cross-checked against Wikibooks "Chess Opening Theory" where coverage exists
//   (en.wikibooks.org/wiki/Chess_Opening_Theory/1._e4/1...e5/2._Nc3, consulted
//   2026-07-17); natural-play extensions past book depth. Masters-DB frequency check
//   (scripts/verify-lines.mjs) pending — explorer API was auth-gated at the time of writing.
//   Rank 5: Frankenstein-Dracula 3.Bc4 Nxe4 (ECO C27).
//   Rank 6: Vienna Gambit Accepted 3...exf4 4.e5 (ECO C29).
export default {
  slug: "vienna-game",
  name: "Vienna Game",
  eco: "C25",
  playableColors: ["white"],
  detectionKeys: ["vienna game", "vienna gambit"],
  lines: [
    {
      rank: 1,
      name: "Vienna Gambit: 3...d5 Main Line",
      moves: [
        ["e4", "Take the center."],
        ["e5", "Symmetrical reply."],
        ["Nc3", "The Vienna: defend e4 first, keep f4 available."],
        ["Nf6", "Develop and hit e4."],
        ["f4", "The Vienna Gambit: fight for the center like a King's Gambit."],
        ["d5", "The correct counter — striking back in the center."],
        ["fxe5", "Take, gaining a tempo on the f6 knight."],
        ["Nxe4", "The point of ...d5: the knight lands actively."],
        ["Nf3", "Develop and cover the sensitive h4 checks."],
        ["Be7", "Calm development, preparing ...O-O."],
        ["d4", "Claim the center and open the c1 bishop."],
        ["O-O", "Black castles first."],
        ["Bd3", "Challenge the e4 knight directly."],
        ["Nxc3", "Trade before the knight is pushed away."],
        ["bxc3", "Recapture toward the center — big pawn presence."],
        ["c5", "Chip at the pawn center immediately."],
        ["O-O", "King safety; the half-open f-file is White's prize."],
        ["Nc6", "Develop and pressure d4."],
        ["Be3", "Hold d4; White's center and f-file promise attacking chances."],
        ["cxd4", "Trade to relieve the pressure."],
      ],
    },
    {
      rank: 2,
      name: "Max Lange Setup: 2...Nc6 3.Bc4",
      moves: [
        ["e4", "Take the center."],
        ["e5", "Symmetrical reply."],
        ["Nc3", "The Vienna."],
        ["Nc6", "Natural development."],
        ["Bc4", "Target f7 while delaying the knight to f3."],
        ["Nf6", "Develop and eye e4."],
        ["d3", "Solidify e4; the f4 push is coming."],
        ["Bc5", "Active development."],
        ["f4", "The thematic Vienna advance — a delayed King's Gambit."],
        ["d6", "Hold e5 and open the c8 bishop."],
        ["Nf3", "Develop and keep the f-file tension."],
        ["O-O", "Black castles into the coming storm."],
        ["f5", "Clamp the kingside — the attack plays itself: g4-g5 next."],
        ["Na5", "Black seeks the strong c4 bishop."],
        ["Bb3", "Preserve it — this bishop is the attack's backbone."],
        ["Nxb3", "Trade anyway to blunt the diagonal."],
        ["axb3", "Recapture; the open a-file is a small bonus."],
        ["c6", "Prepare ...b5 and give the queen c7."],
        ["g4", "Launch the pawn storm against the castled king."],
        ["b5", "Black races on the other wing — sharp opposite-flank play."],
      ],
    },
    {
      rank: 3,
      name: "Positional Vienna: 3.g3",
      moves: [
        ["e4", "Take the center."],
        ["e5", "Symmetrical reply."],
        ["Nc3", "The Vienna."],
        ["Nf6", "Develop and hit e4."],
        ["g3", "The positional treatment: fianchetto against d5."],
        ["d5", "The principled break anyway."],
        ["exd5", "Trade — the g2 bishop will bear on the long diagonal."],
        ["Nxd5", "Recapture with a centralized knight."],
        ["Bg2", "The fianchetto hits d5 and b7."],
        ["Nxc3", "Trade before losing time to the pressure."],
        ["bxc3", "Recapture toward the center; the pawn duo controls d4."],
        ["Nc6", "Develop."],
        ["Nf3", "Develop and restrain ...e4."],
        ["Bd6", "Point at the kingside, holding e5."],
        ["O-O", "Castle behind the fianchetto wall."],
        ["O-O", "Black castles."],
        ["d3", "Complete the structure; c1's bishop gets options."],
        ["Re8", "Support e5 down the half-open file."],
        ["Rb1", "The other point of bxc3 — pressure on b7 forever."],
        ["Rb8", "Black defends passively; White keeps a pleasant grind."],
      ],
    },
    {
      rank: 4,
      name: "2...Bc5 3.Nf3 d6",
      moves: [
        ["e4", "Take the center."],
        ["e5", "Symmetrical reply."],
        ["Nc3", "The Vienna."],
        ["Bc5", "Quick development, delaying ...Nf6."],
        ["Nf3", "Attack e5 — Black must react."],
        ["d6", "Hold e5 solidly."],
        ["d4", "Open the center while better developed."],
        ["exd4", "Forced trade to avoid losing e5."],
        ["Nxd4", "Recapture with a dominant knight."],
        ["Nf6", "Develop and pressure e4."],
        ["Bg5", "Pin the knight — awkward for Black already."],
        ["h6", "Put the question to the bishop."],
        ["Bh4", "Maintain the pin; ...g5 would wreck Black's king."],
        ["Nc6", "Challenge the strong d4 knight."],
        ["Nxc6", "Trade and damage Black's queenside structure."],
        ["bxc6", "Recapture, accepting the split pawns."],
        ["Bc4", "Classic diagonal, hitting f7."],
        ["O-O", "Black castles."],
        ["Qd3", "Connect and aim pieces at the kingside."],
        ["Re8", "Activate the rook; White retains the better structure."],
      ],
    },
    {
      rank: 5,
      name: "Frankenstein-Dracula: 3.Bc4 Nxe4",
      moves: [
        ["e4", "Take the center."],
        ["e5", "Symmetrical reply."],
        ["Nc3", "The Vienna: develop, keeping the f-pawn free."],
        ["Nf6", "The most common reply, eyeing e4."],
        ["Bc4", "The quiet-looking alternative to f4 — with hidden teeth."],
        ["Nxe4", "The critical test: the fork trick — Nxe4 Qh5 is the real fight."],
        ["Qh5", "The point: threaten mate on f7 and hang the e4 knight."],
        ["Nd6", "The only good square: block nothing, hit the c4 bishop."],
        ["Bb3", "Keep the bishop; the threats continue."],
        ["Nc6", "Defend e5 the greedy way — inviting the storm."],
        ["Nb5", "The monster threat: Nxc7+ forking king and rook."],
        ["g6", "Forced: the queen must be pushed off h5 first."],
        ["Qf3", "Renew the f7 threat from a new angle."],
        ["f5", "Block the diagonal — again forced."],
        ["Qd5", "Third wave: f7 falls unless Black gives the exchange."],
        ["Qe7", "Cover f7 and accept what's coming on c7."],
        ["Nxc7+", "Take the fork: king and rook."],
        ["Kd8", "Forced sidestep."],
        ["Nxa8", "Win the exchange — but the knight is trapped in the corner."],
        ["b6", "The famous tabiya: Black plays ...Bb7 and hunts the a8 knight."],
      ],
    },
    {
      rank: 6,
      name: "Gambit Accepted: 3...exf4 4.e5",
      moves: [
        ["e4", "Take the center."],
        ["e5", "Symmetrical reply."],
        ["Nc3", "The Vienna."],
        ["Nf6", "The main reply."],
        ["f4", "The Vienna Gambit."],
        ["exf4", "Accepting is the critical mistake the Vienna player must punish."],
        ["e5", "The punishment: the f6 knight has no good square."],
        ["Ng8", "The retreat — humiliating but forced (…Qe7 pins are met by Qe2)."],
        ["Nf3", "Develop with a big lead and cover the Qh4+ check forever."],
        ["d6", "Strike at the cramping e5 pawn."],
        ["d4", "Hold the spearhead with the full center."],
        ["dxe5", "Trade before White consolidates."],
        ["Nxe5", "Recapture with a strong knight — d4 stays intact."],
        ["Bd6", "Develop against the proud e5 knight."],
        ["Bxf4", "Regain the gambit pawn with interest in development."],
        ["Ne7", "Belated development toward safety."],
        ["Bc4", "The classic diagonal — f7 is sensitive again."],
        ["O-O", "Black castles out of the center at last."],
        ["O-O", "White castles; the lead in development persists."],
        ["Nbc6", "Challenge the e5 knight; White is simply better."],
      ],
    },
  ],
};
