// Validates every catalog line with chess.js (legality + canonical SAN) and
// writes two files:
//   - supabase/seed.sql: the full catalog, for fresh installs (run after schema.sql).
//   - supabase/migrations/2026-07-20-curated-lines.sql: sync migration for live
//     databases. Diffs the catalog against the DB by (slug, rank): replaces the
//     moves of lines whose SAN sequence changed (and resets their SRS cards so
//     users relearn the corrected content), deletes lines removed from the
//     catalog, and syncs names/explanations in place. Idempotent — re-running
//     it against an already-synced DB changes nothing.
// Historical migrations (2026-07-16, 2026-07-17) are not regenerated.
// Run with: node scripts/generate-seed.mjs
import { Chess } from "chess.js";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { catalog } from "./catalog/index.mjs";

const MIGRATION_FILE = "supabase/migrations/2026-07-20-curated-lines.sql";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const errors = [];
const notes = [];

function esc(text) {
  return text.replaceAll("'", "''");
}

// Validates the line's moves with chess.js and returns them in canonical SAN.
// Pushes to the shared errors/notes arrays.
function validateLine(opening, line) {
  const chess = new Chess();
  const moves = [];
  line.moves.forEach(([san, why], i) => {
    const ply = i + 1;
    let move;
    try {
      move = chess.move(san);
    } catch {
      errors.push(
        `${opening.slug} / "${line.name}" ply ${ply}: illegal or ambiguous move "${san}" (FEN: ${chess.fen()})`,
      );
      return;
    }
    if (move.san !== san) {
      notes.push(
        `${opening.slug} / "${line.name}" ply ${ply}: normalized "${san}" -> "${move.san}"`,
      );
    }
    moves.push([move.san, why]);
  });

  if (line.moves.length !== 20) {
    notes.push(
      `${opening.slug} / "${line.name}": ${line.moves.length} plies (expected 20)`,
    );
  }
  return moves;
}

function openingInsert(opening) {
  const colors = `{${opening.playableColors.join(",")}}`;
  const keys = `{${opening.detectionKeys.map((k) => `"${k}"`).join(",")}}`;
  return (
    `insert into public.openings (slug, name, eco, playable_colors, detection_keys) values ` +
    `('${esc(opening.slug)}', '${esc(opening.name)}', '${opening.eco}', '${colors}', '${esc(keys)}');`
  );
}

function lineInserts(opening, line, moves) {
  const rows = moves.map(
    ([san, why], i) => `  (${i + 1}, '${san}', '${esc(why)}')`,
  );
  return [
    `insert into public.opening_lines (opening_id, name, rank) values ` +
      `((select id from public.openings where slug = '${esc(opening.slug)}'), '${esc(line.name)}', ${line.rank});`,
    `insert into public.line_moves (line_id, ply, san, explanation)`,
    `select ol.id, v.ply, v.san, v.explanation from (values`,
    rows.join(",\n"),
    `) as v(ply, san, explanation)`,
    `join public.opening_lines ol on true ` +
      `join public.openings o on o.id = ol.opening_id ` +
      `where o.slug = '${esc(opening.slug)}' and ol.rank = ${line.rank};`,
    "",
  ];
}

// Validate everything once; keep canonical moves per (slug, rank).
const validated = new Map();
for (const opening of catalog) {
  const ranks = new Set();
  for (const line of opening.lines) {
    if (ranks.has(line.rank)) {
      errors.push(`${opening.slug}: duplicate rank ${line.rank}`);
    }
    ranks.add(line.rank);
    validated.set(`${opening.slug}#${line.rank}`, validateLine(opening, line));
  }
  if (opening.lines.length < 3 || opening.lines.length > 6) {
    errors.push(
      `${opening.slug}: ${opening.lines.length} lines (must be 3-6 per README quality policy)`,
    );
  }
}

// ---------------------------------------------------------------------------
// Full seed (fresh installs)
// ---------------------------------------------------------------------------
const seed = [];
seed.push("-- ============================================================================");
seed.push("-- Zephyriov — Opening catalog seed (generated by scripts/generate-seed.mjs)");
seed.push("-- Every line has been validated as a legal move sequence with chess.js and");
seed.push("-- audited with Stockfish (scripts/audit-lines.mjs) — see README.");
seed.push("-- Run once, after supabase/schema.sql, in the Supabase SQL editor.");
seed.push("-- ============================================================================");
seed.push("begin;");
seed.push("");
for (const opening of catalog) {
  seed.push(`-- ${opening.name} (${opening.eco})`);
  seed.push(openingInsert(opening));
  for (const line of opening.lines) {
    const moves = validated.get(`${opening.slug}#${line.rank}`);
    seed.push(...lineInserts(opening, line, moves));
  }
}
seed.push("commit;");

// ---------------------------------------------------------------------------
// Curated-lines sync migration (live databases)
// ---------------------------------------------------------------------------
const mig = [];
mig.push("-- ============================================================================");
mig.push("-- Zephyriov migration 2026-07-20: curated opening lines");
mig.push("-- (generated by scripts/generate-seed.mjs — do not edit by hand)");
mig.push("--");
mig.push("-- Syncs a live database to the audited catalog (see README 'Metodología de");
mig.push("-- curaduría'). By (opening slug, rank):");
mig.push("--   1. deletes lines removed from the catalog (cascade removes their moves,");
mig.push("--      SRS cards and session history),");
mig.push("--   2. inserts lines that don't exist yet,");
mig.push("--   3. syncs line names,");
mig.push("--   4. replaces all moves of lines whose SAN sequence changed,");
mig.push("--   5. syncs explanations of unchanged lines in place,");
mig.push("--   6. resets the SRS cards of changed lines (state='new', interval 0,");
mig.push("--      unlocked_moves back to the user's moves_per_block) — the memorized");
mig.push("--      content changed, so scheduling must restart,");
mig.push("--   7. creates missing cards for users already studying an opening.");
mig.push("--");
mig.push("-- Idempotent: safe to paste more than once (second run changes nothing).");
mig.push("-- ============================================================================");
mig.push("begin;");
mig.push("");
mig.push("create temp table _catalog (");
mig.push("  slug text, rank smallint, line_name text, ply smallint, san text, explanation text");
mig.push(") on commit drop;");
mig.push("");
mig.push("insert into _catalog (slug, rank, line_name, ply, san, explanation) values");
const rows = [];
for (const opening of catalog) {
  for (const line of opening.lines) {
    const moves = validated.get(`${opening.slug}#${line.rank}`);
    moves.forEach(([san, why], i) => {
      rows.push(
        `('${esc(opening.slug)}', ${line.rank}, '${esc(line.name)}', ${i + 1}, '${san}', '${esc(why)}')`,
      );
    });
  }
}
mig.push(rows.join(",\n") + ";");
mig.push("");
mig.push("-- Lines whose move sequence differs from the catalog (or that are missing).");
mig.push("create temp table _changed on commit drop as");
mig.push("select c.slug, c.rank");
mig.push("from (select distinct slug, rank from _catalog) c");
mig.push("join public.openings o on o.slug = c.slug");
mig.push("left join public.opening_lines ol on ol.opening_id = o.id and ol.rank = c.rank");
mig.push("where ol.id is null");
mig.push("   or (select string_agg(lm.san, ' ' order by lm.ply)");
mig.push("       from public.line_moves lm where lm.line_id = ol.id)");
mig.push("      is distinct from");
mig.push("      (select string_agg(c2.san, ' ' order by c2.ply)");
mig.push("       from _catalog c2 where c2.slug = c.slug and c2.rank = c.rank);");
mig.push("");
mig.push("-- 1. delete lines removed from the catalog");
mig.push("delete from public.opening_lines ol");
mig.push("using public.openings o");
mig.push("where o.id = ol.opening_id");
mig.push("  and not exists (select 1 from _catalog c where c.slug = o.slug and c.rank = ol.rank);");
mig.push("");
mig.push("-- 2. insert lines new to the database");
mig.push("insert into public.opening_lines (opening_id, name, rank)");
mig.push("select o.id, c.line_name, c.rank");
mig.push("from (select distinct slug, rank, line_name from _catalog) c");
mig.push("join public.openings o on o.slug = c.slug");
mig.push("on conflict (opening_id, rank) do nothing;");
mig.push("");
mig.push("-- 3. sync line names");
mig.push("update public.opening_lines ol");
mig.push("set name = c.line_name");
mig.push("from public.openings o,");
mig.push("     (select distinct slug, rank, line_name from _catalog) c");
mig.push("where ol.opening_id = o.id and o.slug = c.slug and ol.rank = c.rank");
mig.push("  and ol.name is distinct from c.line_name;");
mig.push("");
mig.push("-- 4. replace the moves of changed lines");
mig.push("delete from public.line_moves lm");
mig.push("using public.opening_lines ol, public.openings o, _changed ch");
mig.push("where lm.line_id = ol.id and ol.opening_id = o.id");
mig.push("  and o.slug = ch.slug and ol.rank = ch.rank;");
mig.push("");
mig.push("insert into public.line_moves (line_id, ply, san, explanation)");
mig.push("select ol.id, c.ply, c.san, c.explanation");
mig.push("from _catalog c");
mig.push("join _changed ch on ch.slug = c.slug and ch.rank = c.rank");
mig.push("join public.openings o on o.slug = c.slug");
mig.push("join public.opening_lines ol on ol.opening_id = o.id and ol.rank = c.rank;");
mig.push("");
mig.push("-- 5. sync explanations of unchanged lines");
mig.push("update public.line_moves lm");
mig.push("set explanation = c.explanation");
mig.push("from public.opening_lines ol, public.openings o, _catalog c");
mig.push("where lm.line_id = ol.id and ol.opening_id = o.id");
mig.push("  and o.slug = c.slug and ol.rank = c.rank and lm.ply = c.ply");
mig.push("  and lm.explanation is distinct from c.explanation;");
mig.push("");
mig.push("-- 6. reset SRS cards of changed lines");
mig.push("update public.user_lines ul");
mig.push("set state = 'new', interval_days = 0, due_date = current_date,");
mig.push("    reps = 0, lapses = 0, last_result = null,");
mig.push("    unlocked_moves = p.moves_per_block");
mig.push("from public.profiles p, public.opening_lines ol, public.openings o, _changed ch");
mig.push("where p.user_id = ul.user_id");
mig.push("  and ul.line_id = ol.id and ol.opening_id = o.id");
mig.push("  and o.slug = ch.slug and ol.rank = ch.rank;");
mig.push("");
mig.push("-- 7. create missing cards for openings users already study");
mig.push("insert into public.user_lines (user_id, line_id, unlocked_moves)");
mig.push("select uo.user_id, ol.id, p.moves_per_block");
mig.push("from public.user_openings uo");
mig.push("join public.opening_lines ol on ol.opening_id = uo.opening_id");
mig.push("join public.profiles p on p.user_id = uo.user_id");
mig.push("where uo.is_active");
mig.push("on conflict (user_id, line_id) do nothing;");
mig.push("");
mig.push("commit;");

if (notes.length) {
  console.log("Notes:");
  for (const n of notes) console.log("  -", n);
}

if (errors.length) {
  console.error(`\n${errors.length} error(s):`);
  for (const e of errors) console.error("  -", e);
  process.exit(1);
}

writeFileSync(join(root, "supabase", "seed.sql"), seed.join("\n") + "\n");
writeFileSync(join(root, MIGRATION_FILE), mig.join("\n") + "\n");
const lineCount = catalog.reduce((a, o) => a + o.lines.length, 0);
const moveCount = catalog.reduce(
  (a, o) => a + o.lines.reduce((b, l) => b + l.moves.length, 0),
  0,
);
console.log(
  `\nOK: ${catalog.length} openings, ${lineCount} lines, ${moveCount} moves -> supabase/seed.sql + ${MIGRATION_FILE}`,
);
