// Validates every catalog line with chess.js (legality + canonical SAN) and
// writes two files:
//   - supabase/seed.sql: the full catalog, for fresh installs (run after schema.sql).
//   - supabase/migrations/2026-07-17-six-lines-and-new-openings.sql: delta for
//     live databases seeded before 2026-07-17 (rank 5-6 lines + the two new
//     openings + the wider rank constraint + user_lines backfill). Safe to
//     re-paste: every statement is conditional or "on conflict do nothing".
// Run with: node scripts/generate-seed.mjs
import { Chess } from "chess.js";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { catalog } from "./catalog/index.mjs";

// What the 2026-07-17 delta migration must carry: openings added that day get
// all their lines; pre-existing openings only their new rank 5-6 lines.
const DELTA = {
  file: "supabase/migrations/2026-07-17-six-lines-and-new-openings.sql",
  newOpeningSlugs: ["hyper-accelerated-dragon", "kings-gambit"],
  minRankForExisting: 5,
};

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const errors = [];
const notes = [];

function esc(text) {
  return text.replaceAll("'", "''");
}

// Validates the line's moves with chess.js and returns them in canonical SAN.
// Pushes to the shared errors/notes arrays.
function validateLine(opening, line) {
  const chess = new Chess();
  const moves = [];
  line.moves.forEach(([san, why], i) => {
    const ply = i + 1;
    let move;
    try {
      move = chess.move(san);
    } catch {
      errors.push(
        `${opening.slug} / "${line.name}" ply ${ply}: illegal or ambiguous move "${san}" (FEN: ${chess.fen()})`,
      );
      return;
    }
    if (move.san !== san) {
      notes.push(
        `${opening.slug} / "${line.name}" ply ${ply}: normalized "${san}" -> "${move.san}"`,
      );
    }
    moves.push([move.san, why]);
  });

  if (line.moves.length !== 20) {
    notes.push(
      `${opening.slug} / "${line.name}": ${line.moves.length} plies (expected 20)`,
    );
  }
  return moves;
}

function openingInsert(opening, { idempotent }) {
  const colors = `{${opening.playableColors.join(",")}}`;
  const keys = `{${opening.detectionKeys.map((k) => `"${k}"`).join(",")}}`;
  return (
    `insert into public.openings (slug, name, eco, playable_colors, detection_keys) values ` +
    `('${esc(opening.slug)}', '${esc(opening.name)}', '${opening.eco}', '${colors}', '${esc(keys)}')` +
    (idempotent ? ` on conflict (slug) do nothing;` : `;`)
  );
}

function lineInserts(opening, line, moves, { idempotent }) {
  const rows = moves.map(
    ([san, why], i) => `  (${i + 1}, '${san}', '${esc(why)}')`,
  );
  return [
    `insert into public.opening_lines (opening_id, name, rank) values ` +
      `((select id from public.openings where slug = '${esc(opening.slug)}'), '${esc(line.name)}', ${line.rank})` +
      (idempotent ? ` on conflict (opening_id, rank) do nothing;` : `;`),
    `insert into public.line_moves (line_id, ply, san, explanation)`,
    `select ol.id, v.ply, v.san, v.explanation from (values`,
    rows.join(",\n"),
    `) as v(ply, san, explanation)`,
    `join public.opening_lines ol on true ` +
      `join public.openings o on o.id = ol.opening_id ` +
      `where o.slug = '${esc(opening.slug)}' and ol.rank = ${line.rank}` +
      (idempotent ? ` on conflict (line_id, ply) do nothing;` : `;`),
    "",
  ];
}

// Validate everything once; keep canonical moves per (slug, rank).
const validated = new Map();
for (const opening of catalog) {
  const ranks = new Set();
  for (const line of opening.lines) {
    if (ranks.has(line.rank)) {
      errors.push(`${opening.slug}: duplicate rank ${line.rank}`);
    }
    ranks.add(line.rank);
    validated.set(`${opening.slug}#${line.rank}`, validateLine(opening, line));
  }
  if (opening.lines.length !== 6) {
    notes.push(`${opening.slug}: ${opening.lines.length} lines (expected 6)`);
  }
}

// ---------------------------------------------------------------------------
// Full seed (fresh installs)
// ---------------------------------------------------------------------------
const seed = [];
seed.push("-- ============================================================================");
seed.push("-- Zephyriov — Opening catalog seed (generated by scripts/generate-seed.mjs)");
seed.push("-- Every line has been validated as a legal move sequence with chess.js.");
seed.push("-- Run once, after supabase/schema.sql, in the Supabase SQL editor.");
seed.push("-- ============================================================================");
seed.push("begin;");
seed.push("");
for (const opening of catalog) {
  seed.push(`-- ${opening.name} (${opening.eco})`);
  seed.push(openingInsert(opening, { idempotent: false }));
  for (const line of opening.lines) {
    const moves = validated.get(`${opening.slug}#${line.rank}`);
    seed.push(...lineInserts(opening, line, moves, { idempotent: false }));
  }
}
seed.push("commit;");

// ---------------------------------------------------------------------------
// Delta migration (live databases seeded before 2026-07-17)
// ---------------------------------------------------------------------------
const delta = [];
delta.push("-- ============================================================================");
delta.push("-- Zephyriov migration 2026-07-17: 6 lines per opening + 2 new openings");
delta.push("-- (generated by scripts/generate-seed.mjs — do not edit by hand)");
delta.push("--");
delta.push("-- For databases seeded BEFORE 2026-07-17. Fresh installs don't need this:");
delta.push("-- schema.sql + seed.sql already contain everything.");
delta.push("--");
delta.push("-- Does, in order: (1) widens the opening_lines.rank constraint to 1-6,");
delta.push("-- (2) inserts the two new openings, (3) inserts only the NEW lines");
delta.push("-- (rank 5-6 of existing openings + all lines of the new ones), and");
delta.push("-- (4) creates the missing SRS cards for openings users already study,");
delta.push("-- mirroring what addOpening does (lib/actions/library.ts). New cards are");
delta.push("-- born state='new' and enter the daily session pool without changing the");
delta.push("-- session/progression behavior.");
delta.push("--");
delta.push("-- Safe to paste more than once: every statement is conditional.");
delta.push("-- ============================================================================");
delta.push("begin;");
delta.push("");
delta.push("-- 1. rank constraint 1-4 -> 1-6");
delta.push("alter table public.opening_lines drop constraint if exists opening_lines_rank_check;");
delta.push("alter table public.opening_lines add constraint opening_lines_rank_check check (rank between 1 and 6);");
delta.push("");
delta.push("-- 2 & 3. new openings and new lines");
for (const opening of catalog) {
  const isNewOpening = DELTA.newOpeningSlugs.includes(opening.slug);
  const newLines = opening.lines.filter(
    (l) => isNewOpening || l.rank >= DELTA.minRankForExisting,
  );
  if (!newLines.length) continue;
  delta.push(`-- ${opening.name} (${opening.eco})${isNewOpening ? " — new opening" : ""}`);
  if (isNewOpening) delta.push(openingInsert(opening, { idempotent: true }));
  for (const line of newLines) {
    const moves = validated.get(`${opening.slug}#${line.rank}`);
    delta.push(...lineInserts(opening, line, moves, { idempotent: true }));
  }
}
delta.push("-- 4. backfill SRS cards for openings already in study");
delta.push("insert into public.user_lines (user_id, line_id, unlocked_moves)");
delta.push("select uo.user_id, ol.id, p.moves_per_block");
delta.push("from public.user_openings uo");
delta.push("join public.opening_lines ol on ol.opening_id = uo.opening_id");
delta.push("join public.profiles p on p.user_id = uo.user_id");
delta.push("where uo.is_active");
delta.push("on conflict (user_id, line_id) do nothing;");
delta.push("");
delta.push("commit;");

if (notes.length) {
  console.log("Notes:");
  for (const n of notes) console.log("  -", n);
}

if (errors.length) {
  console.error(`\n${errors.length} error(s):`);
  for (const e of errors) console.error("  -", e);
  process.exit(1);
}

writeFileSync(join(root, "supabase", "seed.sql"), seed.join("\n") + "\n");
writeFileSync(join(root, DELTA.file), delta.join("\n") + "\n");
const lineCount = catalog.reduce((a, o) => a + o.lines.length, 0);
const moveCount = catalog.reduce(
  (a, o) => a + o.lines.reduce((b, l) => b + l.moves.length, 0),
  0,
);
console.log(
  `\nOK: ${catalog.length} openings, ${lineCount} lines, ${moveCount} moves -> supabase/seed.sql + ${DELTA.file}`,
);
