// Validates every catalog line with chess.js (legality + canonical SAN) and
// writes supabase/seed.sql. Run with: node scripts/generate-seed.mjs
import { Chess } from "chess.js";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { catalog } from "./catalog/index.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const errors = [];
const notes = [];

function esc(text) {
  return text.replaceAll("'", "''");
}

const sql = [];
sql.push("-- ============================================================================");
sql.push("-- Zephyriov — Opening catalog seed (generated by scripts/generate-seed.mjs)");
sql.push("-- Every line has been validated as a legal move sequence with chess.js.");
sql.push("-- Run once, after supabase/schema.sql, in the Supabase SQL editor.");
sql.push("-- ============================================================================");
sql.push("begin;");
sql.push("");

for (const opening of catalog) {
  const colors = `{${opening.playableColors.join(",")}}`;
  const keys = `{${opening.detectionKeys.map((k) => `"${k}"`).join(",")}}`;
  sql.push(`-- ${opening.name} (${opening.eco})`);
  sql.push(
    `insert into public.openings (slug, name, eco, playable_colors, detection_keys) values ` +
      `('${esc(opening.slug)}', '${esc(opening.name)}', '${opening.eco}', '${colors}', '${esc(keys)}');`,
  );

  const ranks = new Set();
  for (const line of opening.lines) {
    if (ranks.has(line.rank)) {
      errors.push(`${opening.slug}: duplicate rank ${line.rank}`);
    }
    ranks.add(line.rank);

    const chess = new Chess();
    const rows = [];
    line.moves.forEach(([san, why], i) => {
      const ply = i + 1;
      let move;
      try {
        move = chess.move(san);
      } catch {
        errors.push(
          `${opening.slug} / "${line.name}" ply ${ply}: illegal or ambiguous move "${san}" (FEN: ${chess.fen()})`,
        );
        return;
      }
      if (move.san !== san) {
        notes.push(
          `${opening.slug} / "${line.name}" ply ${ply}: normalized "${san}" -> "${move.san}"`,
        );
      }
      rows.push(`  (${ply}, '${move.san}', '${esc(why)}')`);
    });

    if (line.moves.length !== 20) {
      notes.push(
        `${opening.slug} / "${line.name}": ${line.moves.length} plies (expected 20)`,
      );
    }

    sql.push(
      `insert into public.opening_lines (opening_id, name, rank) values ` +
        `((select id from public.openings where slug = '${esc(opening.slug)}'), '${esc(line.name)}', ${line.rank});`,
    );
    sql.push(
      `insert into public.line_moves (line_id, ply, san, explanation)`,
    );
    sql.push(
      `select ol.id, v.ply, v.san, v.explanation from (values`,
    );
    sql.push(rows.join(",\n"));
    sql.push(
      `) as v(ply, san, explanation)`,
    );
    sql.push(
      `join public.opening_lines ol on true ` +
        `join public.openings o on o.id = ol.opening_id ` +
        `where o.slug = '${esc(opening.slug)}' and ol.rank = ${line.rank};`,
    );
    sql.push("");
  }
}

sql.push("commit;");

if (notes.length) {
  console.log("Notes:");
  for (const n of notes) console.log("  -", n);
}

if (errors.length) {
  console.error(`\n${errors.length} error(s):`);
  for (const e of errors) console.error("  -", e);
  process.exit(1);
}

writeFileSync(join(root, "supabase", "seed.sql"), sql.join("\n") + "\n");
const lineCount = catalog.reduce((a, o) => a + o.lines.length, 0);
const moveCount = catalog.reduce(
  (a, o) => a + o.lines.reduce((b, l) => b + l.moves.length, 0),
  0,
);
console.log(
  `\nOK: ${catalog.length} openings, ${lineCount} lines, ${moveCount} moves -> supabase/seed.sql`,
);
