-- ============================================================================
-- Zephyriov migration 2026-07-17: 6 lines per opening + 2 new openings
-- (generated by scripts/generate-seed.mjs — do not edit by hand)
--
-- For databases seeded BEFORE 2026-07-17. Fresh installs don't need this:
-- schema.sql + seed.sql already contain everything.
--
-- Does, in order: (1) widens the opening_lines.rank constraint to 1-6,
-- (2) inserts the two new openings, (3) inserts only the NEW lines
-- (rank 5-6 of existing openings + all lines of the new ones), and
-- (4) creates the missing SRS cards for openings users already study,
-- mirroring what addOpening does (lib/actions/library.ts). New cards are
-- born state='new' and enter the daily session pool without changing the
-- session/progression behavior.
--
-- Safe to paste more than once: every statement is conditional.
-- ============================================================================
begin;

-- 1. rank constraint 1-4 -> 1-6
alter table public.opening_lines drop constraint if exists opening_lines_rank_check;
alter table public.opening_lines add constraint opening_lines_rank_check check (rank between 1 and 6);

-- 2 & 3. new openings and new lines
-- Ponziani Opening (C44)
insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'ponziani'), 'Caro Gambit: 3...d5 4.Qa4 Bd7', 5) on conflict (opening_id, rank) do nothing;
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'Take the center.'),
  (2, 'e5', 'Symmetrical reply.'),
  (3, 'Nf3', 'Attack e5 and develop.'),
  (4, 'Nc6', 'Defend e5.'),
  (5, 'c3', 'Prepare the d4 break.'),
  (6, 'd5', 'The critical counter, striking e4.'),
  (7, 'Qa4', 'The point of the Ponziani: pin the c6 knight.'),
  (8, 'Bd7', 'The Caro Gambit: calmly break the pin and offer e5.'),
  (9, 'exd5', 'Take the center pawn while the offer stands.'),
  (10, 'Nd4', 'The trick: the ''pinned'' knight jumps — ...Nc2+ forking is the threat.'),
  (11, 'Qd1', 'Retreat and cover c2; Qxd7+ loses the queen to ...Qxd7.'),
  (12, 'Nxf3+', 'Trade off the defender of e5 and d4.'),
  (13, 'Qxf3', 'Recapture; White is a pawn up but behind in development.'),
  (14, 'Nf6', 'Develop with pressure on d5.'),
  (15, 'Bc4', 'Hold the extra d5 pawn the natural way.'),
  (16, 'Bd6', 'Aim at h2 and prepare ...O-O — full compensation play.'),
  (17, 'd3', 'Open the c1 bishop and solidify.'),
  (18, 'O-O', 'King safety; Black''s activity balances the pawn.'),
  (19, 'O-O', 'White castles too.'),
  (20, 'Bg4', 'Hit the queen and probe d5''s defenses — a rich fight.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'ponziani' and ol.rank = 5 on conflict (line_id, ply) do nothing;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'ponziani'), 'Leonhardt: 3...d5 4.Qa4 Nf6', 6) on conflict (opening_id, rank) do nothing;
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'Take the center.'),
  (2, 'e5', 'Symmetrical reply.'),
  (3, 'Nf3', 'Attack e5 and develop.'),
  (4, 'Nc6', 'Defend e5.'),
  (5, 'c3', 'Prepare the d4 break.'),
  (6, 'd5', 'The critical counter.'),
  (7, 'Qa4', 'Pin the c6 knight against e5/d5.'),
  (8, 'Nf6', 'The Leonhardt: develop and ignore the threat — a true gambit.'),
  (9, 'Nxe5', 'Call the bluff: take, exploiting the pinned defender.'),
  (10, 'Nxe4', 'Grab the pawn back in kind, keeping maximum activity.'),
  (11, 'Nxc6', 'Win the tangled knight before Black consolidates.'),
  (12, 'bxc6', 'Recapture, opening the b-file for counterplay.'),
  (13, 'Qxc6+', 'Collect a second pawn with check — the punishing continuation.'),
  (14, 'Bd7', 'Block and develop with tempo on the queen.'),
  (15, 'Qxd5', 'Take a third pawn — greedy but theory approves.'),
  (16, 'Nf6', 'Hit the queen again; Black plays for raw initiative.'),
  (17, 'Qd3', 'Step back to safety, ready to return material for development.'),
  (18, 'Bd6', 'Point everything at the kingside.'),
  (19, 'Be2', 'Catch up in development before the storm hits.'),
  (20, 'O-O', 'Black castles; White is up material but must defend precisely.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'ponziani' and ol.rank = 6 on conflict (line_id, ply) do nothing;

-- Caro-Kann: Fantasy Variation (B12)
insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'caro-kann-fantasy'), 'Early Queen: 3...Qb6', 5) on conflict (opening_id, rank) do nothing;
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'Take the center.'),
  (2, 'c6', 'The Caro-Kann.'),
  (3, 'd4', 'Build the center.'),
  (4, 'd5', 'Challenge e4.'),
  (5, 'f3', 'The Fantasy setup.'),
  (6, 'Qb6', 'Hit d4 and b2 at once before committing any pawn.'),
  (7, 'Nc3', 'Develop and defend b2 tactically — grabbing it is poison.'),
  (8, 'dxe4', 'Take now that d4 is the only real target.'),
  (9, 'fxe4', 'Recapture, keeping the broad center.'),
  (10, 'e5', 'The central strike, hitting d4 a second time.'),
  (11, 'Nf3', 'Defend d4 by developing, as always in the Fantasy.'),
  (12, 'exd4', 'Win the pawn — White gets activity in exchange.'),
  (13, 'Nxd4', 'Recapture; the b6 queen bites on granite now.'),
  (14, 'Bc5', 'Pile on d4 and develop with tempo.'),
  (15, 'Be3', 'Meet the pressure; b2 is still tactically off-limits.'),
  (16, 'Nf6', 'Develop and decline the bait for good.'),
  (17, 'Bc4', 'The f7 diagonal — White''s lead in development takes shape.'),
  (18, 'O-O', 'King safety before the center opens further.'),
  (19, 'O-O', 'White castles; every piece is aimed at the kingside.'),
  (20, 'Nbd7', 'Complete development — a tense, balanced middlegame.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'caro-kann-fantasy' and ol.rank = 5 on conflict (line_id, ply) do nothing;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'caro-kann-fantasy'), 'Main Line Pawn Grab: 5...exd4', 6) on conflict (opening_id, rank) do nothing;
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'Take the center.'),
  (2, 'c6', 'The Caro-Kann.'),
  (3, 'd4', 'Build the center.'),
  (4, 'd5', 'Challenge e4.'),
  (5, 'f3', 'The Fantasy setup.'),
  (6, 'dxe4', 'The critical test.'),
  (7, 'fxe4', 'Recapture with the broad center.'),
  (8, 'e5', 'Strike before White consolidates.'),
  (9, 'Nf3', 'Defend d4 by developing.'),
  (10, 'exd4', 'The greedy branch: take and dare White to prove it.'),
  (11, 'Bc4', 'Prove it: hit f7 and lead in development — the Fantasy gambit.'),
  (12, 'Be6', 'The solid defense: neutralize the dangerous bishop.'),
  (13, 'Bxe6', 'Trade — keeping the attack going costs too much.'),
  (14, 'fxe6', 'Recapture; the doubled e-pawns guard d5 and f5.'),
  (15, 'Qxd4', 'Regain the pawn with a dominant central queen.'),
  (16, 'Qxd4', 'Trade queens — the safest path with the weakened structure.'),
  (17, 'Nxd4', 'Recapture with a strong central knight eyeing e6.'),
  (18, 'Nf6', 'Develop with tempo on e4.'),
  (19, 'Nc3', 'Defend e4 and complete development.'),
  (20, 'Bc5', 'Active development against d4 — near-equal endgame.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'caro-kann-fantasy' and ol.rank = 6 on conflict (line_id, ply) do nothing;

-- French: Two Knights Variation (C00)
insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'french-two-knights'), 'Counterstrike: 3...c5', 5) on conflict (opening_id, rank) do nothing;
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'Take the center.'),
  (2, 'e6', 'The French Defense.'),
  (3, 'Nc3', 'Develop and cover e4.'),
  (4, 'd5', 'Challenge e4.'),
  (5, 'Nf3', 'The Two Knights setup.'),
  (6, 'c5', 'Strike the center immediately, French-style, before d4 exists.'),
  (7, 'exd5', 'Clarify the center while Black''s pieces are home.'),
  (8, 'exd5', 'Recapture, freeing the c8 bishop.'),
  (9, 'd4', 'Claim the center — an IQP battle is coming.'),
  (10, 'Nc6', 'Develop and hold c5.'),
  (11, 'Bb5', 'Pin, stepping up the pressure on the center.'),
  (12, 'Nf6', 'Develop; the d5 pawn is well covered.'),
  (13, 'O-O', 'King safety first.'),
  (14, 'Be7', 'Prepare to castle.'),
  (15, 'dxc5', 'Trade into the isolani structure White wants.'),
  (16, 'Bxc5', 'Recapture, developing again for free.'),
  (17, 'Bg5', 'The classic anti-IQP pin against d5''s defender.'),
  (18, 'O-O', 'Castle; piece activity must offset the isolated pawn.'),
  (19, 'Bxc6', 'Trade to fix Black with weak queenside pawns.'),
  (20, 'bxc6', 'Recapture — hanging pawns, open b-file: double-edged.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'french-two-knights' and ol.rank = 5 on conflict (line_id, ply) do nothing;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'french-two-knights'), 'Development: 3...Nc6', 6) on conflict (opening_id, rank) do nothing;
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'Take the center.'),
  (2, 'e6', 'The French Defense.'),
  (3, 'Nc3', 'Develop and cover e4.'),
  (4, 'd5', 'Challenge e4.'),
  (5, 'Nf3', 'The Two Knights setup.'),
  (6, 'Nc6', 'Pure development, keeping every pawn break in reserve.'),
  (7, 'd4', 'Build the full center while it''s free.'),
  (8, 'dxe4', 'Trade before the center gets overwhelming.'),
  (9, 'Nxe4', 'Recapture with a strong central knight.'),
  (10, 'Nf6', 'Challenge it immediately.'),
  (11, 'Nxf6+', 'Trade on White''s terms.'),
  (12, 'Qxf6', 'Recapture with the queen — ...Bd6 and ...O-O come fast.'),
  (13, 'Bd3', 'The kingside diagonal.'),
  (14, 'Bd6', 'Mirror it, eyeing h2.'),
  (15, 'O-O', 'King safety.'),
  (16, 'O-O', 'Black castles; development is complete and sound.'),
  (17, 'c3', 'Solidify d4 against the coming ...e5 break.'),
  (18, 'e5', 'The freeing break anyway — well-timed equality.'),
  (19, 'dxe5', 'Trade; refusing leaves the tension in Black''s favor.'),
  (20, 'Nxe5', 'Recapture; the symmetrical position holds no fear for Black.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'french-two-knights' and ol.rank = 6 on conflict (line_id, ply) do nothing;

-- Italian Game (C50)
insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'italian-game'), 'Giuoco Piano: Center Attack 5.d4', 5) on conflict (opening_id, rank) do nothing;
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'Take the center.'),
  (2, 'e5', 'Symmetrical reply.'),
  (3, 'Nf3', 'Attack e5 and develop.'),
  (4, 'Nc6', 'Defend e5.'),
  (5, 'Bc4', 'The Italian bishop.'),
  (6, 'Bc5', 'Mirror development.'),
  (7, 'c3', 'Prepare d4 with pawn support.'),
  (8, 'Nf6', 'Hit e4 rather than defend passively.'),
  (9, 'd4', 'The classical center attack — the old main line of the Giuoco.'),
  (10, 'exd4', 'Take; letting White keep d4-e4 for free is worse.'),
  (11, 'cxd4', 'Recapture with the ideal pawn duo, hitting the c5 bishop.'),
  (12, 'Bb4+', 'The saving check — without it Black is simply worse.'),
  (13, 'Bd2', 'The solid main line; 7.Nc3 is the wild Greco gambit.'),
  (14, 'Bxd2+', 'Trade — keeping the bishop loses time.'),
  (15, 'Nbxd2', 'Recapture, developing at the same time.'),
  (16, 'd5', 'The classical equalizer: strike e4 before the center rolls.'),
  (17, 'exd5', 'Take — protecting e4 leaves d4 weak.'),
  (18, 'Nxd5', 'Recapture with a fine blockading knight.'),
  (19, 'Qb3', 'The critical try: double-attack d5 and b7.'),
  (20, 'Nce7', 'The main defense: hold d5 with everything.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'italian-game' and ol.rank = 5 on conflict (line_id, ply) do nothing;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'italian-game'), 'Two Knights: Modern 4.d3', 6) on conflict (opening_id, rank) do nothing;
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'Take the center.'),
  (2, 'e5', 'Symmetrical reply.'),
  (3, 'Nf3', 'Attack e5 and develop.'),
  (4, 'Nc6', 'Defend e5.'),
  (5, 'Bc4', 'The Italian bishop.'),
  (6, 'Nf6', 'The Two Knights Defense.'),
  (7, 'd3', 'The modern choice at every level: keep the tension, skip 4.Ng5 theory.'),
  (8, 'Be7', 'Solid — avoid c3-d4 tempo hits on a c5 bishop.'),
  (9, 'O-O', 'King safety.'),
  (10, 'O-O', 'Black castles.'),
  (11, 'Re1', 'Standard e4 support before regrouping.'),
  (12, 'd6', 'Hold e5 and open the c8 bishop.'),
  (13, 'a4', 'Modern wing space — also readies Ba2 keeping the diagonal.'),
  (14, 'Na5', 'Trade-seeking: the knight hunts the strong c4 bishop.'),
  (15, 'Ba2', 'Preserve it — this bishop is White''s best piece.'),
  (16, 'c5', 'Grab queenside space and give the knight a home on c6 again.'),
  (17, 'c3', 'Prepare d4 and keep the a5 knight shut out of b3/c4.'),
  (18, 'Nc6', 'Return to the center — the a5 trip fixed the queenside terms.'),
  (19, 'Nbd2', 'The familiar Italian tour toward f1-g3.'),
  (20, 'Be6', 'Offer the trade to ease the position — the modern tabiya.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'italian-game' and ol.rank = 6 on conflict (line_id, ply) do nothing;

-- Ruy Lopez (C60)
insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'ruy-lopez'), 'Open Variation: 5...Nxe4', 5) on conflict (opening_id, rank) do nothing;
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'Take the center.'),
  (2, 'e5', 'Symmetrical reply.'),
  (3, 'Nf3', 'Attack e5 and develop.'),
  (4, 'Nc6', 'Defend e5.'),
  (5, 'Bb5', 'The Ruy Lopez.'),
  (6, 'a6', 'The Morphy Defense.'),
  (7, 'Ba4', 'Keep the pin option alive.'),
  (8, 'Nf6', 'Develop and counterattack e4.'),
  (9, 'O-O', 'Castle — e4 is only tactically defended.'),
  (10, 'Nxe4', 'The Open Variation: take the pawn and fight for the initiative.'),
  (11, 'd4', 'Open the center at once — White''s compensation is activity.'),
  (12, 'b5', 'Push the bishop back before it recaptures on c6.'),
  (13, 'Bb3', 'The bishop keeps eyeing f7 from its classic diagonal.'),
  (14, 'd5', 'Secure the e4 knight and free the c8 bishop — the Open''s backbone.'),
  (15, 'dxe5', 'Grab the e5 pawn; the advanced pawn cramps Black later.'),
  (16, 'Be6', 'Develop and overprotect d5 against the b3 bishop.'),
  (17, 'c3', 'Blunt ...Nc5-ideas hitting b3 and prepare Nbd2 to evict e4.'),
  (18, 'Be7', 'Sensible development; ...Bc5 is the sharper alternative.'),
  (19, 'Nbd2', 'Challenge the strong e4 knight — Black''s whole game hangs on it.'),
  (20, 'O-O', 'King safety; the fight revolves around the e4 outpost.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'ruy-lopez' and ol.rank = 5 on conflict (line_id, ply) do nothing;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'ruy-lopez'), 'Marshall Attack', 6) on conflict (opening_id, rank) do nothing;
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'Take the center.'),
  (2, 'e5', 'Symmetrical reply.'),
  (3, 'Nf3', 'Attack e5 and develop.'),
  (4, 'Nc6', 'Defend e5.'),
  (5, 'Bb5', 'The Ruy Lopez.'),
  (6, 'a6', 'The Morphy Defense.'),
  (7, 'Ba4', 'Keep the pin option alive.'),
  (8, 'Nf6', 'Develop and counterattack e4.'),
  (9, 'O-O', 'Castle.'),
  (10, 'Be7', 'Solid development, keeping ...b5 and ...d5 ideas in reserve.'),
  (11, 'Re1', 'Defend e4 and take the e-file.'),
  (12, 'b5', 'Push the bishop off the a4-e8 diagonal.'),
  (13, 'Bb3', 'Standard retreat toward f7.'),
  (14, 'O-O', 'Castle FIRST — delaying ...d6 keeps the d-pawn free for ...d5.'),
  (15, 'c3', 'Prepare d4; this is what the Marshall exploits.'),
  (16, 'd5', 'The Marshall Attack: sacrifice a pawn for a lasting kingside attack.'),
  (17, 'exd5', 'Accept — declining concedes easy equality.'),
  (18, 'Nxd5', 'Recapture and clear the way for ...Nxe5xe5 tricks.'),
  (19, 'Nxe5', 'Take the pawn; White banks the material.'),
  (20, 'Nxe5', 'Recapture — after Rxe5 c6 Black gets ...Bd6, ...Qh4 with a raging attack.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'ruy-lopez' and ol.rank = 6 on conflict (line_id, ply) do nothing;

-- Vienna Game (C25)
insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'vienna-game'), 'Frankenstein-Dracula: 3.Bc4 Nxe4', 5) on conflict (opening_id, rank) do nothing;
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'Take the center.'),
  (2, 'e5', 'Symmetrical reply.'),
  (3, 'Nc3', 'The Vienna: develop, keeping the f-pawn free.'),
  (4, 'Nf6', 'The most common reply, eyeing e4.'),
  (5, 'Bc4', 'The quiet-looking alternative to f4 — with hidden teeth.'),
  (6, 'Nxe4', 'The critical test: the fork trick — Nxe4 Qh5 is the real fight.'),
  (7, 'Qh5', 'The point: threaten mate on f7 and hang the e4 knight.'),
  (8, 'Nd6', 'The only good square: block nothing, hit the c4 bishop.'),
  (9, 'Bb3', 'Keep the bishop; the threats continue.'),
  (10, 'Nc6', 'Defend e5 the greedy way — inviting the storm.'),
  (11, 'Nb5', 'The monster threat: Nxc7+ forking king and rook.'),
  (12, 'g6', 'Forced: the queen must be pushed off h5 first.'),
  (13, 'Qf3', 'Renew the f7 threat from a new angle.'),
  (14, 'f5', 'Block the diagonal — again forced.'),
  (15, 'Qd5', 'Third wave: f7 falls unless Black gives the exchange.'),
  (16, 'Qe7', 'Cover f7 and accept what''s coming on c7.'),
  (17, 'Nxc7+', 'Take the fork: king and rook.'),
  (18, 'Kd8', 'Forced sidestep.'),
  (19, 'Nxa8', 'Win the exchange — but the knight is trapped in the corner.'),
  (20, 'b6', 'The famous tabiya: Black plays ...Bb7 and hunts the a8 knight.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'vienna-game' and ol.rank = 5 on conflict (line_id, ply) do nothing;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'vienna-game'), 'Gambit Accepted: 3...exf4 4.e5', 6) on conflict (opening_id, rank) do nothing;
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'Take the center.'),
  (2, 'e5', 'Symmetrical reply.'),
  (3, 'Nc3', 'The Vienna.'),
  (4, 'Nf6', 'The main reply.'),
  (5, 'f4', 'The Vienna Gambit.'),
  (6, 'exf4', 'Accepting is the critical mistake the Vienna player must punish.'),
  (7, 'e5', 'The punishment: the f6 knight has no good square.'),
  (8, 'Ng8', 'The retreat — humiliating but forced (…Qe7 pins are met by Qe2).'),
  (9, 'Nf3', 'Develop with a big lead and cover the Qh4+ check forever.'),
  (10, 'd6', 'Strike at the cramping e5 pawn.'),
  (11, 'd4', 'Hold the spearhead with the full center.'),
  (12, 'dxe5', 'Trade before White consolidates.'),
  (13, 'Nxe5', 'Recapture with a strong knight — d4 stays intact.'),
  (14, 'Bd6', 'Develop against the proud e5 knight.'),
  (15, 'Bxf4', 'Regain the gambit pawn with interest in development.'),
  (16, 'Ne7', 'Belated development toward safety.'),
  (17, 'Bc4', 'The classic diagonal — f7 is sensitive again.'),
  (18, 'O-O', 'Black castles out of the center at last.'),
  (19, 'O-O', 'White castles; the lead in development persists.'),
  (20, 'Nbc6', 'Challenge the e5 knight; White is simply better.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'vienna-game' and ol.rank = 6 on conflict (line_id, ply) do nothing;

-- London System (D02)
insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'london-system'), 'Steinitz Countergambit: 2...c5', 5) on conflict (opening_id, rank) do nothing;
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'd4', 'Take the center.'),
  (2, 'd5', 'Symmetrical reply.'),
  (3, 'Bf4', 'The London bishop.'),
  (4, 'c5', 'The immediate countergambit: hit d4 before White sets the wall.'),
  (5, 'e3', 'Decline calmly and keep the structure — taking helps Black.'),
  (6, 'Nc6', 'Develop with pressure on d4.'),
  (7, 'c3', 'The wall, as always.'),
  (8, 'Nf6', 'Natural development.'),
  (9, 'Nd2', 'Flexible London development, holding e4 and c4 ideas.'),
  (10, 'Bf5', 'Grab the good diagonal before ...e6 closes it.'),
  (11, 'Ngf3', 'Complete the setup.'),
  (12, 'Qb6', 'The point of Black''s order: b2 is attacked and Qb3 is harder now.'),
  (13, 'Qb3', 'Offer the trade anyway — the endgame slightly favors White.'),
  (14, 'c4', 'Black declines with tempo: hit the queen and clamp the queenside.'),
  (15, 'Qxb6', 'Trade on White''s terms before ...Qxb3 doubles White''s pawns.'),
  (16, 'axb6', 'Recapture; the open a-file and b6 targets are the trade-off.'),
  (17, 'Be2', 'Develop and prepare O-O; the c4 pawn cramps White slightly.'),
  (18, 'e6', 'Solidify and open the f8 bishop.'),
  (19, 'O-O', 'King safety.'),
  (20, 'Be7', 'Complete development — a subtle, balanced endgame battle.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'london-system' and ol.rank = 5 on conflict (line_id, ply) do nothing;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'london-system'), 'vs King''s Indian: ...g6 & ...d6', 6) on conflict (opening_id, rank) do nothing;
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'd4', 'Take the center.'),
  (2, 'Nf6', 'The Indian move order — no early ...d5.'),
  (3, 'Bf4', 'The London works against nearly everything — play it anyway.'),
  (4, 'g6', 'Black sets up a King''s Indian structure.'),
  (5, 'e3', 'The usual pyramid.'),
  (6, 'Bg7', 'The KID bishop.'),
  (7, 'Nf3', 'Develop.'),
  (8, 'd6', 'The KID point: prepare ...e5 against the London wall.'),
  (9, 'h3', 'Secure h2 for the bishop before ...Nh5 or ...e5 tricks.'),
  (10, 'O-O', 'Black castles.'),
  (11, 'Be2', 'Modest and correct: d3 would bite on granite against ...g6.'),
  (12, 'c5', 'Strike at d4 — the alternative plan to ...e5.'),
  (13, 'c3', 'Hold the wall.'),
  (14, 'Nc6', 'Develop and keep asking about d4.'),
  (15, 'O-O', 'King safety.'),
  (16, 'b6', 'Prepare ...Bb7 for the long-diagonal battle.'),
  (17, 'Nbd2', 'Complete the setup; a4 and Ne5 are the active tries.'),
  (18, 'Bb7', 'Complete development.'),
  (19, 'a4', 'Gain space and threaten a5 against the b6 chain.'),
  (20, 'a6', 'Restrain it — a long maneuvering game, London-style.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'london-system' and ol.rank = 6 on conflict (line_id, ply) do nothing;

-- Queen's Gambit (D06)
insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'queens-gambit'), 'Semi-Slav: Meran', 5) on conflict (opening_id, rank) do nothing;
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'd4', 'Take the center.'),
  (2, 'd5', 'Symmetrical reply.'),
  (3, 'c4', 'The Queen''s Gambit.'),
  (4, 'c6', 'Start with the Slav move order.'),
  (5, 'Nf3', 'Develop flexibly.'),
  (6, 'Nf6', 'Natural development.'),
  (7, 'Nc3', 'Pressure d5.'),
  (8, 'e6', 'The Semi-Slav: both center pawns defended, ...dxc4 plus ...b5 loaded.'),
  (9, 'e3', 'The solid main line, avoiding the razor-sharp Botvinnik 5.Bg5.'),
  (10, 'Nbd7', 'Flexible development, supporting both ...c5 and ...e5.'),
  (11, 'Bd3', 'Natural — and now the Meran machinery starts.'),
  (12, 'dxc4', 'The Meran: take exactly when the bishop must lose a tempo.'),
  (13, 'Bxc4', 'Recapture.'),
  (14, 'b5', 'Gain the tempo and start queenside expansion.'),
  (15, 'Bd3', 'Best retreat, back on the kingside diagonal.'),
  (16, 'a6', 'Support ...b4 and prepare the freeing ...c5.'),
  (17, 'e4', 'Claim the center while Black is still unraveling.'),
  (18, 'c5', 'The thematic counter — strike d4 before e5 lands.'),
  (19, 'e5', 'Push on, hitting the f6 knight — the critical Meran fight.'),
  (20, 'cxd4', 'Take; the wild lines after Nxb5 are the Meran''s main battlefield.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'queens-gambit' and ol.rank = 5 on conflict (line_id, ply) do nothing;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'queens-gambit'), 'Tarrasch Defense', 6) on conflict (opening_id, rank) do nothing;
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'd4', 'Take the center.'),
  (2, 'd5', 'Symmetrical reply.'),
  (3, 'c4', 'The Queen''s Gambit.'),
  (4, 'e6', 'Hold d5.'),
  (5, 'Nc3', 'Develop with pressure on d5.'),
  (6, 'c5', 'The Tarrasch: free piece play at the price of an isolated pawn.'),
  (7, 'cxd5', 'Take toward the isolani structure White wants.'),
  (8, 'exd5', 'Recapture, keeping the strong pawn presence on d5.'),
  (9, 'Nf3', 'Develop and eye the d4/e5 squares.'),
  (10, 'Nc6', 'Support c5/d4-breaks and develop.'),
  (11, 'g3', 'The Rubinstein plan: fianchetto against the d5 pawn.'),
  (12, 'Nf6', 'Natural development.'),
  (13, 'Bg2', 'The bishop takes aim at d5 — Black''s long-term burden.'),
  (14, 'Be7', 'Prepare to castle.'),
  (15, 'O-O', 'King safety.'),
  (16, 'O-O', 'Black castles; activity must compensate the structure.'),
  (17, 'Bg5', 'Pressure f6, indirectly d5 — the classic anti-Tarrasch piece.'),
  (18, 'cxd4', 'Resolve the tension before d4xc5 comes.'),
  (19, 'Nxd4', 'Recapture; the isolated d5 pawn is fixed as the target.'),
  (20, 'h6', 'Put the question to the bishop — the main tabiya of the Tarrasch.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'queens-gambit' and ol.rank = 6 on conflict (line_id, ply) do nothing;

-- Sicilian Dragon (B70)
insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'sicilian-dragon'), 'Yugoslav: 9.g4', 5) on conflict (opening_id, rank) do nothing;
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'White takes the center.'),
  (2, 'c5', 'The Sicilian.'),
  (3, 'Nf3', 'Prepare d4.'),
  (4, 'd6', 'Support the coming ...Nf6.'),
  (5, 'd4', 'The Open Sicilian.'),
  (6, 'cxd4', 'The thematic trade.'),
  (7, 'Nxd4', 'Recapture.'),
  (8, 'Nf6', 'Develop and hit e4.'),
  (9, 'Nc3', 'Defend e4.'),
  (10, 'g6', 'The Dragon.'),
  (11, 'Be3', 'Yugoslav development.'),
  (12, 'Bg7', 'Complete the fianchetto.'),
  (13, 'f3', 'Support e4, prepare the storm.'),
  (14, 'O-O', 'Castle.'),
  (15, 'Qd2', 'Prepare O-O-O.'),
  (16, 'Nc6', 'Develop with pressure on d4.'),
  (17, 'g4', 'The immediate bayonet: gain space before deciding on the king.'),
  (18, 'Be6', 'The main answer: develop and prepare ...d5 or ...Qa5 anyway.'),
  (19, 'Nxe6', 'Trade before ...Nxd4 — doubling Black''s pawns...'),
  (20, 'fxe6', '...but the f-file opens and e6/d5 gets a firm grip — double-edged.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'sicilian-dragon' and ol.rank = 5 on conflict (line_id, ply) do nothing;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'sicilian-dragon'), 'Fianchetto: 6.g3', 6) on conflict (opening_id, rank) do nothing;
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'White takes the center.'),
  (2, 'c5', 'The Sicilian.'),
  (3, 'Nf3', 'Prepare d4.'),
  (4, 'd6', 'Support the coming ...Nf6.'),
  (5, 'd4', 'The Open Sicilian.'),
  (6, 'cxd4', 'The thematic trade.'),
  (7, 'Nxd4', 'Recapture.'),
  (8, 'Nf6', 'Develop and hit e4.'),
  (9, 'Nc3', 'Defend e4.'),
  (10, 'g6', 'The Dragon.'),
  (11, 'g3', 'The Fianchetto: meet the dragon bishop with its mirror image.'),
  (12, 'Nc6', 'Develop with pressure on d4.'),
  (13, 'Nde2', 'Sidestep — keep the knight rather than allow ...Nxd4.'),
  (14, 'Bg7', 'Complete the fianchetto.'),
  (15, 'Bg2', 'The g2 bishop guards e4, freeing the pieces from defense.'),
  (16, 'O-O', 'Castle.'),
  (17, 'O-O', 'Both kings safe: a positional Dragon, not a race.'),
  (18, 'Rb8', 'Prepare the ...b5-b4 minority plan — Black''s standard counterplay.'),
  (19, 'a4', 'Restrain ...b5 immediately.'),
  (20, 'a6', 'Insist: ...b5 will come with support.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'sicilian-dragon' and ol.rank = 6 on conflict (line_id, ply) do nothing;

-- Modern Defense (B06)
insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'modern-defense'), 'Fianchetto: 4.g3', 5) on conflict (opening_id, rank) do nothing;
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'White takes the center.'),
  (2, 'g6', 'The Modern.'),
  (3, 'd4', 'Full center.'),
  (4, 'Bg7', 'The fianchetto.'),
  (5, 'Nc3', 'Development.'),
  (6, 'd6', 'Standard restraint.'),
  (7, 'g3', 'The positional treatment: mirror the fianchetto, deny targets.'),
  (8, 'Nc6', 'Provoke d5 or win the d4/e5 tension battle.'),
  (9, 'Be3', 'Hold d4 and keep the structure flexible.'),
  (10, 'e5', 'Stake the central claim before White finishes.'),
  (11, 'd5', 'Close, gaining space and shutting the g7 bishop''s file.'),
  (12, 'Nce7', 'Standard KID-style regrouping toward f5/g6.'),
  (13, 'Bg2', 'Complete the fianchetto; e4 is rock solid.'),
  (14, 'f5', 'The thematic break — Black''s entire play is here.'),
  (15, 'exf5', 'Trade to keep e4 for pieces and blunt the f-file.'),
  (16, 'gxf5', 'Recapture toward the center, opening the g-file.'),
  (17, 'Nge2', 'Develop while keeping f4 and d4 covered.'),
  (18, 'Nf6', 'Develop at last; ...O-O and ...f4 are the plan.'),
  (19, 'O-O', 'King safety.'),
  (20, 'O-O', 'Both castled — a maneuvering battle across the whole board.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'modern-defense' and ol.rank = 5 on conflict (line_id, ply) do nothing;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'modern-defense'), 'Pseudo-Yugoslav: ...c6 & ...b5', 6) on conflict (opening_id, rank) do nothing;
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'White takes the center.'),
  (2, 'g6', 'The Modern.'),
  (3, 'd4', 'Full center.'),
  (4, 'Bg7', 'The fianchetto.'),
  (5, 'Nc3', 'Development.'),
  (6, 'c6', 'The flexible move order: ...b5 comes before ...Nf6 exists to be hit.'),
  (7, 'Be3', 'The Yugoslav-style setup: Qd2, f3 and O-O-O are the plan.'),
  (8, 'd6', 'Standard restraint, transposing structures.'),
  (9, 'Qd2', 'Connect for O-O-O and eye h6.'),
  (10, 'b5', 'The point of ...c6: expansion with tempo-free support.'),
  (11, 'f3', 'Cover e4 and prepare the g4/h4 storm.'),
  (12, 'Nd7', 'Develop, keeping the g8 knight for f6 or h6 duty.'),
  (13, 'h4', 'Start the storm before Black''s arrives.'),
  (14, 'h5', 'The standard brake: fix h4 and deny g4 its full force.'),
  (15, 'Nh3', 'Reroute — the g5 outpost is the new target.'),
  (16, 'Ngf6', 'Complete development, covering g4 and e4-jumps.'),
  (17, 'O-O-O', 'Commit: opposite wings, full-speed attacks.'),
  (18, 'Qa5', 'The counterattack arrives with tempo threats on a2/c3.'),
  (19, 'Kb1', 'The standard prophylactic sidestep.'),
  (20, 'Bb7', 'Complete the setup — both sides race; one tempo decides.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'modern-defense' and ol.rank = 6 on conflict (line_id, ply) do nothing;

-- Caro-Kann Defense (B10)
insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'caro-kann'), 'Karpov: 4...Nd7', 5) on conflict (opening_id, rank) do nothing;
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'White takes the center.'),
  (2, 'c6', 'The Caro-Kann.'),
  (3, 'd4', 'Full center.'),
  (4, 'd5', 'Strike at e4.'),
  (5, 'Nc3', 'Defend e4 with a piece.'),
  (6, 'dxe4', 'Release the tension — the classical treatment.'),
  (7, 'Nxe4', 'Recapture with a centralized knight.'),
  (8, 'Nd7', 'The Karpov Variation: prepare ...Ngf6 without doubled pawns.'),
  (9, 'Ng5', 'The modern main line: probe f7 before Black consolidates.'),
  (10, 'Ngf6', 'Cover f7''s h5-attacker routes and develop; ...h6 must wait.'),
  (11, 'Bd3', 'Aim at h7 and prepare N1f3-e5 tricks.'),
  (12, 'e6', 'Blunt the d3 bishop and open the f8 bishop.'),
  (13, 'N1f3', 'The g1 knight joins; g5 and f3 coordinate against e6/f7.'),
  (14, 'Bd6', 'Active development, controlling e5.'),
  (15, 'Qe2', 'Pile on e6 and prepare O-O-O or Ne5.'),
  (16, 'h6', 'Finally put the question to the g5 knight.'),
  (17, 'Ne4', 'Retreat with tempo play on d6 — the point of Qe2.'),
  (18, 'Nxe4', 'Trade the attacker.'),
  (19, 'Qxe4', 'Recapture, keeping h7 under watch.'),
  (20, 'Qc7', 'Cover e5/h2 tricks and prepare ...b6 or ...c5 — the tabiya.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'caro-kann' and ol.rank = 5 on conflict (line_id, ply) do nothing;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'caro-kann'), 'Tartakower: 5...exf6', 6) on conflict (opening_id, rank) do nothing;
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'White takes the center.'),
  (2, 'c6', 'The Caro-Kann.'),
  (3, 'd4', 'Full center.'),
  (4, 'd5', 'Strike at e4.'),
  (5, 'Nc3', 'Defend e4 with a piece.'),
  (6, 'dxe4', 'Release the tension.'),
  (7, 'Nxe4', 'Recapture.'),
  (8, 'Nf6', 'Offer the trade — Black accepts a structural change for activity.'),
  (9, 'Nxf6+', 'Take; declining loses time.'),
  (10, 'exf6', 'The Tartakower: open the f8 bishop and keep a rock-solid king.'),
  (11, 'c3', 'Support d4 against the coming piece pressure.'),
  (12, 'Bd6', 'The bishop takes the strong kingside diagonal.'),
  (13, 'Bd3', 'Symmetrical development toward the king.'),
  (14, 'O-O', 'Castle early — Black''s whole setup is built for it.'),
  (15, 'Ne2', 'Flexible: keep f3 free for the f-pawn and avoid pins.'),
  (16, 'Re8', 'The rook takes the open e-file at once.'),
  (17, 'O-O', 'King safety.'),
  (18, 'c5', 'Break at d4 — Black''s active plan in this structure.'),
  (19, 'Be3', 'Hold d4 and complete development.'),
  (20, 'Nc6', 'Develop with pressure; Black''s pieces fully justify the pawns.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'caro-kann' and ol.rank = 6 on conflict (line_id, ply) do nothing;

-- French Defense (C02)
insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'french-defense'), 'Rubinstein Variation', 5) on conflict (opening_id, rank) do nothing;
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'White takes the center.'),
  (2, 'e6', 'The French.'),
  (3, 'd4', 'Full center.'),
  (4, 'd5', 'The planned break.'),
  (5, 'Nc3', 'Defend e4.'),
  (6, 'dxe4', 'The Rubinstein: trade the tension away for a compact game.'),
  (7, 'Nxe4', 'Recapture with a centralized knight.'),
  (8, 'Nd7', 'Prepare ...Ngf6 so a trade doesn''t wreck the pawns.'),
  (9, 'Nf3', 'Natural development.'),
  (10, 'Ngf6', 'Offer the trade on White''s terms no longer.'),
  (11, 'Nxf6+', 'Take — retreating concedes the tempo battle.'),
  (12, 'Nxf6', 'Recapture with the piece, keeping the structure clean.'),
  (13, 'Bd3', 'The active diagonal, eyeing h7.'),
  (14, 'c5', 'The essential break — without it Black suffocates.'),
  (15, 'dxc5', 'Trade toward a small but lasting development lead.'),
  (16, 'Bxc5', 'Recapture, completing a key developing move for free.'),
  (17, 'Qe2', 'Connect for O-O-O ideas and control e5.'),
  (18, 'O-O', 'King safety.'),
  (19, 'Bg5', 'The last piece out, pinning — White''s edge is activity.'),
  (20, 'b6', 'Solve the eternal French problem: ...Bb7 comes next.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'french-defense' and ol.rank = 5 on conflict (line_id, ply) do nothing;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'french-defense'), 'Exchange Variation', 6) on conflict (opening_id, rank) do nothing;
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'White takes the center.'),
  (2, 'e6', 'The French.'),
  (3, 'd4', 'Full center.'),
  (4, 'd5', 'The planned break.'),
  (5, 'exd5', 'The Exchange: trade into a symmetric, open structure.'),
  (6, 'exd5', 'Recapture — the c8 bishop is finally free.'),
  (7, 'Nf3', 'Develop toward the kingside.'),
  (8, 'Nf6', 'Mirror development.'),
  (9, 'Bd3', 'The active diagonal.'),
  (10, 'Bd6', 'Black mirrors — in symmetry, activity is everything.'),
  (11, 'O-O', 'King safety.'),
  (12, 'O-O', 'Black castles.'),
  (13, 'Bg5', 'Create the first asymmetry: pressure on f6.'),
  (14, 'Bg4', 'Answer in kind against f3.'),
  (15, 'Nbd2', 'Flexible: support Nf3, keep c3 free for the pawn.'),
  (16, 'Nbd7', 'Same mirror logic.'),
  (17, 'c3', 'Solidify d4 and open the queen''s path to b3/c2.'),
  (18, 'c6', 'Match it; both sides fight for the e-file next.'),
  (19, 'Qc2', 'Step off the pin''s file and eye h7.'),
  (20, 'Qc7', 'Symmetry holds — the middlegame is a pure activity contest.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'french-defense' and ol.rank = 6 on conflict (line_id, ply) do nothing;

-- Scandinavian Defense (B01)
insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'scandinavian'), 'Portuguese: 3.d4 Bg4', 5) on conflict (opening_id, rank) do nothing;
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'White takes the center.'),
  (2, 'd5', 'The Scandinavian.'),
  (3, 'exd5', 'White accepts.'),
  (4, 'Nf6', 'The gambit move order.'),
  (5, 'd4', 'White holds the extra pawn and builds.'),
  (6, 'Bg4', 'The Portuguese: develop with maximum piece pressure, pawn be damned.'),
  (7, 'f3', 'The critical test: kick the bishop and keep everything.'),
  (8, 'Bf5', 'Retreat but stay active — d3/c2 are the targets.'),
  (9, 'g4', 'The ''correspondence refutation'': kick again and grab space.'),
  (10, 'Bg6', 'Keep the diagonal; the bishop waits for e4/d3 to reappear.'),
  (11, 'c4', 'Cement d5 — White plays for the full point of material.'),
  (12, 'e6', 'Strike the pawn chain before White consolidates.'),
  (13, 'dxe6', 'Take — holding everything is impossible.'),
  (14, 'fxe6', 'Recapture toward the center; the f-file opens for the attack.'),
  (15, 'Nc3', 'Develop and cover the loose light squares.'),
  (16, 'Bb4', 'Pin — every Black piece points at White''s king.'),
  (17, 'Bg2', 'The kingside pawns advanced, so the bishop guards from g2.'),
  (18, 'Nc6', 'Full mobilization; d4 is the pressure point.'),
  (19, 'Ne2', 'Careful development; d4 and f4 both get cover (the c3 knight is pinned).'),
  (20, 'Qe7', 'Connect for ...O-O-O — Black''s activity vs White''s extra pawn.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'scandinavian' and ol.rank = 5 on conflict (line_id, ply) do nothing;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'scandinavian'), 'Icelandic Gambit: 3.c4 e6', 6) on conflict (opening_id, rank) do nothing;
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'White takes the center.'),
  (2, 'd5', 'The Scandinavian.'),
  (3, 'exd5', 'White accepts.'),
  (4, 'Nf6', 'The gambit move order.'),
  (5, 'c4', 'White holds the pawn the greedy way — inviting the Icelandic.'),
  (6, 'e6', 'The gambit: give a whole pawn for development and open lines.'),
  (7, 'dxe6', 'Accept — declining hands Black easy equality.'),
  (8, 'Bxe6', 'Recapture with the bishop, hitting c4 already.'),
  (9, 'd4', 'Take the center White is entitled to — but development lags.'),
  (10, 'Bb4+', 'Check, forcing a concession on the dark squares.'),
  (11, 'Bd2', 'The main block.'),
  (12, 'Qe7', 'Load the e-file against White''s uncastled king.'),
  (13, 'Bxb4', 'Trade off the pinning bishop — but it costs more time.'),
  (14, 'Qxb4+', 'Recapture with tempo — the queen forks b2 threats too.'),
  (15, 'Qd2', 'Block; b2 must be watched and the endgame beckons.'),
  (16, 'Nc6', 'Keep the queens on and hit d4 — trading helps White.'),
  (17, 'd5', 'Push, forking the c6 knight and e6 bishop...'),
  (18, 'O-O-O', '...answered by the point: the rook lands on d8 with a pin.'),
  (19, 'dxe6', 'Take the piece anyway.'),
  (20, 'Rxd2', 'The pin cashes in: queen for rook — dynamic balance.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'scandinavian' and ol.rank = 6 on conflict (line_id, ply) do nothing;

-- King's Indian Defense (E60)
insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'kings-indian'), 'Averbakh Variation', 5) on conflict (opening_id, rank) do nothing;
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'd4', 'White takes the center.'),
  (2, 'Nf6', 'Indian development.'),
  (3, 'c4', 'Space.'),
  (4, 'g6', 'The KID.'),
  (5, 'Nc3', 'Central development.'),
  (6, 'Bg7', 'The KID bishop.'),
  (7, 'e4', 'The big center.'),
  (8, 'd6', 'The standard structure.'),
  (9, 'Be2', 'Develop before committing the g1 knight.'),
  (10, 'O-O', 'Castle.'),
  (11, 'Bg5', 'The Averbakh: clamp e7 so the standard ...e5 is met by tactics.'),
  (12, 'c5', 'The main answer — since ...e5 is awkward, strike on the other wing.'),
  (13, 'd5', 'Close the center into a Benoni structure on White''s terms.'),
  (14, 'e6', 'Challenge the head of the chain immediately.'),
  (15, 'Qd2', 'Connect with Bg5-h6 ideas and keep e6/d5 tension.'),
  (16, 'exd5', 'Resolve toward an open e-file.'),
  (17, 'exd5', 'Keep the space-gaining Benoni bind rather than cxd5.'),
  (18, 'Re8', 'The rook exploits the freshly opened file.'),
  (19, 'Nf3', 'Complete development at last.'),
  (20, 'Bg4', 'Pin and prepare trades to ease the cramped position.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'kings-indian' and ol.rank = 5 on conflict (line_id, ply) do nothing;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'kings-indian'), 'Makagonov: 6.h3', 6) on conflict (opening_id, rank) do nothing;
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'd4', 'White takes the center.'),
  (2, 'Nf6', 'Indian development.'),
  (3, 'c4', 'Space.'),
  (4, 'g6', 'The KID.'),
  (5, 'Nc3', 'Central development.'),
  (6, 'Bg7', 'The KID bishop.'),
  (7, 'e4', 'The big center.'),
  (8, 'd6', 'The standard structure.'),
  (9, 'Nf3', 'Classical development.'),
  (10, 'O-O', 'Castle.'),
  (11, 'h3', 'The Makagonov: prepare Be3/g4 without allowing ...Ng4 or ...Bg4.'),
  (12, 'e5', 'The thematic strike anyway.'),
  (13, 'd5', 'Close the center — with h3 in, White''s g4 clamp is coming.'),
  (14, 'Na6', 'The modern route: the knight heads for c5 hitting e4.'),
  (15, 'Bg5', 'Provoke a concession before completing the setup.'),
  (16, 'h6', 'Ask the bishop.'),
  (17, 'Be3', 'Retreat with the point that ...Ng4 never works with h3 played.'),
  (18, 'Nc5', 'The knight arrives — pressure on e4 pins White''s pieces down.'),
  (19, 'Nd2', 'Overprotect e4 and unblock the f-pawn quietly.'),
  (20, 'a5', 'Anchor the c5 knight against b4 — the standard tabiya.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'kings-indian' and ol.rank = 6 on conflict (line_id, ply) do nothing;

-- Sicilian: Hyper-Accelerated Dragon (B27) — new opening
insert into public.openings (slug, name, eco, playable_colors, detection_keys) values ('hyper-accelerated-dragon', 'Sicilian: Hyper-Accelerated Dragon', 'B27', '{black,white}', '{"hyper accelerated dragon","hyper-accelerated dragon","hyperaccelerated"}') on conflict (slug) do nothing;
insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'hyper-accelerated-dragon'), 'Open: 4.Nxd4 into Accelerated Dragon', 1) on conflict (opening_id, rank) do nothing;
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'White takes the center.'),
  (2, 'c5', 'The Sicilian.'),
  (3, 'Nf3', 'Prepare d4.'),
  (4, 'g6', 'The Hyper-Accelerated Dragon: fianchetto on move two, no ...d6 yet.'),
  (5, 'd4', 'The Open Sicilian, the main test.'),
  (6, 'cxd4', 'The thematic trade.'),
  (7, 'Nxd4', 'The standard recapture.'),
  (8, 'Nc6', 'Develop, transposing toward the Accelerated Dragon.'),
  (9, 'Nc3', 'Natural development.'),
  (10, 'Bg7', 'The dragon bishop appears.'),
  (11, 'Be3', 'Cover d4 and prepare Qd2.'),
  (12, 'Nf6', 'Develop and hit e4.'),
  (13, 'Bc4', 'The critical setup — but without ...d6, ...d5 comes in ONE go.'),
  (14, 'O-O', 'Castle; the point of the accelerated order is speed.'),
  (15, 'Bb3', 'Prophylaxis against ...Nxe4 and ...d5 tricks on c4.'),
  (16, 'd6', 'Concede the one-move ...d5 for now; the structure is classic.'),
  (17, 'f3', 'Yugoslav-style support for e4 and g4.'),
  (18, 'Bd7', 'Standard development toward ...Rc8.'),
  (19, 'Qd2', 'Connect; both sides know the plans from the Dragon proper.'),
  (20, 'Nxd4', 'The typical trade, preparing ...b5 with gain of time.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'hyper-accelerated-dragon' and ol.rank = 1 on conflict (line_id, ply) do nothing;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'hyper-accelerated-dragon'), 'Maroczy Bind: 5.c4', 2) on conflict (opening_id, rank) do nothing;
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'White takes the center.'),
  (2, 'c5', 'The Sicilian.'),
  (3, 'Nf3', 'Prepare d4.'),
  (4, 'g6', 'The Hyper-Accelerated Dragon.'),
  (5, 'd4', 'The Open Sicilian.'),
  (6, 'cxd4', 'The thematic trade.'),
  (7, 'Nxd4', 'Recapture.'),
  (8, 'Nc6', 'Develop.'),
  (9, 'c4', 'The Maroczy Bind: clamp d5 and squeeze — the positional test.'),
  (10, 'Bg7', 'Complete the fianchetto; the bind demands patience.'),
  (11, 'Be3', 'Cover d4 against the g7 pressure.'),
  (12, 'Nf6', 'Develop — and set the famous trick.'),
  (13, 'Nc3', 'Natural — but now comes the point of Black''s move order.'),
  (14, 'Ng4', 'The exchange trick: the g7 bishop suddenly x-rays d4.'),
  (15, 'Qxg4', 'Best: take the knight — Nxc6 first is met by ...Nxe3.'),
  (16, 'Nxd4', 'The point: win the piece back with the centralized knight.'),
  (17, 'Qd1', 'Retreat; the d4 knight must now be evicted.'),
  (18, 'Ne6', 'Solid retreat, keeping the strong dark-square grip.'),
  (19, 'Qd2', 'Prepare Be2/O-O and restrain ...Qa5.'),
  (20, 'd6', 'Complete the setup; Black plays ...Bd7, ...O-O and ...a5 next.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'hyper-accelerated-dragon' and ol.rank = 2 on conflict (line_id, ply) do nothing;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'hyper-accelerated-dragon'), 'Queen Recapture: 4.Qxd4', 3) on conflict (opening_id, rank) do nothing;
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'White takes the center.'),
  (2, 'c5', 'The Sicilian.'),
  (3, 'Nf3', 'Prepare d4.'),
  (4, 'g6', 'The Hyper-Accelerated Dragon — inviting exactly this line.'),
  (5, 'd4', 'The Open Sicilian.'),
  (6, 'cxd4', 'The thematic trade.'),
  (7, 'Qxd4', 'The independent try: the queen eyes the h8 rook.'),
  (8, 'Nf6', 'The only good defense: block the diagonal by developing.'),
  (9, 'e5', 'Push with tempo — the critical continuation.'),
  (10, 'Nc6', 'Counterattack the queen instead of retreating.'),
  (11, 'Qa4', 'Keep the pin on c6 and stay active.'),
  (12, 'Nd5', 'Centralize with tempo threats of ...Nc7 and ...Nb6.'),
  (13, 'Qe4', 'The main line: hit d5 and hold e5 in one move.'),
  (14, 'Nc7', 'Retreat with the plan of ...Ne6 — the knight found work.'),
  (15, 'Bc4', 'Develop actively while Black regroups.'),
  (16, 'Ne6', 'The knight settles, covering the key dark squares.'),
  (17, 'O-O', 'King safety.'),
  (18, 'Bg7', 'The bishop finally lands, hitting e5.'),
  (19, 'Re1', 'Defend e5 laterally.'),
  (20, 'O-O', 'Castle; Black is fully coordinated and equal.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'hyper-accelerated-dragon' and ol.rank = 3 on conflict (line_id, ply) do nothing;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'hyper-accelerated-dragon'), 'Deferred Alapin: 3.c3', 4) on conflict (opening_id, rank) do nothing;
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'White takes the center.'),
  (2, 'c5', 'The Sicilian.'),
  (3, 'Nf3', 'Prepare d4.'),
  (4, 'g6', 'The Hyper-Accelerated Dragon.'),
  (5, 'c3', 'The deferred Alapin: build d4 with pawn support instead.'),
  (6, 'Bg7', 'Complete the fianchetto — d4 will be met by ...d5.'),
  (7, 'd4', 'Claim the full center.'),
  (8, 'cxd4', 'Trade first.'),
  (9, 'cxd4', 'Recapture, keeping the duo.'),
  (10, 'd5', 'The equalizing counter — the g7 bishop makes it work.'),
  (11, 'exd5', 'Take; defending e4 leaves d4 loose.'),
  (12, 'Nf6', 'The point: regain d5 with development, never with the queen.'),
  (13, 'Bb5+', 'The main try to hold the pawn awkwardly.'),
  (14, 'Nbd7', 'Block; the d5 pawn falls anyway.'),
  (15, 'Nc3', 'Develop and protect d5 one more time.'),
  (16, 'O-O', 'Castle first — the pawn isn''t running away.'),
  (17, 'O-O', 'White castles too.'),
  (18, 'Nb6', 'The regroup that finally wins d5 back.'),
  (19, 'Re1', 'Activity while the pawn falls.'),
  (20, 'Nbxd5', 'Recapture; the symmetrical structure is fully comfortable.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'hyper-accelerated-dragon' and ol.rank = 4 on conflict (line_id, ply) do nothing;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'hyper-accelerated-dragon'), 'Direct Maroczy: 3.c4', 5) on conflict (opening_id, rank) do nothing;
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'White takes the center.'),
  (2, 'c5', 'The Sicilian.'),
  (3, 'Nf3', 'Prepare d4.'),
  (4, 'g6', 'The Hyper-Accelerated Dragon.'),
  (5, 'c4', 'Straight to the Maroczy Bind structure.'),
  (6, 'Nc6', 'Develop toward the documented transposition.'),
  (7, 'd4', 'Open the center under bind conditions.'),
  (8, 'cxd4', 'Trade.'),
  (9, 'Nxd4', 'Recapture.'),
  (10, 'Bg7', 'The standard bind tabiya is reached.'),
  (11, 'Be3', 'Cover d4.'),
  (12, 'Nf6', 'Develop and probe e4.'),
  (13, 'Nc3', 'Complete the bind setup.'),
  (14, 'O-O', 'Castle.'),
  (15, 'Be2', 'Sensible development — g4 tricks are already defused here.'),
  (16, 'd6', 'The standard structure; d5 stays White''s, dark squares Black''s.'),
  (17, 'O-O', 'White castles.'),
  (18, 'Bd7', 'Prepare the thematic ...Nxd4 and ...Bc6 regroup.'),
  (19, 'Qd2', 'Connect and watch the a5/h6 diagonals.'),
  (20, 'Nxd4', 'The freeing trade — ...Bc6 and ...a5 counterplay follows.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'hyper-accelerated-dragon' and ol.rank = 5 on conflict (line_id, ply) do nothing;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'hyper-accelerated-dragon'), 'Anti-Sicilian: 3.Bc4', 6) on conflict (opening_id, rank) do nothing;
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'White takes the center.'),
  (2, 'c5', 'The Sicilian.'),
  (3, 'Nf3', 'Prepare d4.'),
  (4, 'g6', 'The Hyper-Accelerated Dragon.'),
  (5, 'Bc4', 'The club favorite: eye f7 and skip theory.'),
  (6, 'Bg7', 'Complete the fianchetto calmly.'),
  (7, 'c3', 'Support a d4 push and give the bishop a retreat.'),
  (8, 'e6', 'The antidote: blunt the bishop and prepare ...d5 in one strike.'),
  (9, 'd4', 'Claim the center anyway.'),
  (10, 'cxd4', 'Trade.'),
  (11, 'cxd4', 'Recapture with the duo.'),
  (12, 'Ne7', 'Develop without blocking the g7 bishop or allowing e5 tempo.'),
  (13, 'O-O', 'King safety.'),
  (14, 'O-O', 'Black castles, fully prepared for the break.'),
  (15, 'Nc3', 'Develop and hold d5 in advance.'),
  (16, 'd5', 'The point of Black''s whole setup: full central equality.'),
  (17, 'exd5', 'Take — the tension favors Black otherwise.'),
  (18, 'exd5', 'Recapture toward the center; the c4 bishop is now a target.'),
  (19, 'Bb3', 'Forced retreat from the ...dxc4 threat.'),
  (20, 'Nbc6', 'Complete development; Black stands actively and equal.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'hyper-accelerated-dragon' and ol.rank = 6 on conflict (line_id, ply) do nothing;

-- King's Gambit (C30) — new opening
insert into public.openings (slug, name, eco, playable_colors, detection_keys) values ('kings-gambit', 'King''s Gambit', 'C30', '{white}', '{"kings gambit","king''s gambit"}') on conflict (slug) do nothing;
insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'kings-gambit'), 'Accepted: Kieseritzky 4...g4', 1) on conflict (opening_id, rank) do nothing;
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'Take the center.'),
  (2, 'e5', 'Symmetrical reply.'),
  (3, 'f4', 'The King''s Gambit: give a pawn to rip open the f-file.'),
  (4, 'exf4', 'Accepting is the main move — Black takes the challenge.'),
  (5, 'Nf3', 'The King''s Knight Gambit: stop ...Qh4+ and develop.'),
  (6, 'g5', 'The classical defense: hold f4 at any cost.'),
  (7, 'h4', 'Undermine the chain immediately.'),
  (8, 'g4', 'Push — the point of no return.'),
  (9, 'Ne5', 'The Kieseritzky: the knight sits mightily in the center.'),
  (10, 'Nf6', 'The modern main line: counterattack e4 at once.'),
  (11, 'd4', 'Claim the center and open the c1 bishop toward f4.'),
  (12, 'd6', 'Put the question to the proud knight.'),
  (13, 'Nd3', 'The strange-looking retreat is the theory move: it eyes f4.'),
  (14, 'Nxe4', 'Take the pawn — material honesty check for both sides.'),
  (15, 'Bxf4', 'Regain the gambit pawn; development counts now.'),
  (16, 'Bg7', 'The long diagonal is Black''s whole game.'),
  (17, 'Nc3', 'Challenge the strong e4 knight.'),
  (18, 'Nxc3', 'Trade — retreating leaves White a free hand.'),
  (19, 'bxc3', 'Recapture toward the center; the b-file opens too.'),
  (20, 'c5', 'Strike at d4 — the main tabiya of the modern Kieseritzky.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'kings-gambit' and ol.rank = 1 on conflict (line_id, ply) do nothing;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'kings-gambit'), 'Accepted: Modern 3...d5', 2) on conflict (opening_id, rank) do nothing;
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'Take the center.'),
  (2, 'e5', 'Symmetrical reply.'),
  (3, 'f4', 'The King''s Gambit.'),
  (4, 'exf4', 'Accept.'),
  (5, 'Nf3', 'The King''s Knight Gambit.'),
  (6, 'd5', 'The Modern Defense: give the pawn right back for free play.'),
  (7, 'exd5', 'Take — declining concedes the center.'),
  (8, 'Nf6', 'Develop and regain d5 with a piece, not the queen.'),
  (9, 'Bb5+', 'The main line: trade off the c6 defender in advance.'),
  (10, 'c6', 'Block and hit the bishop — the critical reply.'),
  (11, 'dxc6', 'Take en route; the structure clarifies.'),
  (12, 'Nxc6', 'Recapture with easy development for the pawn''s return.'),
  (13, 'd4', 'Build the center and open the c1 bishop toward f4.'),
  (14, 'Bd6', 'Overprotect f4 and aim at h2 — Black''s active setup.'),
  (15, 'O-O', 'Castle; the half-open f-file is White''s compensation.'),
  (16, 'O-O', 'Black castles too.'),
  (17, 'Nc3', 'Develop; both sides are fully mobilized.'),
  (18, 'Bg4', 'Pin the f3 knight — the fight is over f4 and d4.'),
  (19, 'Bxc6', 'Trade first, damaging the queenside structure.'),
  (20, 'bxc6', 'Recapture; two bishops versus better pawns — rich play.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'kings-gambit' and ol.rank = 2 on conflict (line_id, ply) do nothing;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'kings-gambit'), 'Accepted: Fischer Defense 3...d6', 3) on conflict (opening_id, rank) do nothing;
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'Take the center.'),
  (2, 'e5', 'Symmetrical reply.'),
  (3, 'f4', 'The King''s Gambit.'),
  (4, 'exf4', 'Accept.'),
  (5, 'Nf3', 'The King''s Knight Gambit.'),
  (6, 'd6', 'Fischer''s ''bust'': prepare ...g5 without allowing Ne5 ideas.'),
  (7, 'd4', 'Take the center — the principled answer.'),
  (8, 'g5', 'Hold f4 now that h4 lacks the Ne5 follow-up.'),
  (9, 'h4', 'Challenge the chain anyway.'),
  (10, 'g4', 'Push, as consistent as in the Kieseritzky...'),
  (11, 'Ng1', '...but here the knight must go home — Fischer''s whole point.'),
  (12, 'Bh6', 'Guard the f4-g5 chain — Black keeps the material.'),
  (13, 'Ne2', 'Redevelop against f4; the g1 detour cost real time.'),
  (14, 'Qf6', 'Reinforce f4 again and eye d4.'),
  (15, 'Nbc3', 'Develop with d5-jump ideas against the queen.'),
  (16, 'c6', 'Deny d5 and keep the wall standing.'),
  (17, 'g3', 'The thematic break: the f4 chain must be dissolved.'),
  (18, 'fxg3', 'Take — holding everything is impossible now.'),
  (19, 'Nxg3', 'Recapture with the knight, opening lines at last.'),
  (20, 'Ne7', 'Develop; material vs open lines — the Fischer battleground.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'kings-gambit' and ol.rank = 3 on conflict (line_id, ply) do nothing;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'kings-gambit'), 'Bishop''s Gambit: 3.Bc4', 4) on conflict (opening_id, rank) do nothing;
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'Take the center.'),
  (2, 'e5', 'Symmetrical reply.'),
  (3, 'f4', 'The King''s Gambit.'),
  (4, 'exf4', 'Accept.'),
  (5, 'Bc4', 'The Bishop''s Gambit: dare ...Qh4+ — the king walk is playable.'),
  (6, 'Nf6', 'The modern refutation attempt: develop and hit e4 instead.'),
  (7, 'Nc3', 'Defend e4 and develop.'),
  (8, 'c6', 'Prepare ...d5 with full support — Black''s main plan.'),
  (9, 'Bb3', 'Step aside in advance; d5 is coming regardless.'),
  (10, 'd5', 'The freeing break — Black returns the pawn for activity.'),
  (11, 'exd5', 'Take — the structure battle begins.'),
  (12, 'cxd5', 'Recapture, claiming central space.'),
  (13, 'd4', 'Counter in the center immediately.'),
  (14, 'Bd6', 'Guard f4 and develop actively.'),
  (15, 'Nge2', 'Develop against f4 without blocking the f1 rook''s future.'),
  (16, 'O-O', 'Castle.'),
  (17, 'O-O', 'White castles; the f4 pawn is surrounded.'),
  (18, 'Nc6', 'Complete development, holding d4 tension.'),
  (19, 'Bxf4', 'Regain the pawn at last.'),
  (20, 'Bxf4', 'Trade; an open, balanced middlegame — Bishop''s Gambit theory.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'kings-gambit' and ol.rank = 4 on conflict (line_id, ply) do nothing;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'kings-gambit'), 'Declined: Classical 2...Bc5', 5) on conflict (opening_id, rank) do nothing;
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'Take the center.'),
  (2, 'e5', 'Symmetrical reply.'),
  (3, 'f4', 'The King''s Gambit.'),
  (4, 'Bc5', 'The classical decline: the bishop forbids O-O forever.'),
  (5, 'Nf3', 'Develop and defend against ...Qh4+ ideas.'),
  (6, 'd6', 'Solidify e5 — the point of declining.'),
  (7, 'Nc3', 'Develop; taking on e5 too early runs into ...Qd4 tricks.'),
  (8, 'Nf6', 'Develop and pressure e4.'),
  (9, 'Bc4', 'Natural development, mirroring the bishop.'),
  (10, 'Nc6', 'Complete the knights; the position stays tense.'),
  (11, 'd3', 'Support e4 and open the c1 bishop.'),
  (12, 'Bg4', 'Pin the f3 knight — pressure against f4''s support.'),
  (13, 'h3', 'Put the question immediately.'),
  (14, 'Bxf3', 'Trade — keeping the pin costs a piece to g4-h5 traps.'),
  (15, 'Qxf3', 'Recapture; the queen supports the coming f4-f5 or fxe5.'),
  (16, 'exf4', 'Take at the best moment, exposing e4.'),
  (17, 'Bxf4', 'Recapture with the bishop, completing development.'),
  (18, 'Nd4', 'The point of Black''s play: hit the queen and c2.'),
  (19, 'Qd1', 'Retreat, covering c2 — the endgame squares matter.'),
  (20, 'O-O', 'Castle; a balanced, maneuvering middlegame follows.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'kings-gambit' and ol.rank = 5 on conflict (line_id, ply) do nothing;

insert into public.opening_lines (opening_id, name, rank) values ((select id from public.openings where slug = 'kings-gambit'), 'Falkbeer: 2...d5 3.exd5 e4', 6) on conflict (opening_id, rank) do nothing;
insert into public.line_moves (line_id, ply, san, explanation)
select ol.id, v.ply, v.san, v.explanation from (values
  (1, 'e4', 'Take the center.'),
  (2, 'e5', 'Symmetrical reply.'),
  (3, 'f4', 'The King''s Gambit.'),
  (4, 'd5', 'The Falkbeer: counter-gambit in the center immediately.'),
  (5, 'exd5', 'Accept — everything else concedes the center.'),
  (6, 'e4', 'The classical point: the cramping pawn wedge on e4.'),
  (7, 'd3', 'Undermine the wedge at once — the main line.'),
  (8, 'Nf6', 'Develop and support e4.'),
  (9, 'dxe4', 'Take; holding the wedge costs Black material.'),
  (10, 'Nxe4', 'Recapture with an active knight.'),
  (11, 'Nf3', 'Develop and cover the sensitive d4/e5 squares.'),
  (12, 'Bc5', 'The active diagonal — f2 is the target.'),
  (13, 'Qe2', 'Pin the e4 knight and prepare to castle long.'),
  (14, 'Bf5', 'Support the knight and develop with threats.'),
  (15, 'Nc3', 'Challenge the pinned knight — the critical moment.'),
  (16, 'Qe7', 'Counter-pin: now everything on the e-file hangs together.'),
  (17, 'Be3', 'Break the tension by offering the dark-square trade.'),
  (18, 'Nxc3', 'The forcing sequence begins: take toward the queen trade.'),
  (19, 'Bxc5', 'In-between: take the bishop with tempo on the queen.'),
  (20, 'Nxe2', 'Take the queen; after Bxe7 Nxf4 the storm ends level.')
) as v(ply, san, explanation)
join public.opening_lines ol on true join public.openings o on o.id = ol.opening_id where o.slug = 'kings-gambit' and ol.rank = 6 on conflict (line_id, ply) do nothing;

-- 4. backfill SRS cards for openings already in study
insert into public.user_lines (user_id, line_id, unlocked_moves)
select uo.user_id, ol.id, p.moves_per_block
from public.user_openings uo
join public.opening_lines ol on ol.opening_id = uo.opening_id
join public.profiles p on p.user_id = uo.user_id
where uo.is_active
on conflict (user_id, line_id) do nothing;

commit;
